### ISSUE TITLE
Добавить возможность формирования отчета в формате jUnit

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#102]
##

**Comment by allustin** [comment]
офтопик - @Pr-Mex а помнишь code coverage для обработок можно подсчитать ? или только через костыль встраивания в конфигурацию ?

**Comment by Pr-Mex** [comment]
Можно. Без встраивания. Только немного магии.

**Comment by allustin** [comment]
переименовал в JUnit - так честней.

офтопик - нашел кстати еще один формат CucumberJSON называется ;-)
очень удобен

**Comment by viskvortsov** [comment]
Я так понимаю, что выбранный формат отличается от стандартного junit?

А будет вот такой формат:
`<testsuites tests="14" name="1CUNIT" time="10" failures="0" errors="2" skipped="0">
<testsuite name="xunit">
<properties/>
<testsuite name="вк_НаборТестов_3SDO-22_Контроль процессов табелирования">
<properties/>
<testcase classname="вк_НаборТестов_3SDO-22_Контроль процессов табелирования" name="ТестДолжен_НеСоздатьПроцессыПоТабелю" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_3SDO-22_Контроль процессов табелирования" name="ТестДолжен_СоздатьДваПроцессаПоТабелю" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_3SDO-22_Контроль процессов табелирования" name="ТестДолжен_СоздатьТриПроцессаПоТабелю" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_3SDO-22_Контроль процессов табелирования" name="ТестДолжен_СоздатьОдинПроцессДосоздатьОдинПроцессПоУслуге" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_3SDO-22_Контроль процессов табелирования" name="ТестДолжен_ЗакрытьВсеЗадачиПоУслуге" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_3SDO-22_Контроль процессов табелирования" name="ТестДолжен_ЗакрытьВсеЗадачиПоОднойУслугеНеЗакрытьЗадачиПоВторойУслуге" time="0" status="passed"/>
</testsuite>
<testsuite name="вк_НаборТестов_3SDO-44_Корректировка вывода списка сотрудников">
<properties/>
<testcase classname="вк_НаборТестов_3SDO-44_Корректировка вывода списка сотрудников" name="ТестДолжен_НеСделатьЗаписьВРегистрОтсутствующие" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_3SDO-44_Корректировка вывода списка сотрудников" name="ТестДолжен_СделатьЗаписьВРегистрОтсутствующие" time="0" status="passed"/>
</testsuite>
<testsuite name="вк_НаборТестов_3SDO27">
<properties/>
<testcase classname="вк_НаборТестов_3SDO27" name="ТестДолжен_ПроверитьЧтоВСпискеТабелированияНетПросроченныхДат" time="0" status="error">
<error message="ВнешняяОбработка.xddTestRunner.МодульОбъекта, строка № 1 330 Если Объект.ЭтоНовый() Тогда Значение не является значением объектного типа (ЭтоНовый)"/>
</testcase>
<testcase classname="вк_НаборТестов_3SDO27" name="ТестДолжен_ПроверитьЧтоВПланированииНельзяТабелироватьПоПросроченнымДатам" time="0" status="error">
<error message="ВнешняяОбработка.xddTestRunner.МодульОбъекта, строка № 1 330 Если Объект.ЭтоНовый() Тогда Значение не является значением объектного типа (ЭтоНовый)"/>
</testcase>
</testsuite>
<testsuite name="вк_НаборТестов_ЗарплатныйБлок">
<properties/>
<testcase classname="вк_НаборТестов_ЗарплатныйБлок" name="ТестДолжен_ПроверитьПравильностьДанныхДляЗаполненияДереваПриемкиПрорабовБезОтборов" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_ЗарплатныйБлок" name="ТестДолжен_ПроверитьПравильностьДанныхДляЗаполненияДереваПриемкиПрорабовСОтборомПоПроекту" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_ЗарплатныйБлок" name="ТестДолжен_ПроверитьПравильностьДанныхДляЗаполненияДереваПриемкиПрорабовСОтборомПоПрорабу" time="0" status="passed"/>
<testcase classname="вк_НаборТестов_ЗарплатныйБлок" name="ТестДолжен_ПроверитьПравильностьДанныхДляЗаполненияДереваПриемкиПрорабовСОтборомПоПроектуПоПрорабу" time="0" status="passed"/>
</testsuite>
</testsuite>
</testsuites>`

Чтобы можно было его подхватить junit plugin в jenkins?

**Comment by Pr-Mex** [comment]
Цель данного issue именно работа с CI.

**Comment by nixel2007** [comment]
Эту закрываем?

**Comment by Pr-Mex** [comment]
Да
