### ISSUE TITLE
В каждую создаваемую процедуру добавлять коммент отладки

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#103]
Добавлять первой строкой во все процедуры код:
//Ванесса.ПосмотретьЗначение(Контекст,Истина);

**Comment by allustin** [comment]
Вообще-то есть кейс от @pumbaEO как лучше отлаживаться,может он лучше подойдет

**Comment by Pr-Mex** [comment]
У меня не заработало.

**Comment by Pr-Mex** [comment]
Сделано.
