### ISSUE TITLE
Ошибка при формировании epf

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#107]
Добрый день, не могу понять, ошибка это или я что-то недонастроил.
![2015-10-28_15-25-52](https://cloud.githubusercontent.com/assets/12106756/10783167/ea8fa20e-7d7f-11e5-8888-80dd7b269d13.png)

**Comment by Pr-Mex** [comment]
Сборка ручной командой из каталога TemplateEpf не должна работать.

Чтобы проверить разборку и сборку epf  - возьми любой готовый epf, распакуй его и собери обратно.

**Comment by viskvortsov** [comment]
Вообще изначальная проблема была в том, что не работала сборка из обработки.
Дело оказалось в том, что после заполнения переменной PATH нужно перезагрузиться.
Вопрос закрыт. Спасибо

**Comment by Pr-Mex** [comment]
Понятно.
На самом деле после заполнения переменной PATH достаточно перезапустить все сессии 1С, включая конфигуратор.
