### ISSUE TITLE
Поддержка таблиц данных (Data Tables) в описании шагов (не в примерах)

### ISSUE THREAD

**Issue by VoronyukM** [silverbulleters/vanessa-behavior#108]
В [спецификации cucumber](https://cucumber.io/docs/reference#data-tables) описана возможность использования т.н. Data Tables. Однако сейчас при попытке их использования выдается ошибка: 
```
Не смог загрузить [...].feature. Строка №[...], обнаружен символ "|", хотя не было ключевого слова "Примеры".
```
Это было бы удобно при верификации табличных частей документов и наборов записей регистров. Сейчас приходится идти обходными путями.

**Comment by Pr-Mex** [comment]
Да. Сейчас это не поддерживается.
Добавим в скором времени.
Спасибо, что напомнили об этом.

**Comment by VoronyukM** [comment]
Кстати, в начале я думал, что логично было бы первую строку преобразовать в имена колонок таблицы значений, но прочитав, например, как используются такие таблицы [здесь](http://www.agileforall.com/2011/10/cucumber-tip-key-value-tables/) и [здесь](https://thomassundberg.wordpress.com/2014/06/30/cucumber-data-tables/), понял, что заголовка у таблицы может и не быть, и лучше бы эту таблицу просто преобразовать в ТЗ с именами колонок в виде порядковых номеров встолбцов (1, 2, 3,..), а в тестах уже самому решать, что это будет - соответствие, массив, или таблица с именами в первой строке.
Возможно, вы уже в курсе этого:)

**Comment by Pr-Mex** [comment]
Сделано. Для совместимости с УФ пердаётся не ТаблицаЗначений, а массив структур.
Пример синтаксиса фичи:
https://github.com/silverbulleters/vanessa-behavior/blob/develop/features/Core/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1DataTables.feature

Пример реализации в коде:
https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Core/step_definitions/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1DataTables/ObjectModule.txt
**смотреть процедуру "ЯВыполняюШагСОбычнымПараметромИВПараметрыКоторогоПереданаТаблица"**
