### ISSUE TITLE
Вызов СоздатьДанныеПоТабличномуДокументу заканчивается падением, если была создана запись регистра сведений

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#109]
Создаю тестовые данные по макету:
Ошибка в ПередНачаломСценария. {Форма.УправляемаяФорма.Форма(4256)}: Ошибка при вызове метода контекста (СоздатьДанныеПоТабличномуДокументуСервер): Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:
НачалоСвойства: ret Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType: Ошибка преобразования данных XDTO:
НачалоСвойства: Value   Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType: Ошибка преобразования данных XDTO:
НачалоСвойства: {http://v8.1c.ru/8.1/data/enterprise/current-config}Filter  Форма: Элемент  Тип: {http://www.w3.org/2001/XMLSchema}anyType

Проблема в том, что в составе создаваемых данных есть запись регистра сведений и в составе структуры, которая возвращается из СоздатьДанныеПоТабличномуДокументуСервер появляется РегистрСведенийНаборЗаписей.

А с сервера насколько я понимаю напрямую СоздатьДанныеПоТабличномуДокументуСервер  не вызвать.

**Comment by Pr-Mex** [comment]
Возможно это проблема передачи контекста.
Попробуй написать перед вызовом серверного метода
Контекст = "";
КонтекстСохраняемый = "";

**Comment by viskvortsov** [comment]
Сделал как вы указали, но проблема не в передаче контекста, хотя с ним тоже бывают проблемы, если там появляется несериализуемое значение. Но это обходится, например:

Если КонтекстСохраняемый.Свойство("ТестируемоеПриложение") Тогда	
		ТП 											= КонтекстСохраняемый.ТестируемоеПриложение;	
		КонтекстСохраняемый.ТестируемоеПриложение 	= Неопределено;
	КонецЕсли;
	Если КонтекстСохраняемый.Свойство("ГлавноеОкноТестКлиента") Тогда
		КонтекстСохраняемый.ГлавноеОкноТестКлиента 	= Неопределено;
		ГЭ 											= КонтекстСохраняемый.ГлавноеОкноТестКлиента;	
	КонецЕсли;
	
	СоздатьТестовыеДанные();
	
	Если КонтекстСохраняемый.Свойство("ТестируемоеПриложение") Тогда	
		КонтекстСохраняемый.ТестируемоеПриложение 	= ТП;
	КонецЕсли;
	Если КонтекстСохраняемый.Свойство("ГлавноеОкноТестКлиента") Тогда
		КонтекстСохраняемый.ГлавноеОкноТестКлиента 	= ГЭ;	
	КонецЕсли;
	
Однако в указанном мной случае проблема именно в наличии РегистрСведенийНаборЗаписей в массиве возвращаемых значений. Возможно, стоит передавать КлючЗаписи вместо этого?
Пока приведенная проблема лечится путем передачи Неопределено вместо Данные:

&НаСервере
Функция СоздатьДанныеПоТабличномуДокументуСервер(ТабличныйДокумент, РежимыЗагрузкиИлиИмяКолонкиЗамещения, ИмяКолонкиЗамещения) //Экспорт
	Данные = Объект().СоздатьДанныеПоТабличномуДокументу(ТабличныйДокумент, РежимыЗагрузкиИлиИмяКолонкиЗамещения, ИмяКолонкиЗамещения);
	//Возврат Данные;
	Возврат Неопределено; //Данные;
КонецФункции

**Comment by Pr-Mex** [comment]
Понял. Посмотрю что можно сделать.

**Comment by Pr-Mex** [comment]
Сделано. Заменил набор записей на массив КлючейЗаписи при передаче на тонкий клиент.
