### ISSUE TITLE
Параметры

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#118]
Для выделения чего-то в тексте использовать символ (звездочка) а для параметров символ (кавычка) или наоборот. Проблема в том, что люди использую кавычки чтобы выделить в фиче имя справочник или имя кнопки, табличной части и т.д. (короче: как-то выделить какую-то хрень которую как параметр не планируется использовать). В итоге мы имеем параметры нифиг никому не нужные...

**Comment by Pr-Mex** [comment]
Согласен.
Предлагаю это зафиксировать в инструкции.

**Comment by Pr-Mex** [comment]
Закрываю, т.к. это не требует доработки кода.
