### ISSUE TITLE
Продумать возврат значения "Отказ" и других подобных при формировании "Тогда"

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#119]
Продумать возврат значения "Отказ" и других подобных при формировании "Тогда".
Например

	Когда в ТЧ "ДанныеКонтрагента" я нажимаю кнопку "Событие"
	И количество событий по контрагенту равно 0 
	Тогда Отказ (или Отмена или еще что-нибудь подобное)

**Comment by Pr-Mex** [comment]
Афтар передумал.

**Comment by Hissin** [comment]
Афтар не передумал, афтар поднял глаза к небу и с глубоким вдохом согласившись об отсутствии логики у мужчин решил сжалостивиться и снять сию тяжелую задачу с плеч Pr-Mex
