### ISSUE TITLE
Отрицательные числа в описании шагов обрабатываются некорректно

### ISSUE THREAD

**Issue by VoronyukM** [silverbulleters/vanessa-behavior#122]
Например, 
```` Допустим количество равно -1 ```` 
преобразовывается в 
```` КоличествоРавно_1() ```` 

А при использовании Data Tables трактуются как строки

**Comment by Pr-Mex** [comment]
Ок. Буду смотреть.

**Comment by Pr-Mex** [comment]
Сделано. Прошу проверить.

**Comment by Pr-Mex** [comment]
Для  Data Tables тоже -1 трактуется как число.

**Comment by Pr-Mex** [comment]
Закрываю.
