### ISSUE TITLE
Добавить скриншот при возникновении бага (аттач в аллюре).

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#149]

**Comment by allustin** [comment]
тут со скриншотами началась активная работа с инструкциями

например в #209

**Comment by 1cto** [comment]
Отдельное спасибо за эту возможность! Стало проще показывать аналитику да и программисту, почему сценарий не прошёл на конкретном шаге - ведь на их тестовой базе всё работало...
А так шаг падения есть и скриншот есть, очень удобно. Я так 2 сценария на CI полечил.

**Comment by Pr-Mex** [comment]
@1cto - пожалуйста!
Для этого и задумывалось!

**Comment by Pr-Mex** [comment]
Задачу закрываю, т.к. работает.
