### ISSUE TITLE
Не генерируется обработка по .feature файлу, если установлен глобальный флаг core.autocrlf=false

### ISSUE THREAD

**Issue by VoronyukM** [silverbulleters/vanessa-behavior#150]
В этом случае при чекауте
1) окончания строк в файле vanessa-behavior\lib\TemplateEpf\renames.txt типа Unix
2) а в vanessa-behavior\vendor\precommit1c\pyv8unpack.py:297
при генерации обработки идет разбор renames.txt-файлов по окончаниям строк типа Windows
        lines = lines.split('\r\n')

В качестве заплатки предлагаю для файлов renames.txt при чекауте устанавливать окончания строк типа Windows. Pull request прилагаю.

**Comment by Pr-Mex** [comment]
Ок. Проверим что скажет CI сервер.

**Comment by Pr-Mex** [comment]
Закрываю?

**Comment by VoronyukM** [comment]
Очистил workdir и сделал чекаут. Ошибка не воспроизвелась. 
Но есть артефакты - git сам изменил еще для некоторых renames.txt кодировку для windows и хочет коммита:
![Файлы, в которых git изменил сам line engings](http://s4.postimg.org/9h4wz1pjx/2015_11_26_13_12_17.png)
Здесь нечто подобное описано: [Refreshing a repository after changing line endings](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings)

В принципе, работе данные артефакты не мешают, но могу закоммитить эти файлы тоже и сделать еще один pull request, чтобы был красивый чекаут для core.autocrlf=false. Думаю, порушить билд это не должно. Сделать?

**Comment by Pr-Mex** [comment]
Да.
