### ISSUE TITLE
Исправить использование путей к фичаридеру при вызове обработки из вне

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#153]
Исправь использование путей к фичаридеру при вызове обработки из вне
По умолчанию бери временно каталог бихевора

Не найден каталог инструментов: e1cib\tempstorage

**Comment by Pr-Mex** [comment]
Если речь идёт про переменную "КаталогИнструментов" то тут ничего не сделать. Это переменная для того и существует, чтобы в ТонкомКлиенте указывать на нужный каталог. При передачи Vanessa-Behavior на сервер все связанные с ним файлы не передаются на сервер, поэтому переменная указывает не туда куда надо, поэтому вызывающая сторона сама должна указать нужное значение.

**Comment by Pr-Mex** [comment]
Закрываю?

**Comment by allustin** [comment]
#185 - по моему это связано

**Comment by Pr-Mex** [comment]
Это тот же тикет что и вот этот:
https://github.com/silverbulleters/vanessa-behavior/issues/175
Надо посмотреть на код вызывающей стороны. Я написал об этом в #175.
Закрываю.
