### ISSUE TITLE
Подгрузка библиотек при запуске из командной строки

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#155]
Хотелось бы в фиче или файле настроек иметь возможность указывать какие библиотеки используются.
Сейчас получается, что при запуске на сервере сборок снипеты пустые, хотя они реализованы в библиотеке

**Comment by Pr-Mex** [comment]
Согласен.

**Comment by Pr-Mex** [comment]
Сделано. Можно проверять.

**Comment by viskvortsov** [comment]
Правильно я понимаю, что настройка должна выглядеть вот так:
"КаталогиБиблиотек":[
"E:\git\vanessa-behavior\features\Libraries",
]

**Comment by Pr-Mex** [comment]
Да, только запятую надо убрать в этом примере, т.к. элемент только один.

**Comment by Pr-Mex** [comment]
Закрываю.
