### ISSUE TITLE
Действие выбор из выпадающего списка для поля ввода

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#156]
Действие выбора выпадающего списка для поля ввода, НЕ являющегося полем табличной части опознается как:
"И     В открытой форме в ТЧ "" из выпадающего списка с заголовком "Вариант распределения" я выбираю "На направления деятельности"

Сделано на примере формы элементы ПланыВидовХарактеристик.СтатьиРасходов в УТ 11.2

**Comment by Pr-Mex** [comment]
Нужен более подробный сценарий воспроизведения. Можно скриншот?

**Comment by viskvortsov** [comment]
Когда Я нажимаю кнопку командного интерфейса "Финансовый результат и контроллинг"
	И     Я нажимаю кнопку командного интерфейса "Статьи расходов"
	Тогда открылось окно "Статьи расходов"
	И     В открытой форме я нажимаю на кнопку с заголовком "Создать"
	Тогда открылось окно "Статья расходов (создание)"
	И     В открытой форме я открываю выпадающий список с заголовком "Вариант распределения"
	И     В открытой форме в ТЧ "" из выпадающего списка с заголовком "Вариант распределения" я выбираю "На направления деятельности"

для УТ 11.2. Пойдет так?

**Comment by Pr-Mex** [comment]
Да. Попробую у себя воспроизвести.

**Comment by Pr-Mex** [comment]
Исправил. Можно проверять.

**Comment by Pr-Mex** [comment]
Закрываю.
