### ISSUE TITLE
Некорректно определяется имя формы

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#159]
Если в форме есть группа страниц, то в строку с названием формы попадает название группы (страницы).

**Comment by Pr-Mex** [comment]
Можно пример как это воспроизвести?

**Comment by viskvortsov** [comment]
Хм. воспроизвести не удалось. Судя по всему это осталось от вчерашней версии. Пока наверное можно закрыть

**Comment by Pr-Mex** [comment]
Закрываю.
