### ISSUE TITLE
Не опознается свертывание/развертывание группы формы

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#160]
Сейчас таких групп полно в настройках в УТ 11.2 и ERP.

**Comment by Pr-Mex** [comment]
Нужен живой пример.

**Comment by sergpogo** [comment]
http://v8.1c.ru/metod/faq2/answer.jsp?id=677

**Comment by yuriybylinkin** [comment]
2015-12-03 17:16 GMT+03:00 sergpogo <notifications@github.com>:

> http://v8.1c.ru/metod/faq2/answer.jsp?id=677
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverbulleters/vanessa-behavior/issues/160#issuecomment-161652338>
> .
>



-- 
Былинкин Юрий

**Comment by Pr-Mex** [comment]
Через кнопконажималку можно )))
Я уже проверил.
Буду делать.

**Comment by Pr-Mex** [comment]
Сделано.
