### ISSUE TITLE
Закрытие TestClient перед закрытием менеджера теста при запуске из командной строки

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#161]
Было бы полезно, если есть подключенный TestClient, после прогона всех тестов перед закрытием сеанса, в котором выполняется vanessa, закрывать TestClient.
Сейчас он остается висеть после закрытия, если его отключение явно не прописывать последним шагом теста, что будет приводить к тому, что каждый сценарий будет открывать и закрывать свой сеанс.

**Comment by Pr-Mex** [comment]
Имеется ввиду запуск сценариев на CI?

**Comment by viskvortsov** [comment]
В первую очередь - да.

**Comment by Pr-Mex** [comment]
Потому что при разработке - удобно, когда сеанс TestClient уже открыт, тогда происходит передподключение к уже открытому сеансу.

**Comment by viskvortsov** [comment]
Переподключение это замечательно и для CI. Это ускоряет прохождение сценариев. Я немного про другое:
Предлагаю сделать флаг для командной строки, который будет закрывать TestCilent при закрытии основного сеанса с vanessa, чтобы testclient не оставался висеть.

**Comment by Pr-Mex** [comment]
Да. Я понял. Сделаю.

**Comment by Pr-Mex** [comment]
Сделано. Добавил параметр "ЗакрытьTestClientПослеЗапускаСценариев".
