### ISSUE TITLE
Добавить обработчик передачи значений в кавычках

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#162]
Иногда надо передавать значения в кавычках, например:
И  реквизит Наименование стал равен "ООО "Мечта"".
Надо решить как это делать.

**Comment by allustin** [comment]
Строковый параметр должен передаваться в апострофах.
Иначе будет геморой

**Comment by Pr-Mex** [comment]
У нас сейчас разрешены и кавычки и апострофы.

**Comment by allustin** [comment]
@Pr-Mex тут вопрос в другом - что используется в строковых реквизитах чаще. Кавычки.

Апострофы используются реже. Значит:

* строковые параметры указываются в апострофах, тогда позволительны кавычки
* когда в строковом параметре указан еще и апостроф, то мы будем его экранировать через скажем два апострофа.

Я думаю стоит поэкспериментировать со сценариями, чтобы понять конечное решение

**Comment by Pr-Mex** [comment]
@allustin Я думаю, для обратной совместимости надо оставить и кавычки и апострофы (т.к. сейчас уже разрешено), но приоритет делать на апострофы (как ты и предлагаешь)

**Comment by Pr-Mex** [comment]
Сделано.
Надо делать так:
И реквизит Наименование стал равен 'ООО "Мечта" моя'
