### ISSUE TITLE
Добавить во все билды закрытие TestClient после выполнения всех сценариев.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#163]

**Comment by allustin** [comment]
#169 - связаны очень активно

другое дело что - как это слишком магически выглядит - закрывать безусловно. может какой параметр в настройках создать - по умолчанию "закрывать безусловно"

**Comment by Pr-Mex** [comment]
Тут я имел ввиду TaskKill.
Иначе могут остаться окна после запуска всех сценариев, если что-то пошло не так.
Под билдами имеются ввиду билды на ci.silverbulleters.org

**Comment by Pr-Mex** [comment]
Уже сделано. Закрываю.
