### ISSUE TITLE
Закрывать все сеансы 1С при запуски билда.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#164]
Надо, если были проблемы при запуске предыдущего билда и остались открытые окна.

**Comment by viskvortsov** [comment]
Двумя руками за. частенько возникает проблема

**Comment by Pr-Mex** [comment]
Я думаю,что этот функционал лучше делать одним из шагов билда.
Т.е. это больше относится к настройке окружения для запуска билда, нежели к самому Vanessa-Behavior.

**Comment by viskvortsov** [comment]
Да, я не сразу сообразил. так и сделали

**Comment by Pr-Mex** [comment]
Тогда закрываю.
