### ISSUE TITLE
Ошибка при заборе дерева фич из эдитора

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#166]
{Форма.УправляемаяФорма.Форма(4609)}: Преобразование значения к типу Булево не может быть выполнено
	Если ЭтоLinux Тогда

Ошибка возникает только при асинхронном вызове. Либо сделай реквизитом, чтобы я могла передать извне, либо другим методом.

**Comment by Pr-Mex** [comment]
Добавил инициализацию переменной.
