### ISSUE TITLE
Шаг сценария происходит раньше, чем отрабатывает интерфейс (Вперед батьки в пекло)

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#170]
В некоторых случаях создается ощущение, что следующий шаг сценария происходит до того как закончатся последствия предыдущего.

В моем случае есть два примера:
1. Проверяю изменение состояния справочника после нажатия кнопки записать.
Выдает ошибку, что элемент не изменился, а ставлю задержку в одну секунду и все хорошо.
2. Выдается ошибка  "Ошибка при вызове метода контекста (ПерейтиКСтроке): Метод не может быть вызван для данного объекта (Список);", а если поставить задержку все нормально.

Такая проблема особенно заметна на слабых машинах. Например, компьютеры разработчиков достаточно шустрые и на них все шаги сценария проходят. А вот CI сервер слабенький и на нем все подтормаживает.

Соответственно, вопросы:
1. Это действительно так или у нас коллективный глюк?
2. Кто как борется с вопросом?
3. Что можно сделать, кроме очевидных костылей в виде задержки (не очень хочется лишний раз вторгаться в поставляемые библиотеки)?

**Comment by Pr-Mex** [comment]
У меня такое не наблюдается. 
Можете скинуть CF, фичи, epf (только приватно)?
Запущу на самой медленной машине.
Скайп: pautovlv

**Comment by nixel2007** [comment]
У многих интерфейсных объектов в Тестируемом приложении есть методы Ожидать...(), например, `ОжидатьФормированияВыпадающегоСписка `.
Посмотрите в их сторону.

**Comment by viskvortsov** [comment]
Pr-Mex, сегодня поставил еще раз прогонять тесты на CI с задержкой.
Завтра с утреца постараюсь скомпоновать что-нибудь что можно отправить вам.

**Comment by viskvortsov** [comment]
Вообщем новости такие:
1. На очень шустрых компьютерах действительно бывает так, что проверка каких-то данных происходит раньше, чем данные запишутся после нажатия кнопки "Записать". 
В таком случае спасает секундная задержка перед проверкой.

2. На CI выставление задержек мне не помогло. Судя по всему проблема не в этом.
Если запускать на CI сервере ванессу самостоятельно при помощи командной строки, а если она запускается CI сервером (в моем случае, teamcity), то возникают ошибки. У нас возникают такие:
{Форма.Форма.Форма(328)}: Ошибка при вызове метода контекста (ПерейтиКСтроке): Метод не может быть вызван для данного объекта (СписокДокументыПоступления); ИмяФайла=E:\git\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf, ИмяПроцедуры=ВФормеВТаблицеЯПерехожуКСтроке
Эта ошибка возникает во всех без исключения случаях, когда используется метод. При этом названия ТЧ точно правильные и при интерактивном запуске все отрабатывает.

**Comment by Pr-Mex** [comment]
1. Насчет кнопки "Записать".
   За кнопкой "Записать" могут прятаться сколь угодно долгие процедуры, точно рассчитать задержу тут трудно. Я рекомендую использовать следующий приём:
	Ванесса.ЗапретитьВыполнениеШагов();
	ПодключитьОбработчикОжидания("ОбработчикОжидания",1);

затем
	&НаКлиенте
	Процедура ОбработчикОжидания()
                //тут вы ожидаете, что запись закончилась
		Ванесса.ПродолжитьВыполнениеШагов();
	КонецПроцедуры

**Comment by nixel2007** [comment]
Если нажимать кнопку "Записать и закрыть", то можно использовать процедуру `ОжидатьЗакрытия()`

**Comment by Pr-Mex** [comment]
@viskvortsov 
Насчет "ПерейтиКСтроке":
у вас агент Тимсити запускается как сервис или как приложение?

**Comment by viskvortsov** [comment]
ТимСити запускается как сервис

**Comment by Pr-Mex** [comment]
@viskvortsov 
У 1С есть особенность.
Некоторые механизмы 1С, основанные на таймерах могут не работать в режиме сервиса.
Я с этим уже сталкивался раньше.
Плюс, для работы автодокументирования режим сервиса всё-равно не подходит.
У меня все агенты Jenkins (и все агенты тимсити в прошлом) стартуют как приложение.
Для тимсити надо использовать команду \bin\agent.bat start
http://stackoverflow.com/questions/488443/running-watin-on-teamcity

**Comment by viskvortsov** [comment]
ОК, попробую. спасибо большое!

**Comment by viskvortsov** [comment]
@Pr-Mex совет действительно помог. Большое спасибо!

**Comment by Pr-Mex** [comment]
Не за что!
