### ISSUE TITLE
Несовпадение формулировки с процедурой

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#174]
В режиме кнопконажималки получается такой текст:
И     В открытой форме в ТЧ "вк_ТаблицаПроблемы" я изменяю флаг с именем "НаличиеПроблемы"

такой процедуры нет, но есть:
ВОткрытойФормеВТЧЯИзменяюФлагСЗаголовком(ИмяТЧ,ИмяРеквизита)

**Comment by Pr-Mex** [comment]
Какая версия VB используется?

**Comment by Pr-Mex** [comment]
Закрываю?

**Comment by viskvortsov** [comment]
Да
