### ISSUE TITLE
Надо вывести на форму каталог инструментов

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#175]
После использования бихевиора сторонней обработкой слетает каталог инструментов:
Не найден каталог инструментов: e1cib\tempstorage\

Выведи на форму, чтобы можно было устанавливать вручную в случае проблем

**Comment by Pr-Mex** [comment]
Каталог инструментов присутствует в "Объекте". Зачем его выводить на форму?

**Comment by Hissin** [comment]
@Pr-Mex  - Когда происходит вызов обработки из-вне я передаю туда каталог инструментов и он не выдает ошибку пути к каталогу инструментов. Но если при этом я работаю в твоей обработке параллельно, он перестает работать выдавая ошибку выше. Чтобы она исчезла, необходимо перезайти **полностью** в 1С, чтобы она заработала.

**Comment by nixel2007** [comment]
Каким образом происходит работа со второй обработкой? Выглядит как получение второй формы без передачи ключа уникальности

**Comment by Hissin** [comment]
@nixel2007  - это временный момент, скоро вызов перестанет быть актуальным. Но пока мне это необходимо для разработки. Проблема, похоже, в сохранении настроек, а не в ключе уникальности.

**Comment by Hissin** [comment]
@Pr-Mex  в том числе необходимо для использования, когда используешь встроенный вызов обработки из конфигурации

**Comment by Pr-Mex** [comment]
Покажи код, который вызывает обработку.

**Comment by Hissin** [comment]
@Pr-Mex - разверни конфу из service-conf-with-testclient в bdd-editor. там вызов.

**Comment by Pr-Mex** [comment]
Сделал пул-реквест.
Смотри.

**Comment by Pr-Mex** [comment]
Решено. Закрываю.

**Comment by Hissin** [comment]
Функционал: Использование бихавиора совместно с эдитором                                                                                                  
	Как пользователь                                                                                                                                      
	Я хочу одновременно работать в обоих обработках                                                                                                       
	Чтобы было удобно работать                                                                                                                            
	
Контекст:
	Дано конфигурация 1С

Сценарий: первичное получение фича-файлов из behavior
	Когда Я открываю обработку BDD-Editor
	И вызываю обработку behavior
	И передаю каталог инструментов в behavior
	Тогда я получаю дерево фича-файлов 

Сценарий: открытие behavior для дальнейшей работы
	Когда я закончила редактирование фича-файлов в BDD-Editore
	И открываю behavior для дальнейшей работы в этом же сеансе 1С
	И нажимаю "загрузить одну фичу" или "загрузить фичи из каталога"
	Тогда каталог инструментов заполняется корректный 
	И заполняется "Дерево тестов"
