### ISSUE TITLE
При выводе сообщений в лог 1С добавить возможность отключения показа времени

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#18]
При выводе сообщений в лог 1С добавить возможность отключения показа времени
Варианты:
- либо отдельный флаг для показа/подключения времени
- либо (что лучше) просто отключить показ времени при выводе в окно сообщений 1С

**Comment by Pr-Mex** [comment]
Чем не удобен показ времени?
По мне так как раз всё удобно.

**Comment by Pr-Mex** [comment]
Не актуально. Закрываю.
