### ISSUE TITLE
Ошибка при попытке создать шаблоны обработок

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#180]
Загружаю фичу →
```
# encoding: utf-8
# language: ru

Функционал:

Как Разработчик Vanessa Stack
Хочу Получать в качестве фикстуры файл json
Чтобы Фикстура была читаемой

Контекст:
	Дано Функция *ПолучитьФикстуру* возвращает файл json
```
→ нажимаю на кнопку "Создать шаблоны обработок" → получаю ошибку:

![screenshot_1](https://cloud.githubusercontent.com/assets/8247178/11822241/12693754-a387-11e5-9297-fe951be673ab.png)

**Comment by Pr-Mex** [comment]
Видимо не установлен питон.
Проверишь?

**Comment by Pr-Mex** [comment]
Добавил проверку на существование питона.
Если нет - то выводится сообщение при генерации EPF.
