### ISSUE TITLE
Не загружать автоматически ту фичу которая была при закрытии бехавоера

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#187]
Вместо автоматической загрузки выдавать вопрос, т.к. ошибочно вместо фич выбрал ярлык и теперь бехавоер не открывается

**Comment by Pr-Mex** [comment]
А ошибка появляется какая-нибудь?

**Comment by Pr-Mex** [comment]
Я думаю правильнее ошибку исправить, из-за которой не открывается форма.
Многим удобно, когда открывается фича, которая была при закрытии формы.

**Comment by Pr-Mex** [comment]
Проблема оказалась в epf, которая не компилируется. Буду смотреть.

**Comment by Pr-Mex** [comment]
Проверил. Это ошибка платформы. Иногда она игнорирует попытку/исключение при подключении внешних обработок.
Ситуацию удалось воспроизвести на чистой системе.
Буду регистрировать ошибку платформы.

**Comment by Pr-Mex** [comment]
Я получил официальный ответ от 1С.
Это не баг - это фича.
Если в подключаемой epf форма не компилируется, то на экране появится ошибка, и попытка/исключение тут не поможет.
Проверяйте ваши модули на корректность синтаксиса.
Итого - задачу закрываю.

Ответ от 1С:

> Здравствуйте!
Ваше обращение зарегистрировано под номером SW1009268 / 2.
Пожалуйста, в тексте следующих обращений на эту же тему ссылайтесь на этот номер.

>Никакой ошибки нет.
Дело в том, что исходный текст внешней обработки содержит ошибку. Переменная ОбменДаннымиПовтИсп. Возникновение ошибки компиляции при загрузке модуля не может быть перехвачено конструкцией Попытка ... Исключение ... КонецПопытки.
Ровно такое же поведение будет и при ошибке компиляции при загрузке любого другого модуля.
Так было всегда в 1C:Предприятии 8.

**Comment by artbear** [comment]
>Ровно такое же поведение будет и при ошибке компиляции при загрузке любого другого модуля.

1С слегка лукавит :)
При загрузке синтаксически неверного кода через Выполнить будет ошибка, которая ловится через Попытка..Исключение. И это хорошо, правильно и удобно.

А вот при загрузке других модулей непорядок :(
