### ISSUE TITLE
Как поступать при генерации шагов если две кнопки в форме имеют один заголовок

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#189]
Например, в форме есть две ТЧ, у которых есть кнопки "Добавить".
Сейчас при использовании библиотеки будет нажиматься строго одна из них.

Будет ли реализовываться такой функционал?

**Comment by yuriybylinkin** [comment]
В автоматизированном тестировании все объекты можно искать по заголовку и
по наименованию. Очевидно, что заголовки могут дублироваться, наименование
- не должно. Может быть поиск сделать по наименованию?

22 декабря 2015 г., 11:34 пользователь viskvortsov <notifications@github.com
> написал:

> Например, в форме есть две ТЧ, у которых есть кнопки "Добавить"
> Сейчас при использовании библиотеки будет нажиматься строго одна из них
>
> Будет ли реализовываться такой функционал?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverbulleters/vanessa-behavior/issues/189>.
>



-- 
Былинкин Юрий

**Comment by Pr-Mex** [comment]
Насчет ТЧ - да. Это предусмотрено. Повышу приоритет у этой задачи.
Насчет дублей заголовков у обычных полей - это уже сделано. 
Если есть дубль - будет генерироваться шаг:
"Тогда я в поле с именем делаю то-то".
Если заголовок уникальный для данной формы
"Тогда я в поле с заголовком делаю то-то".

Если изначально поле было с уникальным заголовком, но потом добавили ещё одно с таким же, будет выдано исключение об неуникальности заголовков и предложено заменить поиск по заголовку на поиск по имени.

Насчёт того, чтобы искать всегда по имени - я стараюсь уйти от этого, т.к. Gherkin предполагает, что любой пользователь может спокойно читать что там написано. А внутренние имена метаданных, такие как "ПолеСтр1ДляПоискКонтраегнтНаим2" ему не доступны, и не читаемы.

В принципе можно сделать опцию, чтобы шаги всегда генерировались с поиском по имени, но надо чётко осознавать минусы этого.

**Comment by Pr-Mex** [comment]
Специально проверил для ТЧ. Там всё работает корректно, т.к. генерируется шаг
**И     В открытой форме в ТЧ "ТабличнаяЧасть1" я нажимаю на кнопку с заголовком "Добавить".**
Проблемы будут, когда есть две кнопки формы с одинаковым заголовком.

**Comment by allustin** [comment]
@Pr-Mex - надо зафиксировать в документации. В Gherkin используем не 1С специалистом понятные формулироки, если мы туда добавим магию - нас не поймут. Тот же Аслак скажет что мы идиоты.

Если кто-то хочет проверить ПолеСтр1ДляПоискКонтраегнтНаим2 - тогда пора начинать писать сценарии кодом, а не только полагаться на кнопконажималку.

Вообще кнопконажималка сделана для скорости входа в технологию, а не как серебряная пуля.

@Pr-Mex офтопик - поздравляю кстат: теперь ты типа "коренной" ;-)

**Comment by Pr-Mex** [comment]
Именно поэтому я стараюсь сохранить читаемые заголовки элементов форм, а не внутренние имена.
P.s. спасибо!

**Comment by Pr-Mex** [comment]
Сделано.
