### ISSUE TITLE
Лог нужно формировать в 2-х вариантах: в окне 1С и в лог-файле

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#19]
Лог нужно формировать в 2-х вариантах: в окне сообщений 1С и в лог-файле.
В окне 1С по флажку удобно выводить краткий/полный лог
А в лог-файл нужно писать полный лог.

**Comment by Pr-Mex** [comment]
Вносились правки. Предлагаю уточнить что именно не так с логом.

**Comment by allustin** [comment]
#18 - стоит рассмотреть в комплексе вопросы логирования

**Comment by Pr-Mex** [comment]
Предлагаю эту проблему закрыть, т.к. есть #24

**Comment by Pr-Mex** [comment]
Не актуально. Закрываю.
