### ISSUE TITLE
Ошибка в процедуре ВывестиИзмененияФормыGherkin(Было,Стало)

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#190]
{Форма.УправляемаяФорма.Форма(6594)}: Поле объекта не обнаружено (Имя)
		Имя = ЭлемСтало.Имя;

Проявляется, если в массиве Стало.МассивЭлементов появляется элемент с типом "Тестируемая декорация формы"

**Comment by Pr-Mex** [comment]
Понял. Посмотрю.

**Comment by Pr-Mex** [comment]
Сделано.
