### ISSUE TITLE
В некоторых случая при нажатии "Запомнить состояние формы TestClient" вылетает в дамп

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#194]
Версия 0.858

В некоторых случаях при нажатии кнопки тестируемый сеанс вылетает в дамп.
Происходит на строго определенных формах.
Это платформа или к вам?

Имя журнала:   Application
Источник:      Application Error
Дата:          24.12.15 12:48:29
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     33A4
Описание:
Имя сбойного приложения: 1CV8C.exe, версия: 8.3.6.2390, метка времени: 0x562e7bb8
Имя сбойного модуля: testmc.dll, версия: 8.3.6.2390, метка времени: 0x562e7d30
Код исключения: 0xc0000005
Смещение ошибки: 0x0000770e
Идентификатор сбойного процесса: 0xaec
Время запуска сбойного приложения: 0x01d13e0ea11ef523
Путь сбойного приложения: C:\Program Files (x86)\1cv8\8.3.6.2390\bin\1CV8C.exe
Путь сбойного модуля: C:\Program Files (x86)\1cv8\8.3.6.2390\bin\testmc.dll
Идентификатор отчета: dcb94847-cc22-48b5-bc2a-68de42ecaa8e
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-24T05:48:29.000000000Z" />
    <EventRecordID>36089</EventRecordID>
    <Channel>Application</Channel>
    <Computer>33A4</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1CV8C.exe</Data>
    <Data>8.3.6.2390</Data>
    <Data>562e7bb8</Data>
    <Data>testmc.dll</Data>
    <Data>8.3.6.2390</Data>
    <Data>562e7d30</Data>
    <Data>c0000005</Data>
    <Data>0000770e</Data>
    <Data>aec</Data>
    <Data>01d13e0ea11ef523</Data>
    <Data>C:\Program Files (x86)\1cv8\8.3.6.2390\bin\1CV8C.exe</Data>
    <Data>C:\Program Files (x86)\1cv8\8.3.6.2390\bin\testmc.dll</Data>
    <Data>dcb94847-cc22-48b5-bc2a-68de42ecaa8e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Pr-Mex** [comment]
1. Это баг платформы. У меня он проявляется, когда в ТЧ нет строк.
2. В 0.858 я добился, чтобы у меня этот баг перестал появляться.
3. Дайте пример, когда он воспроизводится у вас, попробую обойти.

**Comment by viskvortsov** [comment]
Я тоже опытным путем увидел, что если в ТЧ добавить строку, тогда ошибка перестает появляться.
В приложении видео:
[2015-12-24_16-10-50.mp4.zip](https://github.com/silverbulleters/vanessa-behavior/files/71610/2015-12-24_16-10-50.mp4.zip)

**Comment by Pr-Mex** [comment]
Мне не удалось воспроизвести этот сценарий.
Но я добавил ещё одну служебную проверку, чтобы проверить, что в ТЧ есть строки.
Попробуйте у себя.

**Comment by Pr-Mex** [comment]
Закрываю?

**Comment by Pr-Mex** [comment]
Реакции нет. Пока закрываю.
