### ISSUE TITLE
Перепутаны значения в ожидали/получили

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#196]
Получаю ошибку сценария:
24.12.2015 20:46:22 {Форма.Форма.Форма(894)}: ТЧ Товары. Строка № 1. Колонка НДС. Ожидали 2,29, а получили 3,6; ИмяФайла=C:\AYS\git\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf, ИмяПроцедуры=ТаблицаФормыСИменемСталаРавной

Однако 3,6 - то, что у меня в сценарии
![565](https://cloud.githubusercontent.com/assets/12106756/11995230/5eebaf98-aa77-11e5-9b62-d31b5068c620.png)
а 2,29 - то, что получилось по факту.

Судя по всему, значения перепутаны при выводе

**Comment by Pr-Mex** [comment]
Сделано.
