### ISSUE TITLE
Формирование инструкции в серверном варианте базы

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#202]
При записи инструкции в серверной базе происходит вот такая ошибка:
![image](https://cloud.githubusercontent.com/assets/15178930/12298082/f4f7656c-ba18-11e5-9274-6040ed24eda8.png)
При этом на клиентской машине в соответствующей папке есть файлы скринов и журнала прогона сценария.

Хорошо бы на клиентской машине таки получить инструкцию в соотв. папке.

**Comment by allustin** [comment]
Текущий код для работы со скриншотами весь обраблён инструкцией &НаКлиенте - проверили весь

Поэтому нужно:

* версию Behavior ?
* версию платформы ?
* совместимость конфигурации - нет ли там веселухи с асинхровнными вызовами ?

P.S. Кстати @Pr-Mex - обрати внимание: люди используют функционал, который идет как сервисный ;-), больше чем основной: такая вот реальность ;-)

**Comment by 1cto** [comment]
Есть предположение, что это не от серверной базы зависит, а следствие вот этого бага https://github.com/silverbulleters/vanessa-behavior/issues/207

У меня на такой же по параметрам ВМ, и на той же серверной базе нет ошибки типа #207 и инструкция формируется на 0.869 версии.

Нужно будет проверить, почему у @JuniorBA такое происходит.

P.S.
А насчет сервисного функционала - это вы не переживайте, а то повторится дискуссия из гиттера ;-) Мы же не гики-разработчики, а больше техдиры, рп-ки, бизнес-аналитики и т.д. Как оказалось продукт на нас не ориентирован, и мы подбираем крошки с гиковского стола ;-)

**Comment by Pr-Mex** [comment]
Ну ты загнул. Не ориентированно оно на них )))
А на кого тогда?

**Comment by freddy121** [comment]
@Pr-Mex не буди в @1cto флудера. Опять в гиттере свалку устроите

**Comment by Pr-Mex** [comment]
Пусть выскажется, зачем в себе держать )))

**Comment by freddy121** [comment]
У него руки заняты. Он крошки подбирает с гиковского стола :rooster:

**Comment by allustin** [comment]
@1cto и @JuniorBA - проверьте на последней версии, исправлено

**Comment by 1cto** [comment]
Так таки что-то было? я вчера проверял на 0.869 - у меня не
воспроизводилось.

**Comment by Pr-Mex** [comment]
Тогда закрываю.
