### ISSUE TITLE
Ошибка при повторном выполнении сценария

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#205]
Открыл 1С → Открыл бехавоер → Загрузил фичу → Выполнил сценарий → Сценарий отработал корректно → Перезагрузил фичу → Выполнил сценарий → Сценарий отработал НЕ корректно (см. скриншот)

![2016-01-15_0-11-35](https://cloud.githubusercontent.com/assets/8247178/12337753/e9682498-bb1c-11e5-83a0-9550ee223d81.png)

**Comment by Pr-Mex** [comment]
Приложи фичу на которой это воспроизводится.

**Comment by Pr-Mex** [comment]
У тебя в коде написано
**ОписаниеФичИРодительскихКаталогов = Контекст.ФормаОбработки.ПолучитьОписаниеФичИРодительскихКаталогов();**

а в переменной Контекст при определенных случаях значения может не быть
Поставь проверку, что оно там есть. Ошибка уйдёт.
Строка 149.
