### ISSUE TITLE
Подсветка элементов при снятии скриншота экрана в режиме TestClient

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#206]
на основе обратной связи людей пока не умеющих пользоваться github

```
хочется чтобы когда генерируем документацию HTML 
во вставленный скриншот добавлялась красная рамка 
на тот элемент который привязан к шагу.
```

**Comment by freddy121** [comment]
@junior-BA умеет. Он занят. Он рамки красные рисует целый день.
Упоминаю по его просьбе.

**Comment by allustin** [comment]
команда для Windows найдена

http://www.robvanderwoude.com/files/iviewcli.txt

**Comment by Pr-Mex** [comment]
А где там выделение активного элемента?

**Comment by allustin** [comment]
Там комбинация команд advancedbatch и activelement и X filter.
магия именно в X фильтре

**Comment by Pr-Mex** [comment]
ясно, надо посмотреть

**Comment by Pr-Mex** [comment]
нагуглить не удалось, пока не понятно как применить

**Comment by Pr-Mex** [comment]
Сделано с помощью собственных утилит.
Пока доступ ограничен.

**Comment by Pr-Mex** [comment]
Решено.
