### ISSUE TITLE
Проблема с html инструкцией

### ISSUE THREAD

**Issue by Junior-BA** [silverbulleters/vanessa-behavior#207]
Есть такая проблема:
запускаю первую фичу - пишет нормально
запускаю вторую фичу - вылетает. (всегда в разных местах)
Перезапускаю сеанс винды, запускаю вторую фичу - все ок.

Бывает вылетает после первого удачного прогона, а бывает после второго или третьего.

**Comment by allustin** [comment]
надо будет изучить https://irfanview-forum.de/forumdisplay.php?f=8

нужно знать версию Windows как минимум и версию InfanView

@Junior-BA скинешь ?

**Comment by Pr-Mex** [comment]
Можно заменить софт для снятия скриншотов. Их много разных.

**Comment by Junior-BA** [comment]
@allustin windows 8.1 64
4.41 - 32 bit

**Comment by allustin** [comment]
Нужно добавить на сборочный сервер проверку сценария

**Comment by 1cto** [comment]
@Junior-BA а можешь приложить скриншот ошибки от irfan? Я помню там было что-то невразумительное типа "Can't load library "" " - и именно с пустым именем библиотеки.

**Comment by Pr-Mex** [comment]
У меня такого не было ни разу.

**Comment by Pr-Mex** [comment]
Скрин ошибки в студию.

**Comment by Junior-BA** [comment]
При прогонке одной и той же фичи третий раз появилась ошибка
![2016-01-18_211454](https://cloud.githubusercontent.com/assets/16708250/12399061/65ddc0a4-be20-11e5-838e-7d301e82da6f.png)

**Comment by Pr-Mex** [comment]
Вот отсюда:
https://irfanview-forum.de/archive/index.php/t-612.html

**I had the exact same problem as "lifespeed". I used Irfanview to convert .CR2 files to JPG and had no problems but then suddenly, I start getting the "Error! Can't Load" message. I solved this by uninstalling Irfanview, and then re-installing it. This immediately cured the problem, taking care of whatever glitch had occured.
**

**Comment by Pr-Mex** [comment]
Предлагают снести его и поставить заново.

**Comment by Junior-BA** [comment]
снес и поставил заново - на 3м проходе опять ошибка
ставил две предыдущие версии - тоже самое

**Comment by allustin** [comment]
@Junior-BA стоп - а у вас случаем не RDP используется ?

**Comment by Junior-BA** [comment]
@allustin да. у меня рдп и у @1cto тоже рдп и у него работает. 1с стоит на рдм и ифран стоит на рдп.

**Comment by Pr-Mex** [comment]
А когда происходит запуск, окно РДП не бывает свёрнутым?
А то рдп при сворачивании гасит удалённую видеокарту сеанса.

**Comment by Junior-BA** [comment]
@Pr-Mex не. рдп не свернуто. я весь процесс вижу. если нужен видос - запишу.

**Comment by Pr-Mex** [comment]
Видос - давай.

**Comment by Junior-BA** [comment]
@Pr-Mex http://screencast.com/t/R92801g7B

**Comment by Pr-Mex** [comment]
На скринкасте версия 0.866.
Ради чистоты предлагаю проверить на текущей, 0.873.
После 0.866, кажется, были изменения по работе с HTML.

**Comment by Junior-BA** [comment]
@Pr-Mex все тоже самое(

**Comment by Pr-Mex** [comment]
Есть возможность проверить тоже самое на локальной машине?

**Comment by Pr-Mex** [comment]
Я немного переделал механизм снятия скриншотов. Проверьте сейчас.

**Comment by Pr-Mex** [comment]
Прошу сказать осталась ли проблема.

**Comment by Junior-BA** [comment]
Стало лучше.
1. Загрузил одну фичу (которая отрабатывается без ошибок) - инструкция записалась
2. Загрузил вторую фичу (которая отрабатывается без ошибок) - инструкция записалась
3. Загрузил третью фичу (которая отрабатывается без ошибок) - инструкция записалась
4. Загрузил четвертую фичу (которая отрабатывается с ошибкой) - инструкция записалась до ошибки
5. Загрузил вторую фичу (которая отрабатывается без ошибок) - инструкция вылетает

**Comment by Pr-Mex** [comment]
А какая ошибка была на шаге 5?

**Comment by Junior-BA** [comment]
![2016-03-15_140314](https://cloud.githubusercontent.com/assets/16708250/13775775/345edd5e-eaaf-11e5-89ca-7a04f7514842.png)
![2016-03-15_140430](https://cloud.githubusercontent.com/assets/16708250/13775774/345a0a90-eaaf-11e5-9c5c-3904d23c48ae.png)

**Comment by Junior-BA** [comment]
Прогоняю эту же фичу еще раз - такие же ошибки.
Меняю фичу - все ок.

**Comment by Pr-Mex** [comment]
Тогда предлагаю поступить просто.
Смените инструмент для снятия скриншотов.
Я только что проверил на NirCmd - работает.
Надо установить его:
http://www.nirsoft.net/utils/nircmd.zip
затем установить настройки в VB как на картинке
![image](https://cloud.githubusercontent.com/assets/8627416/13782094/28b1038a-eadf-11e5-9953-36a015045317.png)

**Comment by Junior-BA** [comment]
Папка с nircmd
![2016-03-15_213030](https://cloud.githubusercontent.com/assets/16708250/13789502/158034f8-eaed-11e5-8015-d6cb131fd235.png)
Настройка
![2016-03-15_213054](https://cloud.githubusercontent.com/assets/16708250/13789513/219838bc-eaed-11e5-8e0d-7c4d6387c65c.png)
При запуске фичи
![2016-03-15_213030](https://cloud.githubusercontent.com/assets/16708250/13789534/2e1fa642-eaed-11e5-83e6-eebb7fe23fd4.png)
Нажимаю "ок" - ничего не происходит

**Comment by Pr-Mex** [comment]
Уберите "s" лишнюю.

**Comment by Junior-BA** [comment]
Работает. Спасибо. Можно закрывать.

**Comment by Pr-Mex** [comment]
Ок. Закрываю.
