### ISSUE TITLE
Ошибка  при перегенерации epf. Создает снипет с пробелом

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#212]
Сценарий: Воспроизведение ошибки
Когда я выбираю фича-файл
И генерирую по нему epf
Тогда все снипеты формируются верно
Когда Я изменяю одно из условия фича-файла
И я выбираю фича-файл
И перегенерирую по нему epf 
Тогда снипет создается с пробелом

ДобавитьШагВМассивТестов(ВсеТесты,"ЯСоздаю документ(Парам01)","ЯСоздаю документ","Когда Я создаю документ ""Расходная накладная""");

Так произошло в двух обработках из двух :)

![image](https://cloud.githubusercontent.com/assets/13865220/12376252/02546252-bcfb-11e5-88d2-ccbd5685eea4.png)

![image](https://cloud.githubusercontent.com/assets/13865220/12376255/21de6f14-bcfb-11e5-9135-7c2945e6c850.png)

**Comment by Pr-Mex** [comment]
Прикрепи, пожалуйста, данную фичу к ишузу.

**Comment by Hissin** [comment]
@Pr-Mex - я уже ее исправила
Могу заново создать обе. или сам будешь править текст?

**Comment by Pr-Mex** [comment]
Нужен текст, где проблема воспроизводится.

**Comment by Hissin** [comment]
[ПоступлениеРедкогоТовараНаСклад.feature](https://files.zenhub.io/569b34bd5647418e083ae3f6)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Pr-Mex** [comment]
Это неразрывный пробел, код 160. Сделаю его замену.

**Comment by Pr-Mex** [comment]
Решено.
