### ISSUE TITLE
Добавить в параметры JSON-файла настроек путь к библиотекам

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#213]
Контекст: я использую в сценариях библиотеку по работе с формами
Когда я переношу выполнение сценариев на CI
Тогда при первом запуске ванесса не отрабатывает, потому что не найден путь к библиотеке
И нужно вручную указать путь к библиотекам, чтобы сценарии начали отрабатывать автоматически

**Comment by Pr-Mex** [comment]
Уже есть.
Это параметр, массив, "КаталогиБиблиотек".

**Comment by pumbaEO** [comment]
+ 
Когда указываю путь к библиотекам необходимо иметь возможность указывать относительные пути (./lib/) от текущего каталога

**Comment by 1cto** [comment]
Ага, тогда освежите тут: https://github.com/silverbulleters/vanessa-behavior/blob/develop/README.md
А то я как ёжик в тумане ;-)

**Comment by Pr-Mex** [comment]
@pumbaEO Текущий каталог - это который системный?

**Comment by pumbaEO** [comment]
Нет, по приоритету, текущий каталог тестов (если существет), относительно каталога запуска behavior

**Comment by 1cto** [comment]
А как параметр оформить?

Вот так: "КаталогиБиблиотек": "d:\BDD\vanessa-behavior\features\Libraries\",

Или вот так:
"КаталогиБиблиотек": [
"d:\BDD\vanessa-behavior\features\Libraries\",
]
?

**Comment by Pr-Mex** [comment]
Второе - это массив.
И запятая лишняя

**Comment by 1cto** [comment]
Ага, заработало. Первый реальный результат в allure:
![image](https://cloud.githubusercontent.com/assets/15178930/12376878/cebce786-bd11-11e5-8f08-4bc03e1bbc86.png)
