### ISSUE TITLE
precommit1c - переход на OneScript-версию

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/vanessa-behavior#214]
Предлагаю перейти на вызов [onescript-версии](https://github.com/xDrivenDevelopment/precommit1c/blob/develop/v8files-extractor.os) прекоммита, портированную c питона и расширенную мной в начале осени. 
Зачем?
* для среднестатистического 1сника наличие OneScript на машине будет более полезно, чем python
* предполагаю, что в соседних проектах silverbulleters наличие onescript уже требуется
* возможно пригодятся расширенные возможности oscript-версии

Поиск по репозиторию выдал еще упоминание питона в нечто под названием sikuli. Если там это не является требованием к исполнению чего-либо, то можно избавиться от необходимости установки python в принципе.

В отличие от python-версии, oscript-версия:
* не требует указания типа файла для сборки отчета/обработки
* позволяет собирать каталог обработок рекурсивно, повторяя структуру папок и обработок относительно начального каталога
* при работе из git умеет удалять файлы из индекса git (может использоваться для варианта, когда файлы epf физически не хранятся под гитом, а используются только исходники)
  
Полный список ключей [здесь](https://github.com/xDrivenDevelopment/precommit1c#Командная-строка-запуска-onescript).

В рамках бехавиора при беглом осмотре потребуется единственное (не считая имеющихся фич по загрузке питона и README) изменение здесь - https://github.com/silverbulleters/vanessa-behavior/blob/e6156badd3d11dae57548d9d5b329b1c76a2457a/src/vbFeatureReader/ObjectModule.txt#L1550

**Comment by Pr-Mex** [comment]
@allustin что скажешь?

**Comment by allustin** [comment]
@Pr-Mex да что скажу - это очередная коллизия.

Нам спокойней "политически" жить на python версии пока.
С другой стороны правильны  подходом было бы:

* передалать precommit в виде oscrip-lib
* сделать ему oscript precommit install и тогда все прозрачно.

В инсталятор я добавил завивисмость от Oscript - поэтому тут все будет распространяться единым бандлом.

gitsync - сейчас в процессе закрытого портирования в Vanessa-unpack
то есть в целом к релизу 1.3 все будет стабильно.

Что мне непонятно с precommit.os - это лицензия и права. А потом опять начнется "Gherkin не нужен", Cucumber только для тестировщиков, и "мы сделали"

я посмотрел Blame и https://github.com/xDrivenDevelopment/precommit1c/graphs/contributors

и мне совершенно непонятно на каких правах мы его можем использовать - лицензии то нет. а с этим будут проблемы как показала практика

@nixel2007 @EvilBeaver - можете как-то на досуге определиться с порядком распространения и лицензией ? я без троллинга, я именно для прозрачности.

**Comment by EvilBeaver** [comment]
@allustin мы делали его на пару с Артуром только чтобы не изучать самим питон (цель проекта 1Script в действии, как она есть). Я не претендую на этот код, все что я там делал, я делал для таких же людей, как я. Иными словами я свой код отдаю в Public Domain.

А если по хорошему, то там надо апачу или мозилу, как и в остальном xDD.

**Comment by allustin** [comment]
@pumbaEO что скажешь ? ставим в план по миграции ? твой питон хотят выпилить ;-)

**Comment by pumbaEO** [comment]
Без проблем. У меня этого гуталина(python) еще в undiff завались (но там сделал exe). 

Имхо, надо делать именно exe, чтоб просто команда v8files-extractor.exe, а при необходимости в temp папке создалась база для запуска v8reader правильная.

**Comment by nixel2007** [comment]
> У меня этого гуталина(python) еще в undiff завались

undiff1c к слову, тоже без лицензии :)

**Comment by nixel2007** [comment]
> А если по хорошему, то там надо апачу или мозилу, как и в остальном xDD.

поддерживаю.

**Comment by EvilBeaver** [comment]
@pumbaEO насчет exe мысль хорошая. Только в случае с 1script на линуксе exe придется запускать через mono.exe, а питоновский - по другому. Или 1С-ники не коммитят внешние обработки из-под линукса и можно не переживать?

**Comment by pumbaEO** [comment]
chmod +x v8reader.exe и уже не обязательно mono v8reader.exe делать.

т.к. 1с не поддерживает регулярные выражения, а парсинх root файла идет с
помощью com regexp, то в текущем вариаент разбор возможен только на
windows.

18 января 2016 г., 14:44 пользователь Andrei Ovsiankin <
notifications@github.com> написал:

> @pumbaEO <https://github.com/pumbaEO> насчет exe мысль хорошая. Только в
> случае с 1script на линуксе exe придется запускать через mono.exe, а
> питоновский - по другому. Или 1С-ники не коммитят внешние обработки из-под
> линукса и можно не переживать?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverbulleters/vanessa-behavior/issues/214#issuecomment-172505842>
> .
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by EvilBeaver** [comment]
> chmod +x v8reader.exe

У меня так не взлетало, помнится.. Но я особо не копал почему.

**Comment by pumbaEO** [comment]
пакет mono-msc надо поставить.

2016-01-18 16:31 GMT+03:00 Andrei Ovsiankin <notifications@github.com>:

> chmod +x v8reader.exe
>
> У меня так не взлетало, помнится.. Но я особо не копал почему.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverbulleters/vanessa-behavior/issues/214#issuecomment-172527633>
> .
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by stilet** [comment]
Сегодня попробовал с OneScript - так и не смог закоммитить внешнюю обработку- создал задачу:
https://github.com/xDrivenDevelopment/precommit1c/issues/62

**Comment by nixel2007** [comment]
Напишу на всякий случай и сюда 
oscript-версия требует установленных библиотек oscript-library из develop-ветки.

**Comment by nixel2007** [comment]
Так же потребуется изменение в переносе файлов прекоммита здесь - https://github.com/silverbulleters/vanessa-behavior/blob/develop/tools/developers.start.cmd
v8unpack.exe вынесен в каталог tools для отвязки от переменной окружения PATH

**Comment by allustin** [comment]
Тоже склоняюсь к этой задаче, по двум причинам:

* precommit1c на Oscript уже содержит v8unpack
* c python при установке в виртуальных средах может быть "беда" с дополнительными библиотеками в инсталяторе самого python

**Comment by artbear** [comment]
Давно пора :)
precommit1c на 1скрипт давно стабилизирован.

**Comment by g-ones** [comment]
@Pr-Mex - посмотри последние версии

https://github.com/zeratulayuris/precommit1c/tree/use_1c_designer
https://github.com/silverbulleters/precommit1c/commits/develop

Можно будет чуть упростить установку и поддержку

**Comment by nixel2007** [comment]
@g-ones @allustin хм, инсталлятор как-то пошёл параллельной веткой. Хотели же opm пакет? Я даже ожидаемое поведение примерно накидал в соседнем репо

**Comment by allustin** [comment]
@nixel2007 - на самом деле, я просто показал, что делать такие скрипты быстро, быстрей чем обсуждать его необходимость ;-)

**Comment by JohnyDeath** [comment]
@allustin ты ли это говоришь? Прям как будто антилустин написал. )

**Comment by nixel2007** [comment]
@allustin да ради бога, быстро) просто желательно это делать в рамках концепции с которой некоторые согласились и никто не возражал :D

**Comment by allustin** [comment]
@nixel2007 ладно... соглашусь. поторопился @g-ones к вебинару.

**Comment by nixel2007** [comment]
предлагаю хотя бы положить gitattributes для нормализации окончаний строк в bsl. Живой пример - https://github.com/silverbulleters/vanessa-behavior/pull/300
Прекоммит хоть и новый (2.0), но версия младше 2.0.2. В итоге получаем новый конфликт уже не из-за переименнования, а из-за различных способов окончания строк

**Comment by EvilBeaver** [comment]
@nixel2007 какая версия одноксрипт-прекоммита стабильная, какую можно взять в качестве версии сабмодуля?

**Comment by nixel2007** [comment]
@EvilBeaver версия 2.0.3 стабильная (в мастере, с тэгом).
После нее были только исправления логов в тестах.

Есть еще доработки @bambr1975 по части v8reader, которые еще не влиты в прекоммит, но, если я не ошибаюсь, на стабильность работы они не влияют.

**Comment by bambr1975** [comment]
там расширения к макетам двоичных данных, html и ActiveX добавились. Остальное по части precommit такое же, как и в 2.0.3

**Comment by nixel2007** [comment]
Закрываю
