### ISSUE TITLE
Порядок прохождения сценариев

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#219]
Добрый день,
У меня методологический вопрос.

Есть форма, в которой есть два сценария, например:
```
Контекст:
Когда я открываю форму с галочкой или подключаю открытую

Сценарий: Поставить галочку
Когда я ставлю галочку
Тогда галочка поставлена

Снять галочку
Когда я снимаю галочку
Тогда галочка снята
```

При этом при открытии формы галочка всегда снята.
Получается, что сценарий два будет отрабатывать, только если успешно завершается первый сценарий. Если по какой-то причине первый сценарий галочку не поставил, то второй завершится с ошибкой, так как галочка будет поставлена, а не снята.

Получается, что корректный feature должен выглядеть так:
```
Контекст:
Когда я открываю форму с галочкой

Сценарий: Поставить галочку
Когда я ставлю галочку
Тогда галочка поставлена

Снять галочку
Дано галочка поставлена
Когда я снимаю галочку
Тогда галочка снята
```

Вопросы таковы:
1. Имеет ли право на существование первый сценарий? (мои коллеги мотивируют такой вариант тем, что сначала идет сценарий, который ставит галочку, а затем тот который ее снимает и зачем нам еще что-то дополнительно делать). 
Однако, у меня уже не раз сборщик из-за этого выдавал ошибки в сценариях, которые сами по себе были корректными.
С другой стороны, получается, что если следовать второму сценарию, то для тестирования самого маленького шага необходимо делать большое количество подготовки в секции ДАНО.
2. Сценарии строго следуют друг за другом как в фича файле или их порядок может меняться?

**Comment by Pr-Mex** [comment]
1. Сценарии выполняются строго сверху вниз.
2. В BDD зависимость сценариев вполне нормальная вещь. Вы сами решаете - добиваться ли полной независимости сценариев или нет. Лично я к этому не стремлюсь.
Главное при расследовании падающих сценариев начинать с первого упавшего. Для этого я смотрю лог ЖР.

**Comment by Pr-Mex** [comment]
@viskvortsov Закрываю?

**Comment by viskvortsov** [comment]
Да, спасибо!
