### ISSUE TITLE
Запомнить состояние формы TestClient приводит к падению клиента тестирования

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#220]
Версия 0.873.
Падает на любых формах.

**Comment by Pr-Mex** [comment]
У меня отрабатывает нормально.
Дайте ваш сценарий.

**Comment by viskvortsov** [comment]
Платформа: 8.3.7.1845
Сделал видео:
[asd.mp4.zip](https://github.com/silverbulleters/vanessa-behavior/files/98583/asd.mp4.zip)

**Comment by viskvortsov** [comment]
Переход на 8.3.6 не помог. Все равно вылетает. У моих коллег тоже

**Comment by Pr-Mex** [comment]
Проверьте вариант, когда в списке будут строки.

**Comment by Pr-Mex** [comment]
И скажите, есть ли вообще в этой базе документы реализации.

**Comment by viskvortsov** [comment]
Добрый день, попробовал с наличием строк. Все равно падает.

Пока удалось установить следующую зависимость:
Если в форме нет таблицы, то падения не проиходит, все отрабатывает.
Но если таблица есть, то падает.

Раньше была проблема, что если в таблице нет строк, то происходит падение, но это вроде было исправлено.
А сейчас падает вне зависимости от наличия строк.

**Comment by viskvortsov** [comment]
Еще мне кажется, что раньше падал менеджер тестирования, а сейчас падает клиент, хотя не факт что так, уже плохо помню.

**Comment by Pr-Mex** [comment]
Раньше тоже падал TestClient.
Какой релиз 8.3.6 используете?

**Comment by viskvortsov** [comment]
8.3.6.2449

**Comment by Pr-Mex** [comment]
Для чистоты эксперимента дайте dt, на котором это срабатывает.

**Comment by viskvortsov** [comment]
https://www.dropbox.com/s/lt9zcbsioxjwpck/1Cv8.rar?dl=0

**Comment by Pr-Mex** [comment]
Разобрался. По идее надо регать баг в платформе, но сейчас быстрее обойти.
Падение происходило при обращении к картинке и невидимой надписи.

**Comment by Pr-Mex** [comment]
Проверьте сейчас.

**Comment by viskvortsov** [comment]
Проблема в списке похоже решена, но в форме документа падает. Вот пример:
[2016-01-23_08-35-12.mp4.zip](https://github.com/silverbulleters/vanessa-behavior/files/101652/2016-01-23_08-35-12.mp4.zip)
Воспроизвел на той же базе, что уже вам отправил.

**Comment by viskvortsov** [comment]
Воспроизводится на 8.3.6 и на 8.3.7

**Comment by Pr-Mex** [comment]
Убрал вызов проблемного метода. Проверьте сейчас.

**Comment by Pr-Mex** [comment]
Закрываю, т.к. нет ответа.
