### ISSUE TITLE
Как работать с табличными документами типа mxl?

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#221]
Если мне надо проверить, что вывелось в отчёт или в ВПФ, то как это сделать?
Например, по требованию, чтобы в печатной форме заказа поставщику товары выводились отсортированными по алфавиту.

**Comment by Pr-Mex** [comment]
Отразил в документации.
https://github.com/silverbulleters/vanessa-services/blob/master/ru-RU/behavior/Reports.md
