### ISSUE TITLE
Есть ли возможность из одного сценария вызывать другие?

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#222]
Суть задачи. У меня есть сценарий создания заказа клиента. Потом есть сценарий заказа поставщику по потребностям. Потом есть сценарий закупки, и затем сценарий отгрузки.
А мне нужен интегральный сценарий, который последовательно вызовет 4 сценария, описанные выше.

**Comment by g-ones** [comment]
[штатная функциональность](https://github.com/silverbulleters/vanessa-behavior/blob/develop/features/Core/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%D0%A1%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D1%8F%D0%9A%D0%B0%D0%BA%D0%A8%D0%B0%D0%B3%D0%B0.feature) вроде как

пример можно посмотреть в #217 - только что решили вопросы зацикливания

брать текущую develop версию

**Comment by 1cto** [comment]
@g-ones , спасибо, пошёл изучать. А зачем в штатной функциональности сценарий повторяется 4 раза?

**Comment by g-ones** [comment]
@1cto насколько я знаю - для эмуляции зацикливания, чтобы штатно обработать эту ситуацию.

**Comment by g-ones** [comment]
И еще - обратите внимание: как только вы начинаете работать с вложенными сценариями: очень важна структура каталогов 

```
Закупка\СтандартнаяЗакупка.feature
ОтрузкаСоСклада\СтандартнаяОткузка.feature
Продажа\СтандартнаяПродажа.feature
ИграВОптовку.feature
```

и еще в интегральном сценарии очень важна роль - чаще всего это "заказчик системы"

```
Как заказчик системы
  Я хочу чтобы система позволяла выполнить основные операции.
```

**Comment by Pr-Mex** [comment]
Ещё прошу учесть, что в фиче которая делает экспорт необходимо указать тег
@ExportScenarios

**Comment by Pr-Mex** [comment]
@1cto 
ты пишешь:
>> А зачем в штатной функциональности сценарий повторяется 4 раза?

По стандарту BDD каждый баг надо воспроизвести в сценарии, чтобы защититься от повторения бага в дальнейшем.
Поэтому этот сценарий такой какой он есть, т.к. именно такая ситуация с 4 сценариями воспроизводила баг.

**Comment by Pr-Mex** [comment]
Отразил этот момент в документации.
https://github.com/silverbulleters/vanessa-services/blob/master/ru-RU/behavior/ScenarioAsStep.md
