### ISSUE TITLE
CONTIBIUTION guideline

### ISSUE THREAD

**Issue by g-ones** [silverbulleters/vanessa-behavior#223]
При создании новых задач GitHub Делает подстветку в виде плашки

![image](https://cloud.githubusercontent.com/assets/16738467/12451691/d2c67c70-bf9b-11e5-9ccd-5ac9860b1b02.png)

наши пользователи конечно русско и украино язычные, но думаю догадаются

Нужно разработать документ помошник контрибьютора, куда включить

* как создавать задачи
* чем наполнять задачи

* как поучаствовать в проекте
* как читать документацию

и т.д.

то есть в нашей терминологии - это так:

```
Как внешний контрибьютор
Я хочу понимать как участвовать в проекте
Чтобы всем было комфортно

```

**Comment by allustin** [comment]
![image](https://cloud.githubusercontent.com/assets/55323/12454785/09753cc6-bfaa-11e5-8aa7-8f8961c39846.png)

сделано - опечатки исправляйте, могут наличествовать
