### ISSUE TITLE
Не работает изменение количества в тч

### ISSUE THREAD

**Issue by Junior-BA** [silverbulleters/vanessa-behavior#228]
Запись из фичи:
И     В форме "Заказ клиента 0000-000023 от *" в ТЧ "Товары" я выбираю текущую строку
И     В открытой форме в ТЧ "Товары" в поле с заголовком "Количество" я ввожу текст "5,000"
На этой строке вылетает
Видео тут:
http://screencast.com/t/DZGetG7szYA

**Comment by Junior-BA** [comment]
up

**Comment by Pr-Mex** [comment]
Решено. Проверьте.
