### ISSUE TITLE
Ошибка при попытке ПолучитьИзмененияФормыGherkin для печатной формы УТ 11.1

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#229]
Дано версия ванессы-бихейвер 0.874
  И версия конфигурации 1С:УТ 11.1.10.167
  И версия платформы 1С 8.3.6.2421
Когда я открываю существующий документ "Заказ поставщику"
и нажимаю кнопку "Печать"
и нажимаю кнопку "Заказ поставщику"
и получаю на экран печатную форму
и нажимаю в ванессе ПолучитьИзмененияФормыGherkin
тогда получаю ошибку про "Метод не может быть вызван для данного объекта"
{Форма.УправляемаяФорма.Форма(6870)}: Ошибка при вызове метода контекста (ПолучитьТекстОбласти)
   Значение = ЭлементФормы.ПолучитьТекстОбласти(Адрес);
по причине:
Метод не может быть вызван для данного объекта

При этом те же манипуляции на УТ 11.2 ошибки не дают.
Манипуляции с типовым отчётом в УТ 11.1 валовая прибыль отрабатывает корректно.

**Comment by 1cto** [comment]
@Pr-Mex апну на всякий случай

**Comment by Pr-Mex** [comment]
Решено. Проверьте.

**Comment by Pr-Mex** [comment]
Закрываю.
