### ISSUE TITLE
Ошибка генерации EPF

### ISSUE THREAD

**Issue by KatyaLR** [silverbulleters/vanessa-behavior#231]
При попытке сгенерировать epf  выдается сообщение "Для генерации EPF должен быть установлен Питон. В cmd должна выполняться команда: python --version". Хотя питон установлен и при выполнении команды cmd python --version выводится: Python 3.3.5. Работа происходит на Windows 8.

**Comment by KatyaLR** [comment]
Похоже под виндой питон версию выводит не через стандартный ввод/вывод

**Comment by allustin** [comment]
Добавлено требование по большему семантическому контролю установленных утилит

**Comment by Pr-Mex** [comment]
На Windows 8 всё неоднократно проверено. Странно.

**Comment by Pr-Mex** [comment]
Попробуйте пройтись отладчиком в функции УстановленПитон().
На других системах проблема не воспроизводится.

**Comment by KatyaLR** [comment]
Отладчик показал, что не проходит запись версии во временный файл: 

ИмяФайлаЛога = ПолучитьИмяВременногоФайла("txt");
Стр = "python --version > " + ИмяФайлаЛога;
	
ВыполнитьКомандуОС(Стр);

Когда открываю временный файл, он пустой.

**Comment by Pr-Mex** [comment]
а в переменной **ИмяФайлаЛога** какое значение?
возможно там русские символы, и не срабатывает команда консоли из-за кодировки

**Comment by 1cto** [comment]
Как-то так:
![image](https://cloud.githubusercontent.com/assets/15178930/13076879/fe4fa858-d4bd-11e5-9cfd-a4267f9382c7.png)

**Comment by Pr-Mex** [comment]
Решено. Проверьте.

**Comment by Pr-Mex** [comment]
Закрываю.
