### ISSUE TITLE
Ошибка перегенерации

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#232]
Генерирую шаблон обработки → Добавляю код в шаблон обработки → Добавляю в фичу шаг → Перегенерирую шаблон обработки → Открываю шаблон обработки в конфигураторе → Получаю ошибку формата потока.

**Comment by Pr-Mex** [comment]
Нужна сама обработка. На которой воспроизводится ошибка.

**Comment by alehinsasha** [comment]
[Алгоритмы.epf](https://files.zenhub.io/56a5aac6abb587fa56519646)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[Алгоритмы.feature](https://files.zenhub.io/56a5aad3abb587fa56519647)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by alehinsasha** [comment]
[Алгоритмы.epf](https://files.zenhub.io/56a67191abb587fa5651a60c)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[Алгоритмы.feature](https://files.zenhub.io/56a67198abb587fa5651a60f)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Ошибка не появляется если не добавлять свой код, добавил - появилась ошибка.

**Comment by g-ones** [comment]
http://ci.silverbulleters.org/job/Vanessa-Behavior-Develop/306/allure/#/behaviors/845398d69b1b3cd0/665cb83de903670a/expanded

Такая ситуация обрабатывается, нужно понять что различается в проверке В вашем случае между эталоном и проверкой на CI

**Comment by g-ones** [comment]
высянилось - что подобное связано напрямую с артефактами преыдущих сборок epf, когда они были неуспешно собраны

в моем случае проблема воспроизвелась с 3 вариантами:

* при неверной установке python
* при отсутствии в path v8unpack
* при ошибочном выборе режима асинхронности в проверяемой конфигурации

то есть:

1. скачиваем последний develop
2. инициализируем работу с помощью tools\developer.start.cmd

хитрим и убираем из path v8unpack - чтобы как будто мы его забыли скачать и не почитали README.

3. поключаем сервисную конфигурацию в 1С предприятии из каталога distr
4. запускаем в ней behavior
5. открываем behavior в режиме самотестирования - то есть загружаем собственные feature's
6. запускаем для проверки только 1 сценарий StepsGenerator\ПерегенерацияEPF.feature
7. получаем гарантированную ошибку - v8unpack то отстуствует
8. возращаем v8unpack на место и повторяем пункт 6
9. проблема не уходит - ошибка продолжается

@PrMex - хитрость в том что на CI - workspace настроен и очищается перед вызовами, а потом настраивается заново

Я пока не готов сказать, как исправить ситуацию удобней, но расширю Draft требования проверки - пока думаю, что стоит автоматизированно блокировать кнопки зависящие от внешних инструментов и проверять временные каталоги перед стартом сессии проверки.

**Comment by Pr-Mex** [comment]
Тут приведены epf которые уже не открываются в конфигураторе.
Надо выложить epf до перегенерации.

**Comment by nixel2007** [comment]
Покажите файл renames.txt из обработки. Есть шанс, что смогу указать причину (была подобная ошибка в старой версии v8reader при работе precommit1c)

**Comment by alehinsasha** [comment]
[Test.epf](https://files.zenhub.io/56b21a53cf14b71616c471fd)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

только что сгенерировал

**Comment by alehinsasha** [comment]
[Test.epf](https://files.zenhub.io/56b21ba4cf14b71616c47225)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

она же только с добавлением кода

**Comment by nixel2007** [comment]
Мне не нужны обработки) мне нужен файл renames.txt из src

**Comment by alehinsasha** [comment]
в src их два

1-й: \src\features\step_definitions\Алгоритмы

70e297e0-e8a2-43bf-8be1-62e408f610a1-->und\70e297e0-e8a2-43bf-8be1-62e408f610a1
70e297e0-e8a2-43bf-8be1-62e408f610a1.0-->D:\xDD\Rep\WorkShopSPR\src\features\step_definitions\Алгоритмы\Form\Форма\Форма.txt
70e297e0-e8a2-43bf-8be1-62e408f610a1.0-->und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0
70e297e0-e8a2-43bf-8be1-62e408f610a1.0-->und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0
79a499cc-1782-4a2f-abe7-61ea4d49fd5a-->und\79a499cc-1782-4a2f-abe7-61ea4d49fd5a
8aa13ab8-188a-4f59-be4f-031aa5450c90.0\info-->und\8aa13ab8-188a-4f59-be4f-031aa5450c90.0\info
8aa13ab8-188a-4f59-be4f-031aa5450c90.0\text-->ObjectModule.txt
copyinfo-->und\copyinfo
root-->und\root
version-->und\version
versions-->und\versions

2-й: \src\lib\ВерсионироватьОбработку

34418a1c-0421-46d3-b1ed-987cd190341d-->und\34418a1c-0421-46d3-b1ed-987cd190341d
34418a1c-0421-46d3-b1ed-987cd190341d.0-->Form\Форма\Форма.txt
34418a1c-0421-46d3-b1ed-987cd190341d.0-->und\34418a1c-0421-46d3-b1ed-987cd190341d.0
34418a1c-0421-46d3-b1ed-987cd190341d.0-->und\34418a1c-0421-46d3-b1ed-987cd190341d.0
9aa11b58-0179-46a9-b427-594eb80acdc7-->und\9aa11b58-0179-46a9-b427-594eb80acdc7
copyinfo-->und\copyinfo
root-->und\root
version-->und\version
versions-->und\versions

**Comment by nixel2007** [comment]
А renames.txt от самой обработки Test.epf?
Возможно он кладется не в корневой src, а где-то глубже/служебном каталоге. Либо сделайте пробный коммит Test.epf чтобы через precommit сработала распаковка

**Comment by nixel2007** [comment]
В момент перегенерации он создается в "каталог фича-файла"/step_definitions/src
при моих настройках, по крайней мере. после перегенерации сразу удаляется.

**Comment by nixel2007** [comment]
В общем, проблема может быть связана с некорректным формированием файла renames.txt
Попробуйте на вашей же машине обновить сабмодуль v8reader внутри precommit1c на последнюю версию.

**Comment by Pr-Mex** [comment]
Сейчас обновлю

**Comment by Pr-Mex** [comment]
Проблема была в чтении внутреннего формата epf при перегенерации.
Решено.
Можно проверять.

**Comment by alehinsasha** [comment]
Работает, спасибо!
