### ISSUE TITLE
Падение платформы при работе с динамически добавленными колонками

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#233]
При проверке равенства таблицы без строк происходит падение тестового клиента, если были динамически добавлены колонки 

При этом, конструкция:
 
Тогда таблица формы с именем "ТаблицаКурсов" стала равной:
    | 'Курс обучения'|

отрабатывает корректно.

Конструкция:

Тогда таблица формы с именем "ТаблицаКурсов" стала равной:
    | 'Учетная' | 'Курс обучения' |

где "Учетная" - динамически добавленная колонка, приводит к падению платформы.

**Comment by Pr-Mex** [comment]
А если в таблице есть строки тоже падает?

**Comment by viskvortsov** [comment]
Со строками нет.

**Comment by Pr-Mex** [comment]
Дайте скринкаст возникновения поблемы.

**Comment by viskvortsov** [comment]
[Архив.zip](https://github.com/silverbulleters/vanessa-behavior/files/102954/default.zip)

**Comment by Pr-Mex** [comment]
Прошу прощения, что давно не отвечал.
Я, помнится, правил код, где были вылеты на таблицах без строк.
Можете проверить на текущей версии?

**Comment by Pr-Mex** [comment]
Закрываю.
