### ISSUE TITLE
Слияние параметров в один при создании снипетов

### ISSUE THREAD

**Issue by KatyaLR** [silverbulleters/vanessa-behavior#237]
Есть сценарий такого вида: 

[new 1.txt](https://github.com/silverbulleters/vanessa-behavior/files/103255/new.1.txt)

когда перегенирирую epf и создаются процедуры, то все параметры сливаются в один без разделения запятыми:

&НаКлиенте
//И к заказу связанному с реализацией товаров и услуг <Номер> от <ДатаДокумента>  присоединен файл <ИмяФайла> только один
//@КЗаказуСвязанномуСРеализациейТоваровИУслугОтПрисоединенФайлТолькоОдин(НомерДатаДокументаИмяФайла)
Процедура КЗаказуСвязанномуСРеализациейТоваровИУслугОтПрисоединенФайлТолькоОдин(НомерДатаДокументаИмяФайла) Экспорт

**Comment by 1cto** [comment]
Поддержу. Видел своими глазами, потом приходится руками разбивать на части.

**Comment by Pr-Mex** [comment]
Ошибку воспроизвел. Буду смотреть.

**Comment by Pr-Mex** [comment]
Решено. Проверьте.

**Comment by Pr-Mex** [comment]
Закрываю.
