### ISSUE TITLE
Лицензия и использование продукта. Что означает различие с официальной лицензией BSD ?

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#239]
В продукте использована лицензия BSD, правильно я понимаю?

Но почему-то есть разница в тексте.
Например, в BSD 3 пункт написан так:
>Ни **название "Организации"**, ни имена ее сотрудников не могут быть использованы в качестве поддержки или продвижения продуктов, основанных на этом ПО без предварительного письменного разрешения.

А в текущей лицензии продукта 3 пункта написан так:
>Ни **название продукта "Vanessa Behavior"**, ни имена его разработчиков не могут быть использованы
в качестве поддержки или продвижения продуктов, основанных на этом ПО без предварительного письменного разрешения.

Видно, что в BSD используется `название "Организации"`, а в текущей лицензии используется `название продукта "Vanessa Behavior"`
Разница довольно серьезная.

Что означает различие с официальной лицензией BSD ?

@allustin @Pr-Mex что скажете?

**Comment by allustin** [comment]
как видно из файла используется BSD v3

в BSD v3 Organization не является юридическим лицом в русском понимании -  юридическое лицо это Owner.

Поэтому лицензия НЕ изменена - у заполнена правильно, как и положено.
наш юрист это подтвердил.

Консалтингом заниматься не хочу

**Comment by artbear** [comment]
>как видно из файла используется BSD v3

Читаем официальный текст http://opensource.org/licenses/BSD-3-Clause
>3. Neither **the name of the copyright holder** nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Все-таки большая разница с текущей лицензией 
>* Neither **the name of "Vanessa Behavior"** nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

Почему именно используете название продукта, а не владельца продукта?

**Comment by artbear** [comment]
>как видно из файла используется BSD v3

Читаем официальный текст http://opensource.org/licenses/BSD-3-Clause
>3. Neither **the name of the copyright holder** nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Все-таки большая разница с текущей лицензией 
>* Neither **the name of "Vanessa Behavior"** nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

@allustin  Почему именно используете название продукта, а не владельца продукта?

**Comment by artbear** [comment]
@allustin Проблема в использовании имени продукта в лицензии вот в каком сценарии:
один из контрибьюторов или простой пользователь решает развивать свою версию продукта, делает собственный форк и работает только в нем. Именно свою доработку он и распространяет.

Если использовать `the name of the copyright holder`, ИМХО проблемы нет.

Правильно ли я понимаю, что 
+ сейчас согласно текущему тексту лицензии он не имеет права использовать имя продукта для обозначения иерархии разработки (vb -> его продукт) ? 
+ А если он не укажет иерархию разработки, то он нарушит пункт лицензии о правах (пп1 и 2) ?
+ Согласовывать использование имени продукта придется со всеми контрибьюторами (!), верно?

Правильно ли я понимаю, что сейчас запрещено распространение и разработка в соседнем форке ? :(
Т..е ни один из контрибьюторов не имеет права сделать собственный форк и работать только в нем?

Правильно ли я понимаю, что это создает трудности для контрибьюторов :( ?

@allustin @Pr-Mex  Хотелось бы получить пояснения.

**Comment by allustin** [comment]
не ту кнопку нажал.

**Comment by allustin** [comment]
@artbear вынужден спросить - для чего пояснения ?

**Comment by artbear** [comment]
@allustin я хочу понять, в каком виде разрешено участие в проекте и развитие проекта.
Это же опен-сорс.

Например. 
Я или другой пользователь хотим некую фичу, которую другие считают ненужной, не подходящей для проекта. и мы расходимся во мнениях.
я реализовываю эту фичу у себя, в основной продукт она не попадает соответственно.

Сейчас я не вижу возможности, каким образом кто-то из контрибьюторов может использовать свой форк, не нарушая лицензии.

Хочется понять, как я могу юзать/дорабатывать продукт.

**Comment by allustin** [comment]
@artbear нам с тобой лучше это обсуждать НЕ публично - я предлагаю встретиться в кафе и договориться, чтобы наконец-то разрулить конфликт

**Comment by artbear** [comment]
@allustin Я всегда против конфликтов и за кафе :)
В выходные удобно.

Но вопрос и ответы все-таки интересны именно публично, т.к. указанный мной сценарий для опенсорса типичен.
У других контрибьюторов наверняка возникнут те же вопросы :)

**Comment by allustin** [comment]
@artbear на выходных - а потом зафиксируем результаты публично

**Comment by artbear** [comment]
@allustin Принимается

**Comment by g-ones** [comment]
Я так понимаю @artbear решил встроить vanessa-behavior в xUnit v4 а это оказалось запрещено без согласования с разработчиками.

@allustin опасное это дело - если мы встроимся в xUnit, то тогда нас в сообществе cucumber пошлют. 

Может буть xUnit развивается отдельно и Vanessa Stack отдельно - а нам сосредоточится на развитии функционала всего стэка.

**Comment by artbear** [comment]
@g-ones 
>@artbear решил встроить vanessa-behavior в xUnit v4 а это оказалось запрещено без согласования с разработчиками.

Торопишься :(
откуда такой вывод?

**Comment by allustin** [comment]
@g-ones согласен с Артуром - ты торопишься с гипотезами.

**Comment by alehinsasha** [comment]
Использование opensource - это путь Джека Воробья, а не Билла Гейтса! @artbear странно что ты до сих пор этого не понял и не успокоишься)

**Comment by artbear** [comment]
@alehinsasha Это ты к чему? расшифруй про Джека и Билла

**Comment by Hissin** [comment]
@artbear  - знаешь, как человек со стороны, я соглашусь с ребятами. И могу обосновать со своей точки зрения
.
Проекты/продукты развиваются уже не первый месяц, но какого-то внимания до определенных "телодвижений" команды в "мире" с Вашей (твоей?) стороны не было. И первые посты и шаги были в виде "нападок" и каких-то "претензий" к команде. У нас есть люди, которые пришли из-вне, но они пришли совсем по-другому.

И зачем, если xUnit развивается и выполняет все требования и пожелания, необходимо стало погружаться в наши проекты/продукты? В том числе можно же дальше развивать xUnit, и на это тратить время и возможности. Ничего сверхъестественного в наших подходах нет, чего было бы неизвестно в мире.

**Comment by artbear** [comment]
@Hissin 
>Проекты/продукты развиваются уже не первый месяц, но какого-то внимания до определенных "телодвижений" команды в "мире" с Вашей (твоей?) стороны не было. И первые посты и шаги были в виде "нападок" и каких-то "претензий" к команде

человек со стороны, вы не хамите! 
Историю продукта нужно знать. Я с Вас смеюсь (с)

Например, посмотрите [issue продукта под моим авторством]( https://github.com/silverbulleters/vanessa-behavior/issues?utf8=%E2%9C%93&q=+author%3Aartbear+sort%3Acreated-asc+)

Обратите внимание на их номера.
Первые 10 issue продукта я создал.
Из первых 23 issue продукта 21 за моим авторством :)

Можете у @allustin уточнить, как мы с ним и @wizi4d начинали обсуждать bdd и реализацию bdd в 1С. Можешь спросить, на чьих проектах начали появляться первые фичи на языке Gherkin.
Можете у @Pr-Mex узнать, на чьих фичах начинал тестироваться продукт и кто выступал в роли первого бета-тестера.

PS Вынужден это написать, не сочтите за бахвальство!

**Comment by allustin** [comment]
@artbear ты ничего не перепутал ? ты сейчас понял что написал ?

Артур - ты лучше потри это комментарий сам. Иначе дело кончится звиздецом.

**Comment by allustin** [comment]
и впредь пожалуйста указывайте с чего все начиналось - https://bitbucket.org/silverbulleters/cuke4onec/commits/all?page=2

и когда **я создавал первую версию** - никого рядом не было.

**Comment by allustin** [comment]
@artbear и Катя @Hissin историю продукта прекрасно знает, она с @Pr-Mex и мной работает с 2014 ода.

Ну блин... Ну расстроил...

**Comment by artbear** [comment]
@allustin А что не так? я ни в каком случае не присваиваю себе авторство идей, а говорю только о том, что я принимал все-таки некоторое участие в продукте.
Что в моих словах неправда?

Про cuke4onec я ничего не писал.
Я говорю именно о фича-файлах gherkin и продукте под названием vanessa-behavior, который появился на гитхабе.

**Comment by Hissin** [comment]
@allustin - а @artbear не знал что-ли про cuke4onec???

**Comment by artbear** [comment]
@allustin Извини, если я тебя задел.

Думаешь, меня порадовал ничем не оправданный наезд @Hissin ?
Тем более, что, оказывается, она знает всю историю.
Тогда двойное хамство!

**Comment by allustin** [comment]
@Hissin знал конечно - я его Всей команде xDdrivenDevelopment показал.  

@artbear потри комментарий - я тебя прошу... от греха.

**Comment by allustin** [comment]
@all - задача будет закрыта в восресенье - коменты прикрыл.

**Comment by allustin** [comment]
Разобрались в чем причина

На GitHub используется вот такое

![image](https://cloud.githubusercontent.com/assets/55323/12713002/3838bb78-c8dd-11e5-8ec7-d91a4805c53b.png)

на OpenSource 

![image](https://cloud.githubusercontent.com/assets/55323/12713024/4cff13ae-c8dd-11e5-883a-a91c975e84d7.png)

То есть основная непонятка это **promote product** и что это такое.

 а это просто использование в маркетинговых и рекламных компаниях при продвижении своего продукта базирующегося на этом.

Я сейчас добавлю разъяснение в CONTRIBUTIONS.md

**Comment by allustin** [comment]
офтопик - очень интересно, что когда закрыто общение github не может приатачить комииты к задаче

https://github.com/silverbulleters/vanessa-behavior/commit/e89c1f01beb824dd9ee4fede8c88ecf98ea922c4

https://github.com/silverbulleters/vanessa-behavior/commit/897258ab5c14c5b8000857bb034543858d903f07
