### ISSUE TITLE
Нужен детальный итог по выполненным, пропущенным, упавшим сценариям и шагам

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#24]
Нужен детальный итог по выполненным, пропущенным, упавшим сценариям и шагам
В виде дерева.

* Сценарий	Упал	
	* Шаг1	Выполнился
	* Шаг2	Упал
	* Шаг3	Не выполнялся
* Сценарий 2	Упал	
	* Шаг21	Пропущен
	* Шаг22	Не выполнялся

**Comment by Pr-Mex** [comment]
Я думаю сначала сделать #17. А там уже будет понятнее.

**Comment by allustin** [comment]
![2015-07-05 12-29-59](https://cloud.githubusercontent.com/assets/55323/8511117/efbff760-2311-11e5-876e-81e30c43fed3.png)

Для совместимости с Eclipse необходим вот такой вариант

**Comment by Pr-Mex** [comment]
Результат в виде дерева уже сейчас примерно такой. Иконки другие. Секции сводных результатов пока нет.

**Comment by allustin** [comment]
@Pr-Mex Секция сводных результатов относится к полной проверки и закрывается отчетом Allure

Поэтому - пока непонятен сценарий использования в Behavior.
Возможно понадобится в будущем для Eclipse

Закрой задачу с тэгом - подумать потом над сценарием использования

![image](https://cloud.githubusercontent.com/assets/55323/12034834/5fb70b60-ae47-11e5-96be-dd125f4df058.png)
