### ISSUE TITLE
Отсутствие в библиотеке форм шага по работе с типом "ТестируемаяДекорацияФормы"

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#240]
В результате не могу записать (и соответственно воспроизвести) открытие типового отчёта:
![image](https://cloud.githubusercontent.com/assets/15178930/12611141/e60ae976-c4f3-11e5-939c-434e860b9760.png)

Просьба расширить сценарии в https://github.com/silverbulleters/vanessa-behavior/blob/develop/features/Core/ExpectedForms.feature для использования этого типа.

**Comment by Pr-Mex** [comment]
Решено.Проверьте.

**Comment by Pr-Mex** [comment]
Закрываю.
