### ISSUE TITLE
При проверке табличного документа формы необходимо добавить использование * [$5]

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#244]
Как пользователь VB я хочу проверять табличный документ формы с пропуском параметров

Сценарий: Использование "*" в проверке
Когда я использую проверку табличного документа формы через процедуру
	```И     табличный документ формы с именем "РеквизитТабличныйДокумент" стал равен:```
Тогда я хочу указывать в параметрах табличного документа символ "*" для исключения из контроля значения полей.

Например:

И     табличный документ формы с именем "РеквизитТабличныйДокумент" стал равен:
| 'Наименование' | 'Версия' |
| 'Тест'         | '*'                          |

В данном случае проигнорируется проверка на равенство поля "Версия"

**Comment by nixel2007** [comment]
Зачем вообще тогда проверять эту колонку?

**Comment by g-ones** [comment]
тогда это другая проверка

```
И табличный документ формы с именем "РеквизитТабличныйДокумент" стал ПОДОБЕН: 
```

**Comment by g-ones** [comment]
и в документацию на библиотечные шаги описание управляющих символов проверки подобия

**Comment by g-ones** [comment]
@Hissin а можно тебе просьбу - запость bounty на эту задачу 5$, я попробую решить и посмотреть как мне деньги упадут. Я тебе верну при встрече

**Comment by Hissin** [comment]
@allustin Ок. сейчас попробую. 
@nixel2007 Есть поля, которые меняются, например дата редактирования. Тут при сравнении сложно отловить. его надо будет проверять отдельно. Поэтому изначально проверяем что основная таблица заполнилась, а время проверяю отдельно.

**Comment by g-ones** [comment]
@Hissin ща Леха прибежит - ты его позвала ;-)

**Comment by Hissin** [comment]
@g-ones уже рука по привычке:) извиняюсь Андрюш.

**Comment by Hissin** [comment]
@g-ones денег кинула. принимай. только задачу сделай, а то ни Лёне ни Лёше некогда :( а прям печаль с объемом проекта

**Comment by g-ones** [comment]
@Hissin взялся сделаю... за 5 баксов то.

**Comment by Hissin** [comment]
@g-ones сильно то не мучайся. думаю несколько дней живет это :) Есть пока чем заняться

**Comment by Pr-Mex** [comment]
@g-ones 
Сделал?

**Comment by g-ones** [comment]
@Pr-Mex да... только надо PayPall акаунт создать

**Comment by Pr-Mex** [comment]
Решил проблему.
Не заработка ради.
"Неожиданно" понадобилось.

**Comment by Pr-Mex** [comment]
Закрываю.
