### ISSUE TITLE
При генерации epf дублируются шаги, если в feature использовался знак "-" и разные по регистру буквы после

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-behavior#245]
Сценарий:
Когда я в тексте feature-файла в шаге использую знак "-" и разные по регистру буквы после знака "-"
Тогда при генерации EPF такой шаг дублируется.

Пример: 
**feature**

Сценарий: Подстановка в текст 1
 	Когда Я перехожу к тексту feature-**Ф**айла в поле "Текст"

Сценарий: Подстановка в текст 2
 	Когда Я перехожу к тексту feature-**ф**айла в поле "Текст"

**erf**

ДобавитьШагВМассивТестов(ВсеТесты,"ЯПерехожуКТекстуFeature_**ф**айлаВПоле(Парам01)","ЯПерехожуКТекстуFeature_файлаВПоле","Когда Я перехожу к тексту feature-файла в поле ""ТекстФичи""");

ДобавитьШагВМассивТестов(ВсеТесты,"ЯПерехожуКТекстуFeature_**Ф**айлаВПоле(Парам01)","ЯПерехожуКТекстуFeature_ФайлаВПоле","Когда Я перехожу к тексту feature-Файла в поле ""ТекстФичи""");

**Итог**

Ругается на дублирование процедуры

**Comment by Pr-Mex** [comment]
Решено. Можно проверять.
