### ISSUE TITLE
Ошибка с контекстом при использовании обработки оповещения

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#252]
https://github.com/silverbulleters/vanessa-stack-commons/commit/a1a946171930f256f3917796fdf546c2775bb9c3

[2016-02-12_23-16-29.mp4](https://files.zenhub.io/56bf7341f7471cd9688f3b4d)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by Pr-Mex** [comment]
Буду смотреть.

**Comment by Pr-Mex** [comment]
Разобрался.
1С держит в памяти контекст нескольких открытых форм.
Оповещение приходит в каждую из них.
Это воспроизводится только при запрете синхронных вызовов, т.к. чуть другая реализация обхода каталогов.
Буду чинить.

**Comment by Pr-Mex** [comment]
Решено. Можно проверять.

**Comment by Pr-Mex** [comment]
Закрываю.
