### ISSUE TITLE
Падение платформы при проверке равенства табличных документов

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#253]
Если в шаге использовать конструкцию:

Ванесса.ПроверитьРавенствоТабличныхДокументовТолькоПоЗначениям(Отчет, ЭталонныйОтчет);

то, в случае, если она закончится неуспешно, то платформы падает в процедуре ВыполнитьШаг()

Мы что-то не так делаем или это какая-то ошибка? Есть ли способ обхода?

Платформа: 8.3.7.1845
Видео прилагаю: [Видео](https://www.dropbox.com/s/o36wlfxikuhfxj1/%D0%9E%D1%88%D0%B8%D0%B1%D0%BA%D0%B0.rar?dl=0)

**Comment by Pr-Mex** [comment]
Буду смотреть.

**Comment by Pr-Mex** [comment]
Посмотрел.
Мне надо DT на котором это можно воспроизвести и фичу.

**Comment by viskvortsov** [comment]
https://www.dropbox.com/s/lt9zcbsioxjwpck/1Cv8.rar?dl=0

**Comment by Pr-Mex** [comment]
Решено.
Проверьте.

**Comment by Pr-Mex** [comment]
Закрываю.
