### ISSUE TITLE
Запуск только одного подсценария из структуры сценария

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#254]
Как пользователь VB я хочу запускать один вариант сценария из структуры сценария

Сценарий: Запуск одного сценария из структуры сценария
Дано загружена фича со структурой сценария и 4 вариантами сценария
Когда я нажимаю "Выполнить сценарий" на подсценарии
Тогда выполняется только один подсценарий

**Comment by Pr-Mex** [comment]
Да. Пока этого нет.

**Comment by Pr-Mex** [comment]
Решено в рамках #462. Закрываю.
