### ISSUE TITLE
Нужно в процедурах ПередНачаломСценария() и ПослеОкончанияСценария() знать каким сценарием они вызваны

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#261]

**Comment by Pr-Mex** [comment]
Сделано.
Можно использовать примерно так:

	СостояниеVanessaBehvior = Ванесса.ПолучитьСостояниеVanessaBehvior();
	ТекущийСценарий         = СостояниеVanessaBehvior.ТекущийСценарий;
	ТекущийШаг              = СостояниеVanessaBehvior.ТекущийШаг;
	
	Ванесса.ПроверитьРавенство(ТекущийСценарий.Имя,"Тестовая фича, проверяющая получение состояния");
	Ванесса.ПроверитьРавенство(ТекущийШаг.Имя,"Когда я получаю состояние Vanessa Behvior");

**Comment by Pr-Mex** [comment]
Закрываю.
