### ISSUE TITLE
Не генерируется дополнительный шаг записанного сценария

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#262]
Контекст:
  Дано: vanessa-behavior 0.905
  И  платформа 8.3.6.2421
  и конфигурация УТ 11.2.2.116
  и есть записанный сценарий с одним добавленным ручным шагом
![image](https://cloud.githubusercontent.com/assets/15178930/13577884/7c249772-e49d-11e5-923c-9eea1e7361d7.png)

Сценарий: генерация обработки с нереализованным шагом сценария
  Когда: я перехожу на закладку "Генератор EPF"
             и нажимаю кнопку "Создать шаблоны обработок"
  Тогда: получаю вот такой лог
"07.03.2016 20:53:50 Запускаю генерацию epf.
07.03.2016 20:53:51 Ищу снипеты в каталоге C:\1C_Bases\test\
07.03.2016 20:53:51 Ищу снипеты в каталоге c:\1C_Bases\BDD\vanessa-behavior\features\Libraries\
07.03.2016 20:53:51 Работаю по фиче: C:\1C_Bases\test\123.feature
07.03.2016 20:53:51 ОтносительныйКаталогФичи=C:\1C_Bases\test\
07.03.2016 20:53:51 Буду записывать C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF\und/70e297e0-e8a2-43bf-8be1-62e408f610a1.0_123.txt
07.03.2016 20:53:51 Записал C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF\und/70e297e0-e8a2-43bf-8be1-62e408f610a1.0_123.txt
07.03.2016 20:53:51 Переименовал в C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF\und/70e297e0-e8a2-43bf-8be1-62e408f610a1.0
07.03.2016 20:53:51 Создаю C:\1C_Bases\test\step_definitions\123.epf
07.03.2016 20:53:51 Создаю из исходников C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF 
 Временный epf C:\Users\oleynik.dv\AppData\Local\Temp\v8_32E0_9.epf
07.03.2016 20:53:51 СтрокаСборкиEpf=python C:\1C_Bases\BDD\vanessa-behavior\vendor/precommit1c/pyv8unpack.py --compile "C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF" "C:\Users\oleynik.dv\AppData\Local\Temp\v8_32E0_9.epf"
07.03.2016 20:53:51 Ошибка создания файла C:\1C_Bases\test\step_definitions\123.epf!!!
07.03.2016 20:53:51 Создание epf по фичам закончено."
и не получаю обработки с прототипом шага сценария

**Comment by 1cto** [comment]
Текст фичи такой (он может быть любой в данном случае):

# encoding: utf-8
# language: ru

Функционал: <описание фичи>

Как <Роль>
Я хочу <описание функционала> 
Чтобы <бизнес-эффект> 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий


Сценарий: <описание сценария> 

	Когда В панели разделов я выбираю "Продажи"
	Тогда открылось окно "Начальная страница"
	И     В панели функций я выбираю "Отчеты по продажам"
	Тогда открылось окно "Отчеты по продажам"
	И     В открытой форме я нажимаю на гиперссылку с заголовком "Валовая прибыль предприятия"
	Тогда открылось окно "Валовая прибыль предприятия"
	И     В открытой форме я нажимаю на кнопку с заголовком "Сформировать"
	И     Я закрываю окно с заголовком "Валовая прибыль предприятия"
	И 	  теперь я хочу всё проверить

**Comment by Pr-Mex** [comment]
У меня генерация прошла без ошибок.
Я добавил более подробный лог сборки EPF.
Сделай ещё раз.

**Comment by 1cto** [comment]
14.03.2016 19:39:03 Работаю по фиче: C:\1C_Bases\test\123.feature
14.03.2016 19:39:03 ОтносительныйКаталогФичи=C:\1C_Bases\test\
14.03.2016 19:39:03 Буду записывать C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF\und/70e297e0-e8a2-43bf-8be1-62e408f610a1.0_123.txt
14.03.2016 19:39:03 Записал C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF\und/70e297e0-e8a2-43bf-8be1-62e408f610a1.0_123.txt
14.03.2016 19:39:03 Переименовал в C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF\und/70e297e0-e8a2-43bf-8be1-62e408f610a1.0
14.03.2016 19:39:03 Создаю C:\1C_Bases\test\step_definitions\123.epf
14.03.2016 19:39:03 Создаю из исходников C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF 
 Временный epf C:\Users\oleynik.dv\AppData\Local\Temp\v8_F82C_6.epf
14.03.2016 19:39:03 СтрокаСборкиEpf=python C:\1C_Bases\BDD\vanessa-behavior\vendor/precommit1c/pyv8unpack.py --compile "C:\1C_Bases\BDD\vanessa-behavior\lib/TemplateEpfUF" "C:\Users\oleynik.dv\AppData\Local\Temp\v8_F82C_6.epf" > C:\Users\oleynik.dv\AppData\Local\Temp\v8_F82C_7.txt 2>&1
14.03.2016 19:39:04 Лог командны сборки EPF:
Traceback (most recent call last):
  File "C:\1C_Bases\BDD\vanessa-behavior\vendor/precommit1c/pyv8unpack.py", line 385, in <module>
    sys.exit(main())
  File "C:\1C_Bases\BDD\vanessa-behavior\vendor/precommit1c/pyv8unpack.py", line 366, in main
    compilefromsource(args.inputPath, args.output, args.type)
  File "C:\1C_Bases\BDD\vanessa-behavior\vendor/precommit1c/pyv8unpack.py", line 316, in compilefromsource
    shutil.copy(os.path.normpath(old_path), new_path)
  File "c:\Python33\lib\shutil.py", line 227, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "c:\Python33\lib\shutil.py", line 109, in copyfile
    with open(src, 'rb') as fsrc:
OSError: [Errno 22] Invalid argument: 'C:\\1C_Bases\\BDD\\vanessa-behavior\\lib\\TemplateEpfUF\\und\\70e297e0-e8a2-43bf-8be1-62e408f610a1\n70e297e0-e8a2-43bf-8be1-62e408f610a1.0'
14.03.2016 19:39:04 Ошибка создания файла C:\1C_Bases\test\step_definitions\123.epf!!!
14.03.2016 19:39:04 Создание epf по фичам закончено.

**Comment by Pr-Mex** [comment]
Дай скриншот каталога
C:\1C_Bases\BDD\vanessa-behavior\lib\TemplateEpfUF\und

**Comment by 1cto** [comment]
Лови:
![image](https://cloud.githubusercontent.com/assets/15178930/13769490/bf042c4c-ea88-11e5-8241-b0bed74ce0b1.png)

**Comment by Pr-Mex** [comment]
Вроде всё на месте.
Предлагаю тогда подключится через тимвьюер и проверить онлайн.

**Comment by Pr-Mex** [comment]
Разобрались. Была проблема с правами на каталог. Закрываю.
