### ISSUE TITLE
Не получается средствами библиотеки интерфейса выбрать период в отчёте

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#263]
Контекст:
Дано: vanessa-behavior 0.905
И платформа 8.3.6.2421
и конфигурация УТ 11.2.2.116

![image](https://cloud.githubusercontent.com/assets/15178930/13578199/2bb2ac3c-e49f-11e5-9a91-e5fd4995e6e3.png)

записывается вот такой фрагмент сценария:
	И     В форме 'Настройки отчета "Ведомость по товарам на складах"' в таблице "Отборы" я перехожу к строке:
	| 'Заголовок' |
	| 'Период'        |
	И     В форме 'Настройки отчета "Ведомость по товарам на складах"' в ТЧ "Отборы" я выбираю текущую строку
	Тогда открылось окно "Выберите период"

Но окно не открывается, так обработчики видимо стоят только на полях "Условие" и "Значение", а они при переходе на строку неактивны.

**Comment by Pr-Mex** [comment]
Внёс изменения.
Проверь на новой версии.

**Comment by 1cto** [comment]
Не помогло. Вот скринкаст, чё делаю: http://screencast.com/t/wKpni0XWr

**Comment by Pr-Mex** [comment]
Решено.
Проблема была в активной колонке.
Надо перезаписать действия или добавить шаг
**И     В открытой форме в ТЧ "Отборы" я активизирую поле "Условие"**
Проверь.

**Comment by 1cto** [comment]
Закрываю, работает.
