### ISSUE TITLE
Не верна обработка gotoRow

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#265]
[dt, xml](https://drive.google.com/file/d/0By-W2XsFwhjxRmRTclB2ZTRCZmM/view?usp=sharing)

**Comment by Pr-Mex** [comment]
Решено. Оказалось что проблема была с поиском формы по имени, а ошибка при ненахождении формы была неинформативной.
Т.е. при создании элемента справочника форма называется "Справочник1 (создание)", а после изменения любого поля она уже называется "Справочник1 (создание)*", т.е. добавляется ещё один символ и поиск по старому имени не проходит.
Я сделал поиск формы также как в других шагах библиотеки.
Закрываю.
