### ISSUE TITLE
Шторка

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#266]
[dt, feature, avi](https://drive.google.com/file/d/0By-W2XsFwhjxRWpwajhGaGJCQ1E/view?usp=sharing)

**Comment by Pr-Mex** [comment]
Проблема проявляется если включена "Панель функций текущего раздела".
Чтобы это победить надо выключить эту панель, как показано на рисунке.
Было
![image](https://cloud.githubusercontent.com/assets/8627416/13724845/61bac578-e8a3-11e5-965f-0e4a25f403b3.png)

Стало
![image](https://cloud.githubusercontent.com/assets/8627416/13724847/6a269f02-e8a3-11e5-984f-9e5658eaca81.png)

**Comment by Pr-Mex** [comment]
Закрываю.
