### ISSUE TITLE
Проблемы с запуском TestClient (TestClient НЕ подключен.)

### ISSUE THREAD

**Issue by error2221** [silverbulleters/vanessa-behavior#267]
По совету Александра создал проблему тут, продублировав ее с форума

> 
> Сегодня добился нормальной сборки. 
> Но тем не менее считаю ее несовсем честной. 
> фичу для проверки документа взял чужую, свою не смог создать вот по какой причине:
> 
> Открываю vanessa-behavior, вкладка "Работа с UI", пытаюсь подсоединиться к TestClient и вылетает ошибка 
> 20.03.2016 0:52:39 Делаю перезапуск TESTCLIENT.
> 20.03.2016 0:52:44 TestClient НЕ подключен.
> {Форма.УправляемаяФорма.Форма(5956)}: Ошибка при вызове метода контекста (НачатьЗаписьЖурналаДействийПользователя): Ошибка сетевого взаимодействия при вызове.: Ошибка сетевого взаимодействия при вызове.
> 
> Решал задачу Оперативного учета. Леонид сказал не тратить время и это ошибка сети бука. Но тем не менее, хотелось бы решить проблему.
> 
> Пробовал: 
> - выключение брандмауэров
> - выключение антивиря (windows defender)
> 
> 1С стартую от админа. 
> При нажатии на кнопку "Начать запись поведения" открывается 1С, работает 2 секунды, закрывается, открывается заново, но в предыдущем окне ошибки, которые я описал выше.

ВНЕ ТЕМЫ: 
Пробовали открывать Запустить для записи журнала действий, эта функция работает исправно, из чего был сделан вывод, что проблема в vanessa-behavior

**Comment by Pr-Mex** [comment]
Попробуйте подключить TestClient как описано в этой статье. По результату станет понятно где именно проблема.
http://xn----1-bedvffifm4g.xn--p1ai/news/%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-1%D1%81-8-3/

**Comment by Pr-Mex** [comment]
Получилось проверить?

**Comment by nixel2007** [comment]
@Pr-Mex 
на домашней машине запустил подключение кодом
```bsl
// Подключимся к тестируемому приложению 
ТестируемоеПриложение = Новый ТестируемоеПриложение(); 
// Пытаемся подключаться не более одной минуты 
ВремяОкончанияОжидания = ТекущаяДата() + 60; 
Подключен = Ложь; 
Пока Не ТекущаяДата() >= ВремяОкончанияОжидания Цикл 
	Попытка 
		ТестируемоеПриложение.УстановитьСоединение(); 
		Подключен = Истина; 
		Прервать; 
	Исключение 
	Сообщить(ОписаниеОшибки());
	КонецПопытки; 
КонецЦикла; 

Если Не Подключен Тогда 
	// Завершаем работу теста 
	ТестируемоеПриложение = Неопределено; 
	Сообщить("Не удалось установить соединение!"); 
КонецЕсли;
```

В логах:
```
{(8)}: Ошибка при вызове метода контекста (УстановитьСоединение): Ошибка подключения к клиенту тестирования. Возможно, клиент не запущен или неверно указаны параметры подключения.: Ошибка подключения к клиенту тестирования. Возможно, клиент не запущен или неверно указаны параметры подключения.
```

**Comment by Pr-Mex** [comment]
Это означает, что проблема на стороне компа.

**Comment by Pr-Mex** [comment]
Закрываю.

**Comment by nixel2007** [comment]
> грозит мне тотальная переустановка... и VB не работает, и VSC на днях сломался...

Конечно, хорошо было бы все же разобраться, в чем причина такого поведения.
Но это вопрос... не относящийся непосредственно к VB, скажем так :)

**Comment by Pr-Mex** [comment]
Он совсем к VB не относится.
Это проблема коннекта TestManager и TestClient.
Пока проблема в 100% случаев воспроизвелась и без VB.

**Comment by Pr-Mex** [comment]
У меня такой проблемы не возникало.
@allustin сталкивался с таким.
Может он что расскажет.

**Comment by JohnyDeath** [comment]
У меня было подобное. Из-за чего, собственно, я отложил знакомство с VB до появления свободного времени в плане анализа ситуации.

**Comment by Pr-Mex** [comment]
Я подозреваю в проблеме антивирусы, брандмауеры, фаерволы. 
Ещё бывает окно в windows всплывает, что клиент 1с пытается получить доступ в сеть. Некоторые нажимают на запрет доступа.

**Comment by viskvortsov** [comment]
В нашем случае оказалось, что порт, через который общается менеджер с клиентом (1538), оказался занят svchost-ом. Указали в коде -TPort 1581 и все заработало.
Можно ли в настройки запуска testclient-а в VB добавить порт запуска?
