### ISSUE TITLE
Проблема со скриптами контрибутора

### ISSUE THREAD

**Issue by kseniyaloza** [silverbulleters/vanessa-behavior#268]
![image](https://cloud.githubusercontent.com/assets/16815452/13904962/f602bcac-eec2-11e5-80dd-37853248746c.png)

**Comment by alehinsasha** [comment]
У многих на wshop повторилась ошибка.

**Comment by Pr-Mex** [comment]
Это скорее всего остались процессы 1С от предыдущего запуска скриптов, и они блокируют файл.
