### ISSUE TITLE
Нужны сниппеты по сравнению текстовых значений в библиотеке интерфейса

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#279]
Например, есть сниппет:
И   элемент формы с именем "ИмяРеквизита" стал равен "Значение"

Не хватает таких сниппетов:
- И   элемент формы с именем "ИмяРеквизита" стал не пустым
- И   элемент формы с именем "ИмяРеквизита" стал не равен "Значение"
- И   элемент формы с именем "ИмяРеквизита" содержит "Значение"

**Comment by Pr-Mex** [comment]
Тогда давай ещё добавим
И элемент формы с именем "ИмяРеквизита" стал пустым

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
