### ISSUE TITLE
Поддержка работы с Контекст на уровне библиотек

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#280]
Есть переменная Контекст, в которой можно сохранять промежуточные значения, в случае, если шаги программируются.

Но если шаги реализуются библиотечными функциями, то передавать некое значение между шагами непонятно как - разве что через таблицу примеров.

Предлагаю реализовать следующий набор библиотечных сниппетов:
- И в открытой форме помещаю в контекст значение поля с заголовком "Заголовок"
- И помещаю в контекст значение  "Значение"
- И в открытой форме значение поля с заголовком "Заголовок2" стало равным значению по ключу "Заголовок" из контекста
- И значение "Значение" равно значению по ключу "Заголовок" из контекста

Возможно у вас будут более оригинальные идеи, как передавать значения между шагами (а ещё лучше между сценариями) без программирования.

**Comment by Pr-Mex** [comment]
Без программирования пока никак.
Да, понял, что такое надо.

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
