### ISSUE TITLE
Шаг в библиотеке интерфейса для выбора значения элемента ТЧ по имени

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#282]
Дано: в библиотеке имеется такой шаг
"И     В открытой форме в ТЧ "СчетаУчетаНоменклатуры" я выбираю значение реквизита с заголовком "Со склада" из формы списка"

Поскольку в ТЧ заголовки колонок могут совпадать, или вообще не заполняться нужен шаг такого рода:
"И     В открытой форме в ТЧ "СчетаУчетаНоменклатуры" я выбираю значение реквизита с именем "СчетаУчетаНоменклатурыСклад" из формы списка"

**Comment by Pr-Mex** [comment]
Решено.
