### ISSUE TITLE
Неправильная группировка шагов с тегом @tree

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#285]
Если в тексте сценария используется тег @tree, и в последнем шаге второго уровня есть работа с таблицами, например:
			И     В форме 'Дополнительные отчеты (Раздел "Закупки")' в таблице "ТаблицаКоманд" я перехожу к строке:
				| 'Представление'        |
				| 'Сводный отчет по заказам в разрезе клиентов' |	
тогда последующий шаг первого уровня остаётся на втором.

**Comment by nixel2007** [comment]
@Pr-Mex похоже на то, что было у меня. Ты вроде исправлял?

**Comment by Pr-Mex** [comment]
Да, это оно. Сейчас исправляю.

**Comment by Pr-Mex** [comment]
Решено.
