### ISSUE TITLE
Путь к feature файлу в шаге

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#286]
Функционал: Путь к feature файлу
   Как разработчик
   Хочу иметь возможность в шаге сценария узнать путь к текущему feature файлу
   Чтобы определять путь к корню репозитория

Сценарий: Функция **ПолучитьСостояниеVanessaBehvior** возвращает в том числе путь к feature файлу
  Допустим в процедуре проверки шага сценария я вызвал функцию **ПолучитьСостояниеVanessaBehvior**
  Когда функция вернула структуру СостояниеVanessaBehvior
  Тогда в структуре СостояниеVanessaBehvior есть свойство **ТекущийFeatureФайл** а в ней есть свойство **ПутьКФайлу**

**Comment by Pr-Mex** [comment]
Готово.

**Comment by Pr-Mex** [comment]
В ПолучитьСостояниеVanessaBehavior появилось
**ТекущаяФича.Имя**
и
**ТекущаяФича.ПолныйПуть**
