### ISSUE TITLE
Запуск проверки поведения в базе, отличной от текущей

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/vanessa-behavior#288]
``` Gherkin
Функциональность: Запуск проверки поведения в базе, отличной от текущей
   Как разработчик
   Я хочу запускать проверку поведения с указанием пути к базе
   Чтобы мне не надо было перезапускать менеджер тестирования при разработке конфигурации
```

Расшифрую.
Обновление конфигурации требует либо отключение предмета отладки либо выгон всех пользователей из базы для нединамического обновления.
Менеджер тестирования в платформе технически позволяет подключать тест-клиенты других ИБ, даже с отличающимися конфигурациями.

Я хочу получить возможность один раз запусть (даже пустую) базу 1с в режиме TESTMANAGER, прописать в конфиге или прямо контексте фичи путь к тест-клиенту.

Таким образом, когда я в конфигураторе тестируемой базы что-то поменяю, мне не понадобится перезапускать test-manager, а просто перезапустить все проверки поведения в VB.

P.S. все это - про ручной режим запуска, когда отлаживается конкретная функциональность.
Для CI это не особо актуально, на сколько я понимаю.

**Comment by Pr-Mex** [comment]
Тебе тогда придётся отказаться от запросов, обращения к метаданным и т.д.
Это не помешает?

**Comment by nixel2007** [comment]
Эх, я запамятовал, что фичи исполняются в контексте тест-менеджера...

Это может помешать на не-"кнопконажимательских" собственных шагах. но все интерфейсные шаги вроде должны отработать без проблем.

**Comment by Pr-Mex** [comment]
Интерфейсные  - да.
Пока оставлю под вопросом.

**Comment by allustin** [comment]
@nixel2007 концепция была следующая

* один проект - один каталог feature файлов - один git репозиторий -> один контура разработки
* если нужно запустить фичи в разных контекстах баз - то должны быть разные git репозитории

на псевдо языке это будет выглядеть так

```
$cat vanessa-bdd-mass-runner.os

_массивПроектов = ПолучитьСписокРепозиториевGIT();


Для каждого репозиторийПроекта из _массивПроектов Цикл
         ЗапуститьПриложение(репозиторийПроекта.АдресКомандногоФайлаЗапуска);
КонецЦикла
```

Потенциально чувствую, что подобный запрос в итоге выродится в типовую конфигурации под названием - "1C:УправлениеQA"

**Comment by nixel2007** [comment]
@allustin понимаю концепцию. имхо, я немного не про то.
Мне не нужно запускать фичи в разных базах. База у меня по-прежнему одна.
Просто хочется, чтобы плеер можно было запускать откуда угодно, даже с базы пустышки - именно для простоты обновления и перезапуска проверки сценариев. Экономия на постоянном перезапуске тест-менеджера.

Однако, если это противоречит концепции, то можно не включать в "библиотечные" фичи, а реализовать сбоку, в рамках моей базы/задачи.

**Comment by pumbaEO** [comment]
Я так понимаю, есть желание сделать что-то подобное как selenium server.
@allustin не всегда такой принцип подойдет, я вот недавно доработал форму списка регламентных заданий в виде расширения, проект у меня один, feature тоже одно, а запускать хочу на БСП 2.1, 2.2, 2.3, ERP 2.1 и УТ 11..., при этом сами фичи и тесты одни для всех.

**Comment by allustin** [comment]
@pumbaEO ух ты - а ты прав. @nixel2007 - я написал просто про концепцию, она не блокирующая - так типа виделось вначале. Учитывая комментарий Жени, теперь я начинаю понимать о чем ты.

@Pr-Mex - а ведь действительно. когда основной проект - это расширение типовой, то тогда контекстов запуска будет много.

То есть библиотечный сценарий по аналогии c #271 должен выглядеть примерно так

```
Когда я запускаю TestClient для информационной системы "строка соединения" с пользователем "Вася" и паролем "йцукен"
```

или это прям настройка в разделе Сервис

Типа "Адреса информационных систем запуска TestClient"

**Comment by pumbaEO** [comment]
При этом мы должны разделять каким-то образом "библиотечный код" который работает хоть на пустой базе и код в шагах, который завязан на какой-нибудь общий модуль, соответственно тогда можно это разделять. 

Конечно хотелось бы иметь еще возможность запустить в контексте тестового клиента  обработку плеера, который подгрузит только шаги контекста конкретной базы и будет принимать входящие команды в виде "invoke шагСозданияДанныхПоМакету", выполнять и потом отдавать ответ "succes" серверу...

**Comment by nixel2007** [comment]
Реализовано.
