### ISSUE TITLE
Подключение полноценного CI/CD

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#29]
Необходимо на CI

* подключить самотестирование и отображение с помощью https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Test+Result+Plugin

* добавить отображение в формате Allure https://github.com/jenkinsci/allure-plugin/blob/master/README.md

* настроить проверку pull request'ов

* автоматический deploy на github

**Comment by allustin** [comment]
https://github.com/silverbulleters/vanessa-behavior/commit/d329be9b30681973d2660e9917084f60a59110c1

**Comment by allustin** [comment]
подключен специальный slave и создан job

http://ci.silverbulleters.org/job/Venessa-Behavior-Develop/

**Comment by Pr-Mex** [comment]
CI подключен. Работа сценариев проверяется в режимах:
8.2.19 обычные формы
8.2.19 управляемые формы
8.3.6 обычные формы
8.3.6 управляемые формы
8.3.6 управляемые формы в режиме отказа от синхронных вызовов
