### ISSUE TITLE
Ошибка сохранения настроек при закрытии в 8.3.8

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-behavior#294]
В 8.3.8 добавили "удачные" проверки вызова серверных вызовов без возможности их отключения при закрытии предприятия. 
Для возможности работы на 8.3.8 платформе необходимо убирать код "СохранитьНастройки" из процедуры "ПриЗакрытии" и делать или отдельную кнопку "Сохранить настройки" или подключать обработчик ожидания.

**Comment by Pr-Mex** [comment]
Да. У 1С есть целая pdf на эту тему, с описанием как надо исправлять.

**Comment by nixel2007** [comment]
@Pr-Mex можно линк?

**Comment by alehinsasha** [comment]
Поделюсь опытом: в простом режиме bddeditor я сохраняю значения сразу после изменения.

**Comment by Pr-Mex** [comment]
@alehinsasha так тоже можно, но лучше учесть рекомендации от 1С
@nixel2007 я не знаю можно ли её свободно распространять, напомни в понедельник, скину

**Comment by pumbaEO** [comment]
Та какая там рекомендация -или обработчик, или сразу или отменять
завершение, сохранять и потом зааершать безусловно.
14 мая 2016 г. 11:09 пользователь "Pautov Leonid" <notifications@github.com>
написал:

**Comment by Pr-Mex** [comment]
Решено.
