### ISSUE TITLE
.\tools\JSON\main.json не найден

### ISSUE THREAD

**Issue by mmoiseev1** [silverbulleters/vanessa-behavior#298]
Функционал: 
   Как Разработчик
   Я хочу тестировать доработки, подключаясь к серверным базам, располагающимся на другой машине используя скрипт run-behavior-check-session.os

Контекст:
  Дано: текущая
  И 1С:Предприятие 8.3 (8.3.7.2008)

Сценарий: Предварительный тест изменений 
	Когда запустил скрит "2 CheckBehavior.cmd"
	И моя база располагается на сервере
	И сервер физически другой компьютер
	Тогда тест не упал с ошибкой .\tools\JSON\main.json не найден

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
