### ISSUE TITLE
Редактор фича-файлов

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#30]
##### Необходим редактор/конструктор фича-файлов
* два режима работы:
 * редактор
   * проверка и подсветка ключевых слов
 * конструктор
   * ключевые слова выбираются, перемещаются и т.д.
* проверка/исправление последовательности ключевых слов
* чтение/сохранение фича-файлов с комментариями
* бизнес требования, они же фича-файлы должны лежать в GIT

**Comment by Pr-Mex** [comment]
Предлагаю убрать строчку
"бизнес требования, они же фича-файлы должны лежать в GIT"
т.к. это не реализовывается средствами vanessa-behavoir.

**Comment by allustin** [comment]
Главное чтобы feature файл был текстовым в формате .feature

**Comment by Pr-Mex** [comment]
Создан новый проект:
https://github.com/silverbulleters/vanessa-bdd-editor
