### ISSUE TITLE
Наименование с символом '|'

### ISSUE THREAD

**Issue by TatyanaChusovlyanova** [silverbulleters/vanessa-behavior#305]
Контекст:
  Дано: 0.948
  И 8.3.6.2100
  и нетиповая конфигурация

Сценарий: ошибка в сравнении номенклатуры
  Допустим: есть номенклатура с наименованием "Товар1 | Категория1 | Бренд1"
  Когда: запускаю сценарий, сгенерированный кнопконажималкой
  Тогда: падает шаг сравнения номенклатуры
![Скриншот](https://cloud.githubusercontent.com/assets/19835595/15926001/6e99dd26-2e5b-11e6-9bf9-ecf799f4e73b.jpg)

**Comment by Pr-Mex** [comment]
Решено. Можно проверять.

**Comment by TatyanaChusovlyanova** [comment]
Спасибо.
