### ISSUE TITLE
Согласовать правила наименований обработок (убрать пробелы из наименований)

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-behavior#310]
В связи с тем, что при выгрузки типовыми средствами 1с неправильно обрабатываются обработки содержащие в своем имени пробелы, предлагаю убрать пробелы из наименований внешних обработок, а так же в правилах репозитория добавить такое ограничение для других участников. 
Обсуждение на партнерке https://partners.v8.1c.ru/forum/topic/1498374

**Comment by Pr-Mex** [comment]
Закрываю?
