### ISSUE TITLE
Поддержка иерархии в секции контекста

### ISSUE THREAD

**Issue by naa4sb** [silverbulleters/vanessa-behavior#319]
При использовании тэга @tree и табуляции в VB не формируется иерархия шагов в секции Контекст

```Gherkin
#encoding: utf-8
#language: ru

@tree

Функционал: Что-нибудь
	Как Кто-то
	Я хочу Что-нибудь
	Чтобы Всё
	
Контекст:
    Дано Это верхняя строка контекста
        Дано А это подчиненная строка контекста
```

Скриншот:
![2016-06-24 12 33 44](https://cloud.githubusercontent.com/assets/19772779/16334145/f5a7cf82-3a07-11e6-96d3-834d0ed1708e.png)

**Comment by Pr-Mex** [comment]
Принято.

**Comment by Pr-Mex** [comment]
Решено. Можно проверять.

**Comment by naa4sb** [comment]
Проверено. Всё исправлено. Спасибо. Закрываю.
