### ISSUE TITLE
Ошибка при перегенерации обработки проверки поведения

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#320]
Допустим я использую виртуальную машину
И 8.3.8.1652
И 0.948
И я написал фичу
И behavior сгенерировал обработку проверки поведения
Когда я отредактировал фичу
И перезагрузил ее в behavior
И запустил перегенерацию обработки проверки поведения
Тогда получаю сообщение об ошибке

![2016-06-24_12-22-11](https://cloud.githubusercontent.com/assets/8247178/16336133/d9724520-3a13-11e6-899c-57f945502ee0.jpg)
![2016-06-24_12-24-27](https://cloud.githubusercontent.com/assets/8247178/16336134/dd9e5c56-3a13-11e6-9b2c-b0eccaac6482.jpg)
![2016-06-24_13-35-01](https://cloud.githubusercontent.com/assets/8247178/16336136/e0777e9e-3a13-11e6-98c8-ac47070e7eca.jpg)

**Comment by Pr-Mex** [comment]
Буду проверять. Пока не понятно.

**Comment by Pr-Mex** [comment]
Надо проверить твою винду на проблемы с русификацией.
Я припоминаю, что проблемы с перегенрацией были, когда не выполнялись команды с русскими буквами в cmd.

**Comment by Pr-Mex** [comment]
Проблема актуальна?

**Comment by alehinsasha** [comment]
Нет.
