### ISSUE TITLE
Ошибка при загрузке пользователей ИБ из макета MXL с помощью снипета "Я создаю fixtures по макету"

### ISSUE THREAD

**Issue by naa4sb** [silverbulleters/vanessa-behavior#323]
Падающий сценарий на пустой базе без пользователей и ролью "ПолныеПрава"
```Gherkin
Функционал: Тест загрузки пользователей из макета 
	Как Разработчик
	Я хочу Иметь возможность загружать пользователей из макета MXL, полученного в плагине xUnit, библиотечным шагом VB
	Чтобы Использовать загруженные данные пользователей в сценариях
	
Контекст:
	
Дано Я создаю fixtures по макету "Пользователи"

Сценарий: Сделать паузу
	Когда Пауза 1
```

При прогоне сценария шаг с созданием фикстур падает с ошибкой. При этом пользователь подгружается. Текст ошибки:

> 28.06.2016 17:15:11 {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(7090)}: Ошибка при вызове метода контекста (СоздатьДанныеПоТабличномуДокументуСервер): Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.: Ошибка преобразования данных XDTO:Запись значения свойства 'ret': форма: Элемент  имя: {http://v8.1c.ru/8.2/managed-application/modules}ret: Ошибка преобразования данных XDTO:Запись значения свойства 'Value':  форма: Элемент  имя: {http://v8.1c.ru/8.1/data/core}Value: Ошибка отображения типов:Отсутствует отображение для типа 'ПользовательИнформационнойБазы'; ИмяФайла=C:\GIT\SB\main\tools\vanessa-behavior\features\Libraries\VB\step_definitions\СозданиеFixturesПоМакетуОбработкиФичи.epf, ИмяПроцедуры=ЯСоздаюFixturesПоМакету

ZIP с фичей и обработка реализации с макетом приложены
[1.zip](https://github.com/silverbulleters/vanessa-behavior/files/337210/1.zip)

**Comment by pumbaEO** [comment]
Клиент-сервер?

**Comment by nixel2007** [comment]
@pumbaEO почему бы и нет? :)
Там просто ПользовательИБ пробрасывается на клиента из процедуры модуля обработки СоздатьОбъект_ПользовательИБ и вверх по стеку.

Методологически что лучше сделать? Возвращать просто его имя? @Pr-Mex ?

**Comment by naa4sb** [comment]
@pumbaEO файловая

**Comment by Pr-Mex** [comment]
@nixel2007 видимо да, лучше имя
