### ISSUE TITLE
Запись отдельных шагов для ПередНачаломСценария() и ПередОкончаниемСценария() в данные для отчета Allure из VB

### ISSUE THREAD

**Issue by naa4sb** [silverbulleters/vanessa-behavior#327]
```Gherkin
Функционал: Запись отдельных шагов для ПередНачаломСценария() и ПередОкончаниемСценария() в данные для отчета Allure из VB
   Как разработчик, использующий VB и отчеты Allure, генерируемые из данных, сохраненных VB при прогоне сценариев
   Я хочу чтобы при прогоне сценариев в данные для отчета Allure записывалось отдельными шагами выполенение процедур ПередНачаломСценария() и ПередОкончаниемСценария()
   Чтобы в отчете Allure отслеживать длительность и факт выполнения этих процедур как отдельных шагов

Контекст:
  Дано: версия инструментария latest version
  И версия 1С любая из поддерживаемых инструментарием

Сценарий: Прогон сценария с записью данных для Allure
  Допустим: Я прогоняю сценарий с помощью VB
  И запись данных для Allure включена
  Когда: В ходе прогона выполняются процедуры ПередНачаломСценария() и ПередОкончаниемСценария()
  Тогда: В данные для Allure записываются отдельные шаги с временными метками начала и окончания выполнения процедуры и статусом выполнения
```

**Comment by Pr-Mex** [comment]
Это интересная/спорная вещь.
Дело в том, что эти процедуры специально отделены от обычных шагов фичи, чтобы их не видел пользователь. Их назначение - делать служебные действия. 
Скажите, что у вас происходит в этих процедурах?

**Comment by naa4sb** [comment]
Очистка данных, например. По поводу "чтобы их не видел пользователь": речь ведь идет в конечном счете о пользователе отчета Allure. И мне кажется, что Allure в случае VB отображает технические данные, пусть и в довольно "попсовой" (: форме. И эти данные с одной стороны наглядны, а с другой - детальны. И на текущий момент в отчете теряется часть детальных данных о ходе выполнения сценария. Согласен, что спорно, в качестве компромисса можно сделать включение данных этих процедур в вывод для Allure опциональным.

**Comment by allustin** [comment]
@naa4sb не пройдем xsd схеме Allure

есть либо TestCase либо Steps

https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd

Служебные ПередСценарием. ПослеСценария, ПередТестом, ПослеТеста в отчеты о тестировании никогда не выводятся. Это методологически верно - чтобы не было повадно делать различные проверки внутри служебных процедур

В указанную фичу я бы добавил

```Контекст Когда созданы данные
и последний Сценарий Очистка тестовых данных
  Тогда данный очищены
```

что будет точно отражать сценарии проверки поведения и штатно попадет в отчет Allure

**Comment by Pr-Mex** [comment]
Ок. Есть ещё ньюанс.
При падении сценария процедура **ПередОкончаниемСценария()** будет выполнена в любом случае. Надо ли её включать в отчет в таком случае?
А насчет добавления **опции**- согласен.

**Comment by allustin** [comment]
@Pr-Mex я не согласен - фактически это уже шаг проверки, а не служебные функции. XSD схема Alure и xUnit отчеты как бы намекают.

А потом придется расчитывать покрытие кода для служебных процедур

**Comment by Pr-Mex** [comment]
@allustin справедливости ради я бы ещё замтил, что в Gherkin есть синтаксис, чтобы указать шаг, который будет выполнятся после каждого сценария. Не помню сейчас как это правильно пишется, но помню, что что-то было такое.

**Comment by allustin** [comment]
@Pr-Mex не помню такого... надо еще раз посмотреть тут http://docs.behat.org/en/latest/guides/1.gherkin.html#thens
и у Аслака

**Comment by Pr-Mex** [comment]
@allustin 
вот, нашел
https://github.com/cucumber/cucumber/wiki/Hooks

**Comment by Pr-Mex** [comment]
В итоге я согласен с @allustin. Служебные процедуры для своего, шаги для своего.
Предлагаю это issue закрыть.

**Comment by naa4sb** [comment]
Не возражаю)
