### ISSUE TITLE
Некорректно отобржается имя шага в отчете Allure, если оно содержит точку

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#334]
Например вот в этой фиче 
https://github.com/silverbulleters/vanessa-behavior/blob/develop/features/Core/TestClient/Issue-148-Video-Make.feature
есть шаг
**И в течении 700 секунд в каталоге заданном в переменной контекста "ПараметрКаталог" появился файл "result.mp4"**

но в отчете Allure всех версий он отображается как
![image](https://cloud.githubusercontent.com/assets/8627416/16540926/2f759d4e-407e-11e6-8786-a9b66ff5b616.png)

Т.е. был взят только текст находящийся справа от символа точки.

**Comment by nixel2007** [comment]
Так вот в чем причина. А я-то думал, что за хитрый шаг у тебя такой :)

**Comment by Pr-Mex** [comment]
@nixel2007 
ага
я думал это глюк аллюра, но оказалось что так и задумано и надо использовать не только тег Name, но ещё и тег Title.

**Comment by Pr-Mex** [comment]
Решено.
