### ISSUE TITLE
Добавить на форму путь, относительно которого будут разрешаться пути с точками

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-behavior#339]
```Gherkin
Функционал: Указание универсальных путей для любых библиотечных шагов
   Как разработчик с разными окружениями, разными путями и т.д.
   Я хочу указывать пути к библиотекам независимыми от полных путей в системе

Контекст:
  Дано: vanessa-behavior версии больше 1 находится по пути d:\git\vanessa-behavior\build\vanessa-behavior.epf
  И  каталог проекта d:\git\myproject\
  и каталог фича файлов d:\git\myproject\features

Сценарий: указание путей до библиотек с учетом макросов
  Допустим: в списке библиотек я указал первым путь ${workspaceRoot}./features/UI
  И в списке библиотек я указал ${instrumentsRoot}./features/Library/UI
  Когда: Происходит чтение фича файлов и происходит поиск библиотечных шагов
  Тогда: для первой записи библиотеки абсолютный путь определяется как "d:\git\myproject\/features/UI"
  И для второй записи библиотеки абсолютный путь определяется как "d:\git\vanessa-behavior\build/features/Library/UI"

```
${workspaceRoot} - выносим на форму настройки с параметров работы, с возможностью указания вручную или же переопределением через файл настроек json. 
${instrumentsRoot} - уже, есть называется "КаталогИнструментов" и определяется путем к самой обработке vanessa-behavior на сервере, тоже необходимо добавить возможность переопределения пути, т.к. загрузка происходит на клиенте. 
Дополнительно в параметры запуска желательно добавить возможность их переопределения, т.е. /C"workspaceRoot;d:\git\myproject\;instrumentsRoot;d:\git\vanessa-behavior\build\" и через переменные окружения vanessa_workspaceRoot и vanessa_instrumentsRoot. 

Тогда можно будет создавать универсальный main.json и выносить vanessa_behavior из каталога проекта.

**Comment by pumbaEO** [comment]
Ограничение библиотеки парсера json заставляют использовать пути $workspaceRoot без фигурных скобок, т.к. если их указать в json файле настроек, тогда неправильно парсится json.

**Comment by Pr-Mex** [comment]
@pumbaEO Дай пример файла json, который не распарсился.

**Comment by pumbaEO** [comment]
https://gist.github.com/pumbaEO/c173adfa80448fe126c5b4ce5199a335#file-gistfile1-txt-L4

**Comment by Pr-Mex** [comment]
Это можно закрывать?

**Comment by pumbaEO** [comment]
Да.
