### ISSUE TITLE
Если через контекстное меню выполняется только один сценарий, то в отчет Allure должен попасть только он.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#34]

**Comment by allustin** [comment]
2 вопроса:

1. зачем в отчете 1 сценарий - Allure он же про сводное качество, максимум я бы добавлял только фильтр по тэгами

типа

"Сформировать Allure только по указанным тэгам"

2. а сейчас все фичи попадают и по моему это даже круто

**Comment by Pr-Mex** [comment]
Там красное окно вылазит, поэтому некрасиво.

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
