### ISSUE TITLE
Исключение отдельного сценария по тэгу

### ISSUE THREAD

**Issue by naa4sb** [silverbulleters/vanessa-behavior#340]
Не знаю, баг это или так и должно быть, но: если в feature-файле указан тэг у отдельного сценария, но не у фичи в целом, а в VB этот тэг есть в списке исключаемых, то исключается вся фича в целом, а не этот отдельный сценарий.

```Gherkin
Функционал: Исключение отдельного сценария
   Как Разработчик
   Я хочу иметь возможность исключать с помощью тэгов выполнение отдельных сценариев фичи

Контекст:
  Дано: версия инструментария last version

Сценарий: Исключение сценария
  Допустим: В feature-файле указан тэг "draft" для отдельного сценария
  И В feature-файле присутствуют сценарии без тэга "draft"
  И В feature-файле не указаны тэги для фичи в целом
  И тэг "draft" присутствует в списке исключаемых тэгов в настройках VB
  Когда: Загружается данная фича
  Тогда: Исключается только сценарий с тэгом "draft"
```

**Comment by Pr-Mex** [comment]
VB на данный момент не поддерживает исключение отдельных сценариев.
Только вся фича целиком.

**Comment by Pr-Mex** [comment]
Был issue, в котором предлагалось использовать теги, чтобы исключать из сценария шаги.

**Comment by Pr-Mex** [comment]
Вот https://github.com/silverbulleters/vanessa-behavior/issues/292

**Comment by Pr-Mex** [comment]
Вот ещё https://github.com/silverbulleters/vanessa-behavior/issues/260

**Comment by Pr-Mex** [comment]
И вот https://github.com/silverbulleters/vanessa-behavior/issues/257

**Comment by naa4sb** [comment]
Тэги по шагам, как я понимаю, и не поддерживаются "официально". По автодокументации (#260) тоже есть желание как-то отдельные служебные шаги исключать, но, видимо, другой способ надо искать. А вот про тэги сценариев и фич, и включение/исключение в выполнение, явно описано в:
https://cucumber.io/docs/reference#gherkin
https://github.com/cucumber/cucumber/wiki/Tags

**Comment by Pr-Mex** [comment]
@naa4sb
Да, соглашусь.

**Comment by allustin** [comment]
У Gherkin есть AST дерево кстати https://github.com/cucumber/gherkin

![](https://raw.githubusercontent.com/cucumber/gherkin/master/docs/ast.png)

Тэгировать можно - Фичи, Сценарии, Структурные сценарии и Примеры. Как только мы вставим тэги на шаги - все валидаторы отвалятся

**Comment by Pr-Mex** [comment]
Сделано. Закрываю.
