### ISSUE TITLE
Не активизируется строка таблицы формы при открытие из подчиненной формы (TESTCLIENT)

### ISSUE THREAD

**Issue by snov1kov** [silverbulleters/vanessa-behavior#342]
```Gherkin
Функционал: Переход к строке таблицы значения в управляемой форме в кнопканажималке
   Как Пользователь VB
   Я хочу Использовать в проверке своих сценариев библиотечный шаг " В форме "ФормаОбработки" в таблице "ТаблицаЗначения" я перехожу к строке: ..." для автоматического перехода к строке таблицы значения управляемой формы

Контекст:
  Дано: VB 1.000
  И 1С 8.3.7.1917
  и УТ11.1

Сценарий: Переход к строке табличной части
  Допустим: В TestClient открывается форма обработки 
  Когда: Вызывается шаг фичи "В форме "ФормаОбработки" в таблице "ТаблицаЗначения" я перехожу к строке"
  Тогда: Курсор перемещается к строке таблицы значения "ТаблицаЗначения"

**Comment by snov1kov** [comment]
![default](https://cloud.githubusercontent.com/assets/19814854/16609056/866a978e-4359-11e6-80a0-d2bffa5faf25.png)

**Comment by allustin** [comment]
@snov1kov в управляемых формах на форме нет таблицы значений. Есть ЭлементФормы (Тип - ТаблицаФормы).

нажатие происходит именно на элемент, а точнее на элемент таблицы

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Libraries/UITestRunner/step_definitions/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%BC/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L623

В нашем случае проблема вот тут:

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Libraries/UITestRunner/step_definitions/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%BC/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L685

Удобней включить вывод отладочных сообщений или открыть обработку UI в режиме отладки.
Кстати - можно же еще посмотреть что произойдет на самом тест клиенте. Почему это строки на форме не оказалось

**Comment by Pr-Mex** [comment]
@snov1kov 
можете посмотреть какой элемент формы являлся активным в данный момент?
Вроде была такая проблема, когда таблица во время перехода к строке была не активна.

**Comment by snov1kov** [comment]
@Pr-Mex Была активна кнопка на форме перед этим шагом

**Comment by Pr-Mex** [comment]
Ок.
Тогда давайте удостоверимся в чём проблема.
Добавьте шаг перед переходом к строке
```
И Пауза 10
```
и сделайте эту таблицу активным вручную.
Если проблема в активности таблицы - то переход к строке должен сработать.

**Comment by snov1kov** [comment]
@Pr-Mex Да, если вручную щелкнуть после паузы отрабатывает корректно

**Comment by Pr-Mex** [comment]
Понял.

**Comment by allustin** [comment]
@snov1kov очень интересный момент

можешь добавить шаг 

```
И Открылось окно "Добавление номенклатуры из НСИ (Росско)"
```

вместо паузы 

код проверки уже есть тут - 

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Libraries/UITestRunner/step_definitions/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%A1%D0%98%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%BC/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L593

**Comment by snov1kov** [comment]
@allustin Проблема в том, что не активно ТабличноеПоле, окно итак активно

**Comment by allustin** [comment]
вот враги 1С-ники - там же явно вызывается Активизировать()

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Libraries/UITestRunner/step_definitions/РаботаСИнтерфейсом/Form/Форма/Форма.bsl#L634

**Comment by 1cto** [comment]
А-а-а, делюсь опытом. Надо вызвать "перейти к первой строке" - тогда Ок )

**Comment by SonicNorg** [comment]
Привет, фиксить не будете этот баг?

**Comment by Pr-Mex** [comment]
Ну как, баг платформы мы пофиксить не можем.
А насчет обхода этого момента - да, будем делать.

**Comment by Pr-Mex** [comment]
Решено. Добавил обход.

**Comment by EvilBeaver** [comment]
на 8.3.9 обход не всегда срабатывает. Вручную по f11 можно несколько раз получить падение, а затем - нормальное срабатывание.

Можно как-то узнать, что ТестируемаяТаблица является таблицей значений (не дин. списком)? 

Тогда можно было бы сделать построчный переход типа ПерейтиКПервой-СравнитьКлючи-ПерейтиКСледующей-СравнитьКлючи и т.д. до конца таблицы.

**Comment by Pr-Mex** [comment]
Тут про другой обход.
