### ISSUE TITLE
Ошибка записи периодического независимого регистра сведений из фикстуры

### ISSUE THREAD

**Issue by MZelensky** [silverbulleters/vanessa-behavior#359]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Запись 2 строк в периодический независимый РС с одинаковыми измерениями, но с разными периодами
   Как Разработчик
   Я хочу Хочу добавить 2 записи в периодический независимый РС с одинаковыми измерениями, но с разными периодами

Контекст:
  Дано: Vanessa Behavior v 1.000 
  И 1С:Предприятие 8.3 (8.3.7.1917)
  и Управление торговлей, редакция 11.1 (11.1.7.49)

Сценарий: Добавление 2 записей
  Допустим: Есть пустой РС
  Когда: загружаю из фикстуры 2 записи  с одинаковыми измерениями, но разными периодами
  Тогда: В РС создается 2 записи

```

> Прикладывайте файлы скриншотов

**Comment by MZelensky** [comment]
Обработка "Vanessa Behavior v 1.000", модуль объекта, процедура "СоздатьОбъект_Регистр", после цикла в строке № 2087 необходимо добавить конструкцию (если найдете как обойтись без перевода в строку, то будет здорово!!!):

Если Врег(МетаданныеНабора.ПериодичностьРегистраСведений) <> Врег("Непериодический") Тогда
   Объект.Отбор.Период.Установить(ЗаписьНабора["Период"]);	
КонецЕсли;

**Comment by MZelensky** [comment]
![default](https://cloud.githubusercontent.com/assets/20415649/17326194/df37d012-58d9-11e6-8b2b-496262e00134.jpg)

**Comment by Pr-Mex** [comment]
@MZelensky 
Спасибо за участие в проекте!

1. Чтобы проверить без преобразования в строку
```
МетаданныеНабора.ПериодичностьРегистраСведений <> Метаданные.СвойстваОбъектов.РежимЗаписиРегистра.Независимый
```

2. Я предлагаю вам сделать пулреквест, чтобы история изменения сохранилась за вами.

**Comment by Pr-Mex** [comment]
Залил код @MZelensky вручную.
Закрываю.
