### ISSUE TITLE
Обработка параметра сценария со значением даты '00010101'

### ISSUE THREAD

**Issue by SpaceHead1C** [silverbulleters/vanessa-behavior#372]
Версия инструментария: 1.021
Платформа: 8.3.8.1747
Самописная конфигурация: [мой репозиторий](https://github.com/SpaceHead1C/hw2.git) каталог "ib"

В фиче с помощью  обработки "[BDDEditor.epf](https://github.com/silverbulleters/vanessa-bdd-editor.git)" я описал сценарий, в параметр которого передаётся пустая дата рождения ('00010101') и ловил failed на его выполнении. Оказалось, в модуле формы обработки "vanessa-behavior.epf" в функции ПреобразоватьКДатеСтроку(...) сидит такой код (со стр. 3090):
`...
Если Год < 100 Тогда
	Год = Год + 2000;
КонецЕсли;
...`
Вопрос. Это баг? Если нет, то как мне в сценариях правильно описывать пустую дату?

**Comment by nixel2007** [comment]
@Pr-Mex это так смещение дат обыграно?

**Comment by Pr-Mex** [comment]
Просто пиши 01.01.01

**Comment by Pr-Mex** [comment]
Даты задаются через точку.

**Comment by SpaceHead1C** [comment]
В фичу писал так:

`Сценарий: возраст человека без данных о д/р
	Допустим есть человек с датой рождения 01.01.0001
	Когда сегодня 20.08.2016
	Тогда его возраст в месяцах будет равен 0`

**Comment by pumbaEO** [comment]
имхо автоопределение даты как параметра - это порочная практика из других
языков программирования, там есть регулярки, а у нас нет и правильней все в
строку записывать и уже в процедуре делать преобразование.

21 авг. 2016 г. 0:14 пользователь "SpaceHead1C" <notifications@github.com>
написал:

**Comment by Pr-Mex** [comment]
@nixel2007 
Это ошибка.
Исправил.
Теперь можно передавать пустую дату так
01.01.0001
Вот пример 
https://github.com/silverbulleters/vanessa-behavior/blob/develop/features/Core/FeatureReader/%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0%D0%9F%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B8%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%BE%D0%B2.feature#L35

**Comment by Pr-Mex** [comment]
Закрываю.
