### ISSUE TITLE
Не заполняется колонка "Обработка вызова" при генерации EPF

### ISSUE THREAD

**Issue by cybjavax** [silverbulleters/vanessa-behavior#374]
Функционал: делаю фичу, где указываю дату, текст файла ниже

---
# encoding: utf-8
# language: ru

Функционал: РасчетВозрастаЧеловекаВМесяцах
	Как кадровик
	Хочу получать расчет возраста человека в месяцах 
	Чтобы корректно расчитывать пенсию по старости

Сценарий: расчет возраста в месяцах
	Допустим у меня есть дата рождения сотрудника 15.06.1975
	И дата сегодня 19.08.2016
	Тогда расчет возраста в месяцах должен быть 494
----

Ожидаю: что бихавиор сгенерит EPF и заполнит колонку "Обработка вызова"

Что происходит: EPF генерит, но колонку не заполняет (скрин во вложении)

Отклонение: не заполняет колонку, как это описано в курсе

Скрин:
![2016-08-20_184857](https://cloud.githubusercontent.com/assets/21097721/17881841/e568d87a-6921-11e6-948c-fdf327ecb21b.png)

**Comment by Pr-Mex** [comment]
После генерации epf надо нажать на кнопку "Перезазгрузить сценарии". Это делали?

**Comment by cybjavax** [comment]
Да, это было сказано в видео курсе, прежде чем написать, с бубном вокруг поплясал и это естественно тоже пробовал. Видео, как это выглядит https://yadi.sk/i/96uwiVK3uQnzx

**Comment by Pr-Mex** [comment]
Видимо обработка не компилируется, поэтому не может подключиться.

**Comment by alehinsasha** [comment]
@Pr-Mex обработка - создается, но не заполняется колонка "Обработка вызова". Т.е. ошибка при генерации обработки. У меня по фиче нормально сгенерировалась обработка и колонка заполнилась.

**Comment by alehinsasha** [comment]
@cybjavax у вас два лишних шага добавляются в список тестов

`	Ванесса.ДобавитьШагВМассивТестов(ВсеТесты,"ТекущаяДата(Парам01)","ТекущаяДата","И текущая дата 19.08.2016");
	Ванесса.ДобавитьШагВМассивТестов(ВсеТесты,"РассчетВозрастаВМесяцахДолженБыть(Парам01)","РассчетВозрастаВМесяцахДолженБыть","Тогда рассчет возраста в месяцах должен быть 494");
`

и один из них `ТекущаяДата` назван так же как метод встроенного языка 1С.

Удалил код:

`	Ванесса.ДобавитьШагВМассивТестов(ВсеТесты,"ТекущаяДата(Парам01)","ТекущаяДата","И текущая дата 19.08.2016");
	Ванесса.ДобавитьШагВМассивТестов(ВсеТесты,"РассчетВозрастаВМесяцахДолженБыть(Парам01)","РассчетВозрастаВМесяцахДолженБыть","Тогда рассчет возраста в месяцах должен быть 494");
`

и удалил процедуры

`&НаКлиенте
//И текущая дата 19.08.2016
//@ТекущаяДата(Парам01)
Процедура ТекущаяДата(Парам01) Экспорт
	//Ванесса.ПосмотретьЗначение(Парам01,Истина);
	ВызватьИсключение "Не реализовано.";
КонецПроцедуры

&НаКлиенте
//Тогда рассчет возраста в месяцах должен быть 494
//@РассчетВозрастаВМесяцахДолженБыть(Парам01)
Процедура РассчетВозрастаВМесяцахДолженБыть(Парам01) Экспорт
	//Ванесса.ПосмотретьЗначение(Парам01,Истина);
	ВызватьИсключение "Не реализовано.";
КонецПроцедуры
`

и колонка заполнилась.

**Comment by Pr-Mex** [comment]
Увидеть, что в обработка не смогла подключиться из-за ошибок в модуле можно, если включить флаг отладки. Должно выводится сообщение.
![image](https://cloud.githubusercontent.com/assets/8627416/17887316/9072a762-692e-11e6-8e76-00278712950a.png)

**Comment by Pr-Mex** [comment]
Закрываю.
