### ISSUE TITLE
Не подгружаются экспортные сценарии.

### ISSUE THREAD

**Issue by naa4sb** [silverbulleters/vanessa-behavior#376]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

На коммите https://github.com/silverbulleters/vanessa-behavior/commit/d8276eb1a050b5e041f1b5c99ed2a4872cc81b9f
не подгружаются снипеты для экспортных сценариев. Например для такой фичи:
```Gherkin
#encoding: utf-8
#language: ru

Функционал: Тест

Сценарий: Тест
	Когда Я открыл сеанс TestClient от имени "Тест_1" с паролем "" или подключаю уже существующий
```

Получаем:
![2016-08-25 14 22 36](https://cloud.githubusercontent.com/assets/19772779/17967365/70e3a386-6acf-11e6-960a-af8ca16eaf44.png)

**Comment by naa4sb** [comment]
Хотя экспортные тут не при делах.

**Comment by Pr-Mex** [comment]
Да, этот снипет похоже был не корректно объявлен.

**Comment by Pr-Mex** [comment]
Вечером обновлю.

**Comment by Pr-Mex** [comment]
@naa4sb 
Проверь сейчас.

**Comment by naa4sb** [comment]
@Pr-Mex угу. всё работает. спасибо. закрываю.
