### ISSUE TITLE
Не отрабатывает исключение сценария по тэгу, если в предыдущих сценариях фичи есть шаги-сценарии

### ISSUE THREAD

**Issue by naa4sb** [silverbulleters/vanessa-behavior#381]
Вот по такой фиче не исключается второй сценарий при наличии тэга Draft в списке исключений.
```Gherkin
Функционал: Тест ошибки

Сценарий: Сценарий 1
	Когда Я запускаю сценарий открытия TestClient или подключаю уже существующий
@Draft
Сценарий: Исключаемый сценарий
	И Пауза 1
```
В первом сценарии шаг является шагом-сценарием.
При этом в окно сообщений при загрузке фич выводится, что в сценарии обнаружен тэг исключения, но сам исключаемый сценарий все равно загружается.

**Comment by Pr-Mex** [comment]
Решено. В коммитах написал по ошибке 384 вместо 381.
