### ISSUE TITLE
Проблемы с запуском TestClient (TestClient НЕ подключен.)

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#383]
Хотелось бы еще раз поднять тему:
https://github.com/silverbulleters/vanessa-behavior/issues/267

В нашем случае оказалось, что порт, через который общается менеджер с клиентом (1538), оказался занят svchost-ом. Указали в коде -TPort 1581 и все заработало.
Можно ли в настройки запуска testclient-а в VB добавить порт запуска?

**Comment by Pr-Mex** [comment]
Логично добавить в настройки номера порта.
Если заполнено - использовать его.
Иначе - порт по умолчанию.

**Comment by nixel2007** [comment]
Вот это да! Чудесные новости, спасибо за расследование.

**Comment by Pr-Mex** [comment]
А ещё логичнее добавить список разрешеных диапазонов портов, т.к. в будущем планируется сделать запуск множества сеансов TestClient, и это всё придётся разруливать.

**Comment by ivan-kovtun** [comment]
Могу я эту задачку на себя заасайнить? Или просто решить и сделать pull request?

**Comment by nixel2007** [comment]
Ассайнить могут только коллабораторы, на сколько я помню. Обычного комментария о начале работ хватит :) 

На всякий случай уточню порядок действий, который планировали мы (я, @Pr-mex и @allustin) :
* через netstat получить список занятых портов 
* найти свободный порт в резервном фиксированном диапазоне tcp-портов (49000+, точнее см. на вики) 
* пробросить порт в запуск тест клиента (который через ЗапуститьПриложение в модуле формы VB) через параметр -TPort
* этот же порт указать в конструктуре тестируемого приложения
* возможно потребуется сохранить этот порт в реквизитах формы - проверить, можно ли достигнуть ситуации, когда тест клиент как приложение уже запущен, но не подключён через ТестируемоеПриложение

**Comment by pumbaEO** [comment]
Для linux комманда показа занятых портов:
```
ss -tuwan4 2>/dev/null | awk '{print $5}' | grep ':' | cut -d ":" -f 2 | sort | uniq
```
выдаст список портов которые сейчас заняты.

**Comment by nixel2007** [comment]
@pumbaEO я думал нетстат как раз родом из линукса и можно сделать кроссплатформенную команду :)

**Comment by pumbaEO** [comment]
В линуксе уже от нее отказываются, новая команда ss совместимая с netstat

**Comment by Pr-Mex** [comment]
@ivan-kovtun - делай. Фича нужная.

**Comment by ivan-kovtun** [comment]
Ok, тогда я занимаюсь.

**Comment by Pr-Mex** [comment]
Решено.
Сейчас автоматически определяется свободный порт.
