### ISSUE TITLE
Исправить запуск WShell под Windows в режиме пользователя с пробелами

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#384]
```Gherkin

Контекст:
  Дано: версия 1.0.26

Сценарий: Запуск Vanessa Behavior
  Допустим: пользователь Windows имеет временный каталог по адресу "C:\Users\Alexey Lustin\AppData\Local\Temp\"
  Когда: Я запускаю Vanessa Behavior
  Тогда: форма Behavior открыта без ошибок
```

ошибка кроется например тут 

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/vanessa-behavior/Form/УправляемаяФорма/Форма.bsl#L6079

> {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(6079)}: Ошибка при вызове метода контекста (Run)
   WshShell.Run(ИмяВременнгоФайла + " > " + ИмяВременногоЛог,0,-1);
по причине:
Произошла исключительная ситуация (0x80070002)

Примерное исправление

```BSL
Попытка
	WshShell = Новый COMОбъект("WScript.Shell");
				
	КомандаЗапуска = Символ(34) + ИмяВременнгоФайла + Символ(34) + " > " + Символ(34) + ИмяВременногоЛог + Символ(34);
				
	WshShell.Run(КомандаЗапуска,0,-1);

Исключение					
	ВызватьИсключение "Внутренняя ошибка работы с временными файлами
	| " + ИмяВременнгоФайла + " 
	| " + ИмяВременногоЛог + "
	| Полная строка запуска =" + КомандаЗапуска + "=
	| ошибка объекта WShell 
	|" + ОписаниеОшибки();
КонецПопытки;
```

Вообще стоитт сделать обертку над запуском WShell - так как таких мест несколько

**Comment by nixel2007** [comment]
Что такое символ 34? Кавычки?

**Comment by allustin** [comment]
@nixel2007 так точно "кавычки", Погрею тебе еще душу ;-)

обычный код который я вставляю везде где идет работа "с шеллом"

```BSL

Функция Обрамить(_ОбрамляемяСтрокаСтрока, _КодСимвола) 
    Возврат Символ(_КодСимвола) + _ОбрамляемяСтрокаСтрока + Символ(_КодСимвола);
КонецФункции

Функция ВКавычки(_ОбрамляемяСтрокаСтрока) Экспорт
    Возврат Обрамить(_ОбрамляемяСтрокаСтрока, 34)
КонецФункции

```

**Comment by allustin** [comment]
Вот эта строка также работать не будет 

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/vanessa-behavior/Form/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%B0%D1%8F%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L5958

**Comment by Pr-Mex** [comment]
Решено. Закрываю.

**Comment by nixel2007** [comment]
@Pr-Mex ты в номере ишуза не ошибься?

**Comment by Pr-Mex** [comment]
Не, не ошибся. Вот коммит по этой задаче
https://github.com/silverbulleters/vanessa-behavior/commit/80d8d02688d2164f4f1a76fa9f5aa6cbeb45dfa9

Предлагаю задачу закрыть.

**Comment by allustin** [comment]
@nixel2007 связал с комментом по коммиту - там глобальней исправление, не только этого

**Comment by nixel2007** [comment]
Смотрел коммит "Решил проблему", извиняюсь.

**Comment by Pr-Mex** [comment]
Да, я в первом коммите указал не тот номер задачи. Сори.
