### ISSUE TITLE
Ошибка "Значение не является значением объектного типа "Время начала"

### ISSUE THREAD

**Issue by snov1kov** [silverbulleters/vanessa-behavior#385]
```Gherkin
Функционал: Исключение ошибки "Значение не является значением объектного типа "Время начала"
   Как разработчик
   Я хочу пользоваться функционалом VB, без сообщений об ошибке Значение не является значением объектного типа "Время начала"

Контекст:
  Дано: VB 1.026
  И 8.3.8.1784
  и УТ 10.3

Сценарий: Запуск фича-файла
  Допустим: Существует фича файл ПолучениеЗаказаПокупателяИзРозницы.feature
  Когда: Сгенерирована обработка ПолучениеЗаказаПокупателяИзРозницы.epf
  Тогда: Проверка сценариев проходит без ошибок


```

![vbbug](https://cloud.githubusercontent.com/assets/19814854/18240329/ac42841a-7353-11e6-8805-a56b01ffd5d1.png)
[ПолучениеЗаказаПокупателяИзРозницы.zip](https://github.com/silverbulleters/vanessa-behavior/files/454549/default.zip)
[ПолучениеЗаказаПокупателяИзРозницы.zip](https://github.com/silverbulleters/vanessa-behavior/files/454550/default.zip)

**Comment by Pr-Mex** [comment]
Не получается воспроизвести ошибку у себя.
Вы можете создать пример воспроизводящий ошибку на любой конфигурации?
Какие настройки надо для этого сделать?

**Comment by snov1kov** [comment]
После обновления Ванессы баг пропал, не воспроизводится
