### ISSUE TITLE
Если не указан путь до водяного знака, то создание видео падает

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#388]
Ошибка в строке  827 модуля РаботаСВидео
ЗТ.ЗаписатьСтроку(""+ Лев(ГдеИскать,2));

**Comment by Pr-Mex** [comment]
Буду смотреть.

**Comment by Pr-Mex** [comment]
А если указан путь до водяного знака, работает?

**Comment by viskvortsov** [comment]
Да

**Comment by viskvortsov** [comment]
Там инициализация ЗТ происходит только в ветке с водяным знаком

**Comment by Pr-Mex** [comment]
Ок. Исправлю.

Покажите результат видео, если это возможно.
Можно в личку.
pautovlv@gmail.com

**Comment by viskvortsov** [comment]
Покажу, когда доделаю, осталось вроде только говорилку прикрутить

**Comment by Pr-Mex** [comment]
Напомню, что вот тут лежит инструкция как установить софт
https://github.com/silverbulleters/vanessa-behavior/blob/develop/MakeAutoVideo.md

**Comment by viskvortsov** [comment]
Скинул результат на pautovlv@gmail.com

**Comment by Pr-Mex** [comment]
Весело )))
Ответил.

**Comment by Pr-Mex** [comment]
Закрываю.
