### ISSUE TITLE
Ошибки в Режиме использования синхронных вызовов расширений платформы и внешних компонент = Не использовать

### ISSUE THREAD

**Issue by git22ura** [silverbulleters/vanessa-behavior#395]
Для конфигурации у которой "Режим использования синхронных вызовов расширений платформы и внешних компонент" установлен в  "Не использовать"
фича с кодом

``` Gherkin
Контекст: 
    Дано: Я запускаю сеанс 1С с ключом TESTCLIENT С Логином "Руководитель" И Паролем ""
```

падает с ошибкой
13.09.2016 11:38:19 {ВнешняяОбработка.ОткрытьTestClient.Форма.Форма.Форма(109)}: Ошибка при вызове метода контекста (Существует): Использование синхронных методов на клиенте запрещено!; ИмяФайла=c:\repo\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\ОткрытьTestClient.epf, ИмяПроцедуры=ЯЗапускаюСеанс1ССКлючомTESTCLIENTСЛогиномИПаролем

**Comment by Pr-Mex** [comment]
Исправлено. Проверьте.

**Comment by git22ura** [comment]
Работает, спасибо

**Comment by git22ura** [comment]
поторопился, другая ошибка:
``
14.09.2016 12:39:10 {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(7838)}: Ошибка при вызове метода контекста (ЗапуститьПриложение): Использование синхронных методов на клиенте запрещено!; ИмяФайла=c:\repo\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\ОткрытьTestClient.epf, ИмяПроцедуры=ЯАктивизируюГлавноеОкноСеансаTESTCLIENT
``

**Comment by Pr-Mex** [comment]
Приложи свой feature файл, пожалуйста.

**Comment by git22ura** [comment]
Полтергейст. Сейчас работает. Попереключал туда-сюда режим, работает в обоих случаях. 
``
# encoding: utf-8
# language: ru
@tree

Функционал: Закупка товаров и услуг
	Как Оператор
	Хочу вводить данные о поступивших товарах и услугах
	Чтобы документально зафиксировать поступление

Контекст: 
	Дано: В системе есть документ Покупка
	И в справочнике "Номенклатура" есть элемент с наименованием "Веник для теста"

Сценарий: Покупка товара
	Допустим Привезли товар на склад
	И Я запускаю сеанс 1С с ключом TESTCLIENT С Логином "Оператор" И Паролем ""
	И Я активизирую главное окно сеанса TESTCLIENT	
	Когда Я ввожу данные о товаре в документ Покупка
		Когда Я нажимаю кнопку командного интерфейса "Покупка"
		Тогда открылось окно "Покупка"
		И     я нажимаю на кнопку "Создать"
		Тогда открылось окно "Покупка (создание)"
		И     в ТЧ "Товары" я нажимаю на кнопку "Добавить"
		И     в ТЧ "Товары" я нажимаю кнопку выбора у реквизита "Номенклатура"
		Тогда открылось окно "Номенклатура"
		
		И     я нажимаю на кнопку "Расширенный поиск"
		Тогда открылось окно "Найти"
		И     в поле "&Что искать" я ввожу текст "Веник для теста"
		И     я меняю значение переключателя "Как искать" на ""
		И     я нажимаю на кнопку "&Найти"
		Тогда открылось окно "Номенклатура"
		И     В форме "Номенклатура" в таблице "Список" я перехожу к строке:
		| 'Наименование' |
		| 'Веник для теста'        |
		И     я нажимаю на кнопку "Выбрать"		

		Тогда открылось окно "Покупка (создание) *"
		И     в ТЧ "Товары" я активизирую поле "Количество"
		И     в ТЧ "Товары" в поле "Количество" я ввожу текст "1"
		И     в ТЧ "Товары" я активизирую поле "Сумма"
		И     в ТЧ "Товары" в поле "Сумма" я ввожу текст "100"
		И     В форме "Покупка (создание) *" в ТЧ "Товары" я завершаю редактирование строки
		И     я нажимаю на кнопку "Записать"
		И     Пауза 1
		И	  Документ получил очередной номер
		И	  я нажимаю на кнопку "Провести и закрыть"
		И	  Пауза 1
		Тогда открылось окно "Покупка"
		И     Я закрываю окно "Покупка"
	Тогда в системе сохранился новый документ 
	И я закрываю сеанс TESTCLIENT
``

**Comment by git22ura** [comment]
И все-таки ошибка проявляется.
Если при прогоне сценария была ошибка (а это происходит регулярно, ибо сценарий только пишется) 
и после этого исправить выпавшую ошибку
и сохранить обработку
и после этого нажать перезагрузить сценарии
и нажать выполнить сценарии
Тогда получаем ошибку про синхронность.

При этом, если перезапустить сеанс, то ошибка не появляется. 
1С:Предприятие 8.3 (8.3.8.2054)

**Comment by Pr-Mex** [comment]
Это обычный режим или с запретом синхронных вызовов?

**Comment by git22ura** [comment]
Режим "Не использовать"

**Comment by Pr-Mex** [comment]
Понял.
Флаг выполнять шаги асинхронно пока надо оставить включенным.
Он сделан в экспериментальных целях.
Позже разберусь с этим.

**Comment by Pr-Mex** [comment]
@git22ura Попробуй сделать тоже самое, когда флаг **Выполнять шаги асинхронно** включен.

**Comment by git22ura** [comment]
@Pr-Mex  При включенной галке упавший тест не рушит остальные. Перезагрузка и выполнение сценариев также не вызывает ошибки про синхронность.
Т.е. правильное поведение

**Comment by Pr-Mex** [comment]
Понятно. Я позже буду с этим флагом разбираться.

**Comment by Pr-Mex** [comment]
@git22ura 
Привет.
Можешь проверить на текущей версии VB - ошибка воспроизводится?

**Comment by git22ura** [comment]
Привет!
На 1.071 не удалось воспроизвести. Значит все хорошо
