### ISSUE TITLE
Ошибка при прогоне всех feature файлов vanessa-behavior

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#396]
ОС: Windows 7 (32bit)
VB: 1.030

При прогоне всех feature файлов возникают ошибки из скриншота

![project002_000032](https://cloud.githubusercontent.com/assets/8247178/18553611/be3ed9fc-7b69-11e6-8e2f-fbfaf90bd598.png)

**Comment by Pr-Mex** [comment]
Выпустил обновление.
Проверьте.

**Comment by Pr-Mex** [comment]
Закрываю.
