### ISSUE TITLE
Передача параметра в сценарий в таблицу

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#406]
@ExportScenarios
...
Сценарий: Пример тестового сценария с "ИмяПараметра"
...
В форме "Группы доступа физических лиц" в таблице "Список" я перехожу к строке:
    | 'Код'    | 'Наименование' |
    | '00-001' | "ИмяПараметра"     |
....

В таком варианте вызов извне не изменит параметр в таблице, а должен.

**Comment by viskvortsov** [comment]
`В таком варианте вызов извне не изменит параметр в таблице, а должен.`
А есть вариант вызова с таблицей, который работает?

**Comment by Pr-Mex** [comment]
Если я правильно понял вопрос - то это как раз надо сделать.

**Comment by Pr-Mex** [comment]
Решено. Можно проверять.

**Comment by rozhkovdmitriy** [comment]
Ошибка исправлена, спасибо, @Pr-Mex
