### ISSUE TITLE
Ошибка вызова шага нажатия кнопки "Добавить" ТЧ документа при воспроизведении сценария (8.3.9.1818)

### ISSUE THREAD

**Issue by arkuznetsov** [silverbulleters/vanessa-behavior#409]
В 8.3.9 обнаружилась ошибка (в клиенте x64, на x32 не проверял): 
При вызове шага нажатия на кнопку командной панели ТЧ, в обработке РаботаСИнтерфейсом в процедуре ВОткрытойФормеВТЧЯНажимаюНаКнопкуСЗаголовком в строке 1646 вызывается: 

"Кнопка = ТЧ.НайтиОбъект(Тип("ТестируемаяКнопкаФормы"), ИмяКнопки);" 

и вместо кнопки "Добавить" командной панели, находится кнопка "Добавить" контекстного меню 
после чего при вызове "Кнопка.Нажать()" происходит ошибка: 

{ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(1659)}: Ошибка при вызове метода контекста (Нажать): Метод не может быть вызван для данного объекта (Добавить): Метод не может быть вызван для данного объекта (Добавить); ИмяФайла=d:\work\repo\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\Ра­ботаСИнтерфейсом.epf, ИмяПроцедуры=ВТЧЯНажимаюНаКнопку, версия VB=ver 1.035 

со стороны конфигурации можно обойти, отключив контекстное меню 
в 8.3.8 ошибки нет.

> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Выполнение сценария тестирования, описанного в feature-файле
   Как Разработчик
   Я хочу Использовать vanessa-behavior для записи и воспроизведения действий пользователя
   Чтобы создавать feature-файлы и выполнять тестирование разработок

Контекст:
  Дано: Версия vanessa-behavior равна 1.035
  И И версия 1С равна 8.3.9.1818 (x64)
  и конфигурация = "учебная конфигурация для прохождения задания по курсу"

Сценарий: Воспроизведение добавления строки в документ
  Допустим: Я создаю документ
  И я записываю поведение пользователя при добавлении строки документа
  И я создаю feature-файл
  И я описываю сценарий
  И я добавляю записанный текст действий пользователя
  Когда: я запускаю воспроизведение сценария
  Тогда: на шаге добавления строки в документ происходит ошибка сценария

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
