### ISSUE TITLE
Добавить в библиотеку шаги для воспроизведения следующих действий пользователя "ВыполнитьВыборИзМеню" и "ВыполнитьВыборИзСписка"

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#411]

**Comment by Pr-Mex** [comment]
Укажите подробнее о чём идёт речь.
Какие действия совершает пользователь?

**Comment by nixel2007** [comment]
@Pr-Mex внезапно выбирает элемент из меню и из списка

**Comment by Pr-Mex** [comment]
На сколько я помню, на это уже существует шаг в библиотеке.

**Comment by alehinsasha** [comment]
[видео уточнение](https://drive.google.com/file/d/0By-W2XsFwhjxeHNteGJUaWt5SGM/view?usp=sharing)

> На сколько я помню, на это уже существует шаг в библиотеке.

Поиск по "ВыполнитьВыборИзМеню" и "ВыполнитьВыборИзСписка" в репо VB ничего кроме этого issue не выдает.

**Comment by Pr-Mex** [comment]
Ок. Теперь понятно.

**Comment by Pr-Mex** [comment]
Решено.
Надо использовать шаги:
```
	И     я выбираю пункт меню "Товар"
	И     я выбираю из списка  "Элемент списка"
```
