### ISSUE TITLE
Поправить инструкцию по записи видео и доработать проверку работы записи видео

### ISSUE THREAD

**Issue by PiskunovSS** [silverbulleters/vanessa-behavior#412]
- [ ] В обработке РаботаСВидео.epf поправить процедуру проверки, что установлен convert.exe от  ImageMagick, т.к. сейчас проверка проходит успешно без установки данного компонента, а проблема выявляется только на одном из последних этапов по монтажу видео.

В инструкции по записи видео https://github.com/silverbulleters/vanessa-behavior/blob/develop/MakeAutoVideo.md необходимо: 
- [ ] В пункте 4 изменить ссылку на [Server Runtime Languages версии 11](https://www.microsoft.com/en-us/download/details.aspx?id=27224) (сейчас ссылка на 10.2, которая не работает с указанной Microsoft Speech Platform - Runtime (Version 11));
- [ ] В пункте 2 дополнительно указать, что при установке ImageMagick необходимо обязательно установить флаг "Install legacy utilities (e.g. convert)" , иначе convert.exe не будет установлен.

**Comment by Pr-Mex** [comment]
Большое спасибо. Особенно за пункт 2 и 3. Сталкивался с этим.

> В обработке РаботаСВидео.epf поправить процедуру проверки, что установлен convert.exe от ImageMagick, т.к. сейчас проверка проходит успешно без установки данного компонента, а проблема выявляется только на одном из последних этапов по монтажу видео.

Кнопка **ПроверитьЧтоЗаписьВидеоБудетРаботать** проверяет работу и команды Convert тоже.

**Comment by PiskunovSS** [comment]
> Кнопка ПроверитьЧтоЗаписьВидеоБудетРаботать проверяет работу и команды Convert тоже.

Да я в коде видел, что проверка вроде как есть, но по факту не отрабатывает. 
![imagemagic](https://cloud.githubusercontent.com/assets/10277115/19264307/dc1d582e-8fa8-11e6-8164-6e44a7afdce3.png)

**Comment by PiskunovSS** [comment]
Виноват, не ту кнопку нажал)

**Comment by Pr-Mex** [comment]
Там идея была в том - что надо получить все ОК по кнопке **ПроверитьЧтоЗаписьВидеоБудетРаботать**.
И только потом записывать видео.
Тогда добавлю ещё проверку при старте записи.

**Comment by PiskunovSS** [comment]
Не то немного. Сейчас проверка не прошла из-за отсутствия голоса. Но по ImageMagic пишет ОК, хотя файла C:\Program Files\ImageMagick-7.0.3-Q16\convert.exe не существует. На скрине выше  сортировка по именам файлов.

**Comment by Pr-Mex** [comment]
Ок. Буду проверять.

**Comment by PiskunovSS** [comment]
Если голос поставлю, то все проверки будут пройдены, но при склейке финального видео вывалится ошибка, т.к. не будут видео файлы, которые создаются из картинки.

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
