### ISSUE TITLE
Ванесса виснет при попытке выполнить шаг в тестклиенте

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#417]
Бывает такое, что при попытке исполнения шага, например:

И     В форме "Возврат товаров от розничного покупателя (Ваш KPI)" в таблице "Товары" я перехожу к строке:
                | 'Дисконтная карта' | 'Контрагент'         | 'Количество' | 'Цена'      | 'Характеристика' | 'Сумма'     | 'Дата чека'  | 'Номер чека' | 'Возврат' | 'Номенклатура' |
                | '987654321'        | 'ИвановИванИванович' | '1'          | '10 000,00' | 'S'              | '10 000,00' | '20.01.2016' | '1'          | 'Нет'     | 'Блузка'       |

При этом визуально видно, что такая строка есть и перейти к ней он должен, но ни падения ни перехода не происходит пока вручную не зайти и не выключить ТестКлиент.

Есть у кого-нибудь похожая проблема? как бороться?

**Comment by Pr-Mex** [comment]
Какая версия платформы?

**Comment by nixel2007** [comment]
@viskvortsov сколько строк в таблице?
Переход к строке происходит последовательным перебором всех строк с тест-клиента и проверки на совпадение по строчным представлениям реквизитов (типовой механизм тест-клиента)

**Comment by Pr-Mex** [comment]
Ещё хорошо бы сказать точную строку кода на которой зависает сеанс 1С.

**Comment by viskvortsov** [comment]
8.3.8.1747
Попробую отловить зависание. Сообщу

**Comment by Pr-Mex** [comment]
Удалось разобраться?

**Comment by viskvortsov** [comment]
Пока нет, если работать с отладкой, то все хорошо.

**Comment by viskvortsov** [comment]
Пока достоверно удалось выявить следующее.
Зависание происходит только в том случае, если шаг должен был упасть.
Но в некоторых случаях вместо падения VB просто останавливается.
Причем зависать может не только при переходе к строке, но и, например, при попытке нажатия кнопки

**Comment by Pr-Mex** [comment]
Получается стабильно воспроизвести проблему? Или ошибка плавающая?

**Comment by Pr-Mex** [comment]
Пока закрываю.
Переоткройте, если получится получить сценарий воспроизведения проблемы.
