### ISSUE TITLE
Параллельная проверка по ролям

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#420]
``` Gherkin
Функционал: Запуск проверок поведения параллельно
   Как релиз менеджер
   Я хочу запускать проверки параллельно
   Чтобы сократить время сборки
```

Есть парочка идей как это сделать. 

//cc @nixel2007 - это можно сделать на базе проверятора производительности или на базе @alehinsasha инструмента для запуска нескольких тест-клиентов

**Comment by nixel2007** [comment]
Код выполняется тест менеджером, а он обычно один. Для истинной параллельной проверки надо будет запускать несколько тест менеджеров на разных портах (такое тоже есть и работает)

**Comment by JohnyDeath** [comment]
@allustin 
> на базе проверятора производительности

это что за зверь?

**Comment by Pr-Mex** [comment]
Решено. Например можно использовать

```
И я подключаю TestClient "Кладовщик" логин "Пользователь1" пароль "1"
И я подключаю TestClient "Оператор" логин "Пользователь2" пароль "2"
И я активизирую TestClient "Кладовщик"
И я закрываю TestClient "Оператор"
```
