### ISSUE TITLE
Проверка того что запись видео будет работать не видит голосовой движок если в пути к голосовому движку есть пробелы

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#421]
Контекст:
  Дано: vanessa-behavior 1.043
  И платформа 8.3.8.1652
  и чистая инфобаза

Сценарий: проверка доп. инструментария для создания авто-видео-инструкций
  Допустим я установил голосовой движок в Program files
  Когда я загрузил настройки по умолчанию
  И я указал путь к голосовому движку в соответствующем поле
  И я нажал кнопку проверить что запись видео будет работать
  Тогда получаю сообщение что голосовой движок не установлен
  А он установлен

![2016-10-26_21-01-50](https://cloud.githubusercontent.com/assets/8247178/19743214/1e25fdfa-9bd1-11e6-807a-efae5597ba3a.png)

**Comment by Pr-Mex** [comment]
Решено.
