### ISSUE TITLE
кодировка адреса картинки в инструкции Markdown

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#422]
Хотел бы обсудить следующий вопрос.

Есть возможность формировать инструкции в формате Markdown.
Соответственно, есть желание хранить документацию в отдельном гит репозитории.

Однако, при просмотре Markdown файла картинки не отображаются, как я понимаю из-за того, что название картинок на русском.
Есть ли какие-нибудь способы обхода или решения этого вопроса?

Сервер git Gogs

**Comment by Pr-Mex** [comment]
На гитхаб всё показывает.
Вы уже проверили, что если переименовать на английский, то работает?

**Comment by viskvortsov** [comment]
хм, дельное замечание.
Переименование на англ не помогло.
Видимо что-то в настройках Gogs

**Comment by Pr-Mex** [comment]
Тогда закрываю.

**Comment by viskvortsov** [comment]
Чтобы зафиксировать.
Похоже, что gogs не обрабатывает ссылку на картинку, если она представлена в таком формате: 
`<img src="docs/testirovanie_001.png">`
но работает, если сделать так:
`![](docs/testirovanie_001.png)`

Второй формат работает и на github.
Есть ли возможность сменить формат?

**Comment by Pr-Mex** [comment]
Да.

**Comment by Pr-Mex** [comment]
Решено. Можно проверять.
