### ISSUE TITLE
Не открывается VB

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#423]
Контекст:
  Дано: 1.044
  И 8.3.8.1747
  и Управление Торговлей ред. 10.3

Наблюдается следующая ошибка в процедуре ПолучитьМассивЗанятыхПортов():

```
ЗТ = Новый ЗаписьТекста(ИмяВременногоBat, "OEM 866",,Истина); 
ЗТ.ЗаписатьСтроку("chcp 65001"); 
ЗТ.ЗаписатьСтроку("netstat -ano > " + ИмяВременногоФайла + ""); 
ЗТ.Закрыть();  

ВыполнитьКомандуОСБезПоказаЧерногоОкна(ИмяВременногоBat);

Текст = Новый ЧтениеТекста;
Текст.Открыть(ИмяВременногоФайла,"UTF-8");
```

При выполнении ВыполнитьКомандуОСБезПоказаЧерногоОкна(ИмяВременногоBat); временный файл ИмяВременногоФайла по каким-то причинам не создается, что приводит к ошибке: 

```
{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(7922)}: Ошибка при вызове метода контекста (Открыть)
    Текст.Открыть(ИмяВременногоФайла,"UTF-8");
по причине:
Файл не обнаружен 'C:\Users\Артем\AppData\Local\Temp\v8_78E_17.txt'
```

В результате VB не открывается.
Пока лечим тем, что комментируем вызов ПолучитьМассивЗанятыхПортов()

**Comment by Tushkan** [comment]
Вероятнее всего проблема возникает из-за наличия кириллицы в пути файла

**Comment by viskvortsov** [comment]
Ну, наличие кириллицы в пути как и пробелов - нормальная ситуация для windows

**Comment by Pr-Mex** [comment]
Я думаю проблема в кодировке bat файла.
Сейчас выставлена OEM 866.
@viskvortsov можете попробовать поменять на 1251 или utf-8 и проверить останется ли ошибка?

**Comment by Pr-Mex** [comment]
Решено. Закрываю. Прошу сообщить если ошибка осталась.
