### ISSUE TITLE
Для обычных форм нужна выгрузка кода обработки проверки фичи в текстовый документ

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#424]
![image](https://cloud.githubusercontent.com/assets/8247178/19802827/290e92ca-9d0e-11e6-8252-96e68bb8d14d.png)

**Comment by Pr-Mex** [comment]
Думаю - задача неактуальна.
Закрываю.
Прошу переоткрыть задачу, если это не так.
