### ISSUE TITLE
runtime error (8.3.5)

### ISSUE THREAD

**Issue by rozhkovdmitriy** [silverbulleters/vanessa-behavior#426]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Создание фич собственного приложения
   Как Разработчик
   Я хочу применять Vanessa Behavior для разработки через тестирование в собственном окружении 

Контекст:
  Дано: Vanessa Behavior 1.044
  И 1C Предприятие 8.3.5.1460
  и кофигурация Управление автотранспортом

Сценарий: Добавление новой библиотеки на вкладке 
  Допустим: Есть каталог D:\src\features\library и в нем находится файл ПроверкиЛогистики-vanessa-begavior-library.epf
  Когда: Открываю обработку Vanessa Behavior 
И Перехожу на вкладку "Библиотеки"
И Выполняю команду "Добавить"
И Кликаю на кнопке выбора (F4)
Тогда: Открывается окно выбора каталога библиотеки
```

> Прикладывайте файлы скриншотов
![- - - -](https://cloud.githubusercontent.com/assets/801971/19851237/b260e36c-9f7e-11e6-87a0-33070061a202.png)

**Comment by Pr-Mex** [comment]
Поведение на 8.3.5 мы не проверяли.
Ошибка воспроизводится у вас только на 8.3.5? Или на других версиях ошибки нет?

**Comment by rozhkovdmitriy** [comment]
Не смогу в ближайшей перспективе. Тогда пусть висит :) как только появится возможность (не думаю, что скоро), обязательно протестирую.
Спасибо!

**Comment by nixel2007** [comment]
@Pr-Mex Вроде же заявляется поддержка 8.2.19? Или это только для обычных форм?

**Comment by Pr-Mex** [comment]
@nixel2007 Да.
Но на CI сейчас нет сборки под 8.3.5.
Если надо - добавим.

**Comment by Pr-Mex** [comment]
Попробовал на 8.3.5.1625 - ошибки с библиотекой не получил.
У вас в автотранспорте стоит режим совместимости?

**Comment by Pr-Mex** [comment]
Зато получил другую ошибку на 8.3.5.1625.
При попытке загрузить фичу падает вот на этой строке
![image](https://cloud.githubusercontent.com/assets/8627416/20032929/de8c06e4-a3a5-11e6-998c-93c39f6322b1.png)

Похоже на ошибку платформы.
Кто может у себя проверить?

**Comment by rozhkovdmitriy** [comment]
Да, стоит режим совместимости.
![-](https://cloud.githubusercontent.com/assets/801971/20036362/794d528c-a428-11e6-9651-eb4a4b38b22f.png)

**Comment by Pr-Mex** [comment]
Насчет ошибки синхронных вызовов. Она возникает, только если 1С был запущен из конфигуратора.

**Comment by Pr-Mex** [comment]
Решено. Проверьте.
