### ISSUE TITLE
Feature files and video-doc IN ROMANIAN

### ISSUE THREAD

**Issue by 1C-Romania** [silverbulleters/vanessa-behavior#427]
уважаемые коллеги, исходя из увиденного: 
создание feature-скриптов на русском, а потом и на английском и последующая генерация видео-доков на этих языках

возник вопрос:
а есть ли такие возможности для РУМЫНСКОГО языка?

**Comment by allustin** [comment]
@1C-Romania https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json#L2219

**Comment by Pr-Mex** [comment]
@1C-Romania  @allustin 
Штатная поддержка в Gherkin румынского (и всех других языков, которые были в докладе @1C-Romania на Infostart 2016) конечно есть. Но у нас свой парсер Gherkin.
Он не поддерживает румынский прямо сейчас.
Надо добавлять.

**Comment by nixel2007** [comment]
> Но у нас свой парсер Gherkin.
Он не поддерживает румынский прямо сейчас.
Надо добавлять.

Предлагаю сразу привязаться к gherkin-languages и генерить кусок кода с чтением ключевых слов автоматически

**Comment by Pr-Mex** [comment]
@nixel2007 
Я за.
Как это технически просто сделать?

**Comment by 1C-Romania** [comment]
WOW!
коллеги, скорость вашей реакции просто поражает воображение!

> Надо добавлять
какие шансы?

**Comment by Pr-Mex** [comment]
Плюс мне ещё в генерации видео надо будет использовать эти данные.
Там я использую слова "Сценарий". И финальный кадр тоже получается надо переводить.

**Comment by Pr-Mex** [comment]
Я тут подумал. А с финальным кадром так сходу не получится. Там не используются ключевые слова из Gherkin. Проще его для иностранных языков оставить на английском.

**Comment by nixel2007** [comment]
@Pr-Mex предлагаю простое решение.
1. json с языками кладется в репо - главное его периодически обновлять. или подключается сабмодулем или просто руками.
2. проверка на ключевые слова (все вот эти `Если Слово = "Функциональнсть" ИЛИ Слово = Сценарий" ИЛИ ...`) переписывается на вхождение слова в массив ключевых слов.
3. Массив ключевых слов (по-секционный: МассивКогда, МассивТогда и т.д. на основании i18n) заполняется динамически на основании языка фичи (из первой строки).

**Comment by nixel2007** [comment]
Для видеоинструкций надо смотреть, как управлять движком TTS. По идее можно так же составить соответствие язык-голос и подключать его динамически

**Comment by 1C-Romania** [comment]
> финальный кадр ... для иностранных языков оставить на английском

вполне нормальное решение!

**Comment by Pr-Mex** [comment]
Для голоса проблем нет. Я оставил параметр - который управляет какой голосовой движок использовать. 
Проблема именно с текстом на финальном кадре
![image](https://cloud.githubusercontent.com/assets/8627416/19921785/93c1f888-a0f0-11e6-94e3-6f4394c9d36d.png)

**Comment by nixel2007** [comment]
Плюс хорошо бы подглядывать в основную реализацию геркина. Я не смотрел детально, как это сделано в VB. Вот реализация из javascript - https://github.com/cucumber/gherkin/tree/master/javascript/lib/gherkin

Буквально вчера я использовал TokenMatcher.js и Token.js для получения текста конкретного шага.

**Comment by 1C-Romania** [comment]
> Проблема с текстом на финальном кадре

единственное, что в нем не очень нравится - так это "PM"
но это - дело вкуса и не принципиально...

**Comment by Pr-Mex** [comment]
@1C-Romania PM получился видимо из-за того, что язык конфы был английский

**Comment by EvilBeaver** [comment]
А этот кадр вообще нужен? Ну т.е. в рекламных целях инструмента - безусловно. А на боевых сценариях у конечного пользователя может его выключать галочкой?

**Comment by Pr-Mex** [comment]
@EvilBeaver 
Понимаешь, тут точно должна выводится версия инструкции и когда она создана. Ибо они могут и будут меняться во времени.
Часть текста можно убрать конечно, но что-то надо будет оставить.

**Comment by Pr-Mex** [comment]
@1C-Romania 
В любом случае от вас нам понадобится фича на румынском. Для тестов.
Если у вас их нет, то за основу можно взять вот эту:
https://github.com/silverbulleters/vanessa-behavior/blob/develop/examples/features/AccountingSuite/PurchaseOrder.feature

**Comment by kuntashov** [comment]
Коллеги, ведь код языка указывается в начале фичи (`#language ru`), по умолчанию (если не указан) - en. Последний кадр формировать на основе файла-шаблона, который выбирать на основе языка фичи. 

Для проверки в коде создать структуру `КлючевыеСлова` с ключами `Scenario`, `Given`, `When` и т.п. и в зависимости от языка фичи "заряжать" их значениями из файла с "переводом" ключевиков на соответствующий язык.

В проверках, соответственно, использовать что-то в духе

```bsl
Если ТекущееКлючевоеСлово = КлючевыеСлова.Given Тогда
    /// ....
КонецЕсли;
```

**Comment by nixel2007** [comment]
@kuntashov я это и имел ввиду в сообщении выше)

**Comment by kuntashov** [comment]
@nixel2007 я про МассивТогда и т.п. не очень понял (кажется избыточным, сразу все переводы ключевика Тогда считывать), но да, перечитал - то же самое ). В общем и целом это самое очевидное решение :)

**Comment by nixel2007** [comment]
> кажется избыточным, сразу все переводы ключевика Тогда считывать

только по одному выбранному языку. просто геркин позволяет для одной и той же секции использовать несколько ключевых слов. например, для описания контекста - Дано и Допустим

**Comment by Pr-Mex** [comment]
> только по одному выбранному языку. просто геркин позволяет для одной и той же секции использовать несколько ключевых слов. например, для описания контекста - Дано и Допустим

там в реальности можно любые ключевые слова писать

**Comment by kuntashov** [comment]
@nixel2007 @Pr-Mex ок, понял

**Comment by nixel2007** [comment]
> там в реальности можно любые ключевые слова писать

Да. Но тем не менее какие-то из ключевых слов все равно надо парсить наверняка - например, функциональность, сценарий, контекст и т.д.

**Comment by Pr-Mex** [comment]
>Да. Но тем не менее какие-то из ключевых слов все равно надо парсить наверняка - например, функциональность, сценарий, контекст и т.д.

У меня так сейчас и сделано. Но кое-где нет универсальности.

**Comment by allustin** [comment]
Предлагаю подождать примерной фичи на румынском и тогда оценивать реализацию.

**Comment by pumbaEO** [comment]
Уже все давно готово добавляем свою таблицу переводов, определяем язык в файле  https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/vbFeatureReader/ObjectModule.bsl#L4112

**Comment by Pr-Mex** [comment]
@pumbaEO 
как я понял @nixel2007  предлагает парсить json.
Тогда не надо для каждого языка добавлять переводы.

**Comment by pumbaEO** [comment]
Там возможна ситуация, что разной длины слова может зависеть парсинг, т.к. самые короткие надо проверять самыми последними.

**Comment by Pr-Mex** [comment]
Не понял. Вроде не должно зависеть.

**Comment by nixel2007** [comment]
Там бывают конструкции из *двух* слов. Например Scenario Outline. Нужно сначала проверить шаг на Scenario Outline, а только потом на Scenario

**Comment by 1C-Romania** [comment]
> добавляем свою таблицу переводов

коллеги, так нам нужно перевести эти несколько ключевых слов на румынский?
нам подготовить вариант "Функция СоздатьТаблицуКлючевыхСлов_RO()" - ?
или вы возьмете эти переводы из "стандартного Геркина"?

**Comment by Pr-Mex** [comment]
@nixel2007 
теперь понял

**Comment by Pr-Mex** [comment]
@1C-Romania 
От вас нужна фича на румынском.

**Comment by nixel2007** [comment]
@Pr-Mex шаги кнопко-нажималки надо будет переводить отдельно, правильно понимаю?

**Comment by Pr-Mex** [comment]
@nixel2007 
Да. Надо будет добавлять опцию - на каком языке генерировать текст.

**Comment by allustin** [comment]
@Pr-Mex код библиотечных шагов только менять не надо - все равно у них все кодеры русские ;-).

То есть сделаем через

```
And Then I click the command button interface #enlish
I Тоді я натискаю кнопку командного інтерфейсу #ukraine
Și apoi am împinge interfața de comandă buton #romania
Un tad es spiediet pogu komandu interfeisu #latvia
```

будет вызывать старый код библиотеки

```
Ванесса.Шаг("Тогда я нажимаю кнопку командного интерфейса")
```

то есть это обертка будет

**Comment by Pr-Mex** [comment]
@allustin 
я так и делал английскую фичу.
Тут есть момент, что генератор фич из воздуха генерит текст только на русском.
Т.е. накликать фичу на английском сейчас нельзя.
Поэтому хорошо бы, чтобы генератор фич из воздуха тоже умел работать на нескольких языках.

**Comment by allustin** [comment]
@Pr-Mex тады нужно будет еще проверять с ключами сервера в режиме румынского MUI, по аналогии с английскими ключами. вообщем подождем фичу - тут есть куда копать.

о кстати @1C-Romania - вопрос, что там было со сцены сказано было что vanessa-behavior надо допиливать до чего-то ? это про этот запрос была речь ?

**Comment by 1C-Romania** [comment]
> нам понадобится фича на румынском. Для тестов

а вот тут есть вопрос: 
для "прокручивания" фичи на румынском - должна ли аппликация иметь интерфейс на румынском?

Accounting Suite, на котором "прокручивалась" фича на английском и был сгенерирован видео-док - румынского интерфейса не имеет...   8-(

**Comment by 1C-Romania** [comment]
> со сцены сказано было что vanessa-behavior надо допиливать до чего-то 

со сцены сказано было, что Vanessa-Behavior надо БЫЛО допиливать - она не была готова к работе с конфигурациями с английским кодом - я был не прав?

**Comment by Pr-Mex** [comment]
@1C-Romania 
Нам для тестов подойдёт любая фича. Интерфейс может быть любым.

**Comment by allustin** [comment]
@1C-Romania информация устарела... ;-)  везде полное BDD

Вам достаточно описать ожидаемую функциональность на румынском, ту которую вы хотите задокументировать.

**Comment by 1C-Romania** [comment]
> информация устарела... ;-) 

какая именно?  8-)

**Comment by 1C-Romania** [comment]
# encoding: utf-8
# language: ro

@tree

Feature: Cumparare produsului

Ca utilizator
vreau sa cumpar niste bunuri
To be happy with it

Background:
	Given TestClient este conectat

Scenario: Creare Comanda catre Furnizor
	Cand eu pornesc creare documentului
			Cand eu pornesc creare Comanda catre Furnizor
			Si eu indic furnizor Norcal Distribution Company
			
	Si eu adaug niste bunuri		
			Si eu adaug linia noua in comanda
			Si eu indic nomenclator "Coleman 600W Wind Turbine"
			Si eu indic cantitate 1
			Si eu indic data de livrare 30.10.2016
			
	Si eu termin documentul meu
			Si eu salvez Comanda
			Si eu listez Comanda

**Comment by 1C-Romania** [comment]
коллеги, feature-файл готов, но осталось несколько вопросов:
1) надо ли переводить @tree / Feature / Background / Scenario ?
2) что делать с "Given TestClient" ?

**Comment by nixel2007** [comment]
1. Ключевые слова определены в JSON из второго сообщения,  в секции с румынским языком. Можно свободно использовать их. 
2. Не понял вопроса. Given переводится, test client - Наверное на ваше усмотрение.

**Comment by nixel2007** [comment]
1. Тег @tree не является ключевым словом, поэтому... На русский мы его не переводим. Можно добавить перевод на румынский, если так будет удобнее

**Comment by Pr-Mex** [comment]
тег @tree надо оставить
это служебный тег

>надо ли переводить @tree / Feature / Background / Scenario ?

да, надо, кроме @tree 

Given TestClient тоже надо перевести

**Comment by 1C-Romania** [comment]
@nixel2007 + @Pr-Mex - большое спасибо, коллеги!
feature выше - отредактировал!
осталось только мне разобраться с markdown и отформатировать ее по-лучше...   8-(

**Comment by nixel2007** [comment]
заключите текст фичи в три обратных апострофа ``` - в начале и в конце.
будет отдельный блок
```
c всяким
разным
кодом
```

3 ноября 2016 г., 15:13 пользователь ALEXEI SNITKOVSKI <
notifications@github.com> написал:

**Comment by Pr-Mex** [comment]
@1C-Romania 
получилось?
вот так надо
![image](https://cloud.githubusercontent.com/assets/8627416/19982124/de5c0c78-a215-11e6-8524-12729cc9a226.png)

**Comment by 1C-Romania** [comment]
@nixel2007 + @Pr-Mex - большое спасибо за подсказки !
feature выше - отредактировал еще раз - стало красивее   8-)

**Comment by 1C-Romania** [comment]
коллеги, правильно ли я понимаю, что дело могло бы пойти веселее, если за него назначить вознаграждение? (мне говорили про какие-то "баунти")
какая сумма была бы адекватной данному вопросу?  (от feature-файлов на румынском до автоформирования видеодоков на нем же)
это нужно вносить кэшем или можно перечислить с карты VISA?

**Comment by Pr-Mex** [comment]
@1C-Romania 
Да, вознаграждение это хорошо.
Насчет формы оплаты через VISA - не могу сказать.
Может @allustin подскажет.

**Comment by EvilBeaver** [comment]
> какая сумма была бы адекватной данному вопросу?

Я хоть и не разработчик Vanessa-Behavior, но позволю себе вставить 5 копеек)
Сама идея bounty-hunt состоит в том, что именно заказчик назначает награду за свою хотелку. Как в вестернах: **Нужен живым или мертвым за $100500** И все горячие головы в округе (читай, вольные программисты) слетаются и делают за награду. Мало пообещали - никто не слетелся.

Как-то так это работает. А если вы спрашиваете "какая сумма адекватная" - то это уже договорные отношения, а не bounty.

**Comment by allustin** [comment]
@EvilBeaver точно. 

@1C-Romania bounty - это децентрализованный баланс между алчностью разработчика и жадностью заказчика

какую назначите - такую коллеги и возьмут (если возьмут)
в gitter наша переписка транслируется - поэтому алчные контрибьюторы отрефлексируют обязательно.

**Comment by allustin** [comment]
так как награды не поступило - задачу закрываю

**Comment by Pr-Mex** [comment]
Задача получения фич и видео на румынском со стороны VB - решена. Осталось доделать перевод шагов. Но это уже к @1C-Romania 

По парсингу i18n - есть отдельная задача - #434.

Эту задачу закрываю.

**Comment by leemuar** [comment]
> Задача получения фич и видео на румынском со стороны VB - решена

@Pr-Mex какой коммит это решил? Никак не могу найти

**Comment by Pr-Mex** [comment]
@leemuar 
Была добавлена прямая поддержка румынского языка. А также ещё пары языков.
Коммит сейчас сходу не найду.
