### ISSUE TITLE
Невозможно выполнить сценарий в транзакции

### ISSUE THREAD

**Issue by rozhkovdmitriy** [silverbulleters/vanessa-behavior#428]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Тестирование посредством Vanessa Behaviour 1.044
   Как разработчик собственного функционала
   Я хочу чтобы сценарий проходил в транзакции
   И чтобы в issue осталась запись о подходе к выполнению в сценария в транзакции


Контекст:
  Дано: 1.044
  И 8.3.5.1460
  и УАТ

Сценарий: Создание теста с транзакцией
  Допустим: В процедуре ПередНачаломСценария() делается серверный вызов с установкой транзакции и дополнительной проверкой начала транзакции "тут же"
  Когда: в реализуется произвольное поведение бизнеса
  Тогда: транзакция активна

```

> Прикладывайте файлы скриншотов
```

Процедура НачалоСессииТестирования()
	Если ТранзакцияАктивна() Тогда
		Сообщить("Существует активная транзакция закрываем, начинаем свою!!!");
		ОтменитьТранзакцию();
	КонецЕсли;
	НачатьТранзакцию();
	
	Если ТранзакцияАктивна() = Ложь Тогда
		ВызватьИсключение "НачалоСессииТестирования: поиск активной транзакции не выявил результатов";
	КонецЕсли;

КонецПроцедуры
```
```
//Тогда транзакция сессии тестирования активна
//@ТранзакцияСессииТестированияАктивна()
Процедура ТранзакцияСессииТестированияАктивна() Экспорт
	Если ТранзакцияАктивна() = Ложь Тогда
		ВызватьИсключение "Поиск активной транзакции не выявил результатов";
	КонецЕсли;
КонецПроцедуры
```
![vanessa-behavior-check-transaction](https://cloud.githubusercontent.com/assets/801971/20037896/8d3ab1a4-a44b-11e6-9ef9-d62a2a21645d.png)

**Comment by rozhkovdmitriy** [comment]
При том, что vanessa behavior как бы молча завершает транзакцию в 

```
Процедура ДействияПослеЗавершенияСценария(СтрокаСценария,БылаОшибка = Ложь,ОписаниеОшибки = Неопределено)
	ВызватьМетодСценарияЕслиОнЕсть(СтрокаСценария, "ПередОкончаниемСценария",,БылаОшибка,ОписаниеОшибки);
	
	Пока ТранзакцияАктивна() Цикл
		Сообщить("Vanessa behavior отменяет мою транзакцию!!!");
		ОтменитьТранзакцию();
	КонецЦикла;
КонецПроцедуры
```
Но до этого и не доходит, транзакция убита не в коде vanessa behavior

**Comment by nixel2007** [comment]
Шаги VB выполняются на клиенте. Транзакция живёт только в рамках одного серверного вызова. Ваш сценарий работы невозможен.

**Comment by nixel2007** [comment]
Как обычно главный вопрос - зачем?

**Comment by rozhkovdmitriy** [comment]
1. Работаю над созданием документа
1. Пишу тест, входные тестовые данные (загрузка из макета, прогон клиентского сценария), наполнение документа, проверка движений
1. Тест прогоняется N раз до завершения разработки программируемой сущности
1. Тест должен каждый прибираться за собой, иначе в базе будет создано большое количество мусорных записей
1. Существующий подход не приемлет содержания мусорных записей после выполнения отдельного сценария, группы сценариев, это и есть противоречие

Спасибо, за информацию по транзакции!

**Comment by nixel2007** [comment]
@naasb а вы удаление данных по макету реализовали в итоге?

**Comment by nixel2007** [comment]
@rozhkovdmitriy данные можно удалять после прогона сценария. Однако сразу предупреждаю, что такой подход ведёт к резкому увеличению общего времени прогона фич на CI. 

Идеальной ситуацией является реинициализация базы перед общим прогоном фич.

**Comment by rozhkovdmitriy** [comment]
Прекрасно, спасибо :)

**Comment by Pr-Mex** [comment]
@rozhkovdmitriy 
Плюс шаги в VB выполняются асинхронно. Транзакция в 1С так жить не может.
@nixel2007 говорит правильно.
После каждого прогона фич (а точнее в начале джоба) база, в которой запускаются сценарии на CI, должна обнуляться.  Поэтому на CI такой проблемы быть не должно. 
При локальной работе лучше использовать независимые сценарии.  Т.е. сценарий сам обеспечивает окружение для своей работы.
