### ISSUE TITLE
Дать обратную связь по идее использования BDD на обычных формах

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#430]
Подход [отсюда](http://infostart.ru/public/419003/). Реализация _(пока)_ такая:

**фича**

```
Функциональность: Заказ покупателя
    Как менеджер по продажам
    Хочу документ заказ покупателя
    Чтобы обеспечивать клиента товарами

Сценарий: Заказ
    Когда я открываю форму документа "ЗаказПокупателя"
    И я в открытой форме документа в реквизит с именем "Дата" устанавливаю значение 01.11.2016
    И я в открытой форме документа нажимаю на кнопку с именем "ЗаписатьДокумент"  
```

**обработка соответствующая фиче**

```
Функция НайтиКнопкуПоИмени(ИмяКнопки)
	Результат = Неопределено;
	
	ЭлементыПроверяемойФормы = Контекст.ПроверяемаяФорма.ЭлементыФормы;
	Для Каждого ЭлементПроверяемойФормы Из ЭлементыПроверяемойФормы Цикл
		Если ТипЗнч(ЭлементПроверяемойФормы) = Тип("КоманднаяПанель") Тогда
			ИскомаяКнопка = ЭлементПроверяемойФормы.Кнопки.Найти(ИмяКнопки);
			Если Не ИскомаяКнопка = Неопределено Тогда
				Результат = ИскомаяКнопка;

				Прервать;
			КонецЕсли;
		КонецЕсли;
	КонецЦикла;

	Возврат Результат;
КонецФункции

Процедура НажатьНаКнопку(Кнопка)
	ПредставлениеМетода = "" + Строка(Кнопка.Действие) + "(Неопределено)";

	Контекст.ПроверяемаяФорма.ВыполнитьМетодФормы(ПредставлениеМетода);
КонецПроцедуры

//Когда я открываю форму документа "ЗаказПокупателя"
//@ЯОткрываюФормуДокумента(Парам01)
Процедура ЯОткрываюФормуДокумента(ИмяДокумента) Экспорт
	ОткрываемаяФорма = Документы[ИмяДокумента].ПолучитьФорму("ФормаДокумента");
	
	ОткрываемаяФорма.Открыть();
	
	Пауза(3);
	
	Если ОткрываемаяФорма.Открыта() Тогда
		Контекст.Вставить("ПроверяемаяФорма", ОткрываемаяФорма);
	Иначе
		ВызватьИсключение "Не открылась форма документа";
	КонецЕсли;
КонецПроцедуры

//И я в открытой форме документа в реквизит с именем "" устанавливаю значение ""
//@ЯВОткрытойФормеДокументаВРеквизитСИменемУстанавливаюЗначение(Парам01,Парам02)
Процедура ЯВОткрытойФормеДокументаВРеквизитСИменемУстанавливаюЗначение(ИмяРеквизита, НовоеЗначение) Экспорт
	Контекст.ПроверяемаяФорма.УстановитьСвойствоФормы(ИмяРеквизита, НовоеЗначение);
КонецПроцедуры

//И я в открытой форме документа нажимаю на кнопку с именем "Записать"
//@ЯВОткрытойФормеДокументаНажимаюНаКнопкуСИменем(Парам01)
Процедура ЯВОткрытойФормеДокументаНажимаюНаКнопкуСИменем(ИмяКнопки) Экспорт
	ИскомаяКнопка = НайтиКнопкуПоИмени(ИмяКнопки);
	Если Не ИскомаяКнопка = Неопределено Тогда
		НажатьНаКнопку(ИскомаяКнопка);
		
	КонецЕсли;
КонецПроцедуры
```

**дополнение модуля формы документа**

```
Процедура УстановитьСвойствоФормы(ИмяСвойства, Значение) Экспорт
	Выполнить("ЭтотОбъект[ИмяСвойства] = Значение");
КонецПроцедуры

Процедура ВыполнитьМетодФормы(ПредставлениеМетода) Экспорт
	Выполнить(ПредставлениеМетода);
КонецПроцедуры
```

Жду комментари (подходит/нет, вопросы) тех кто хотел бы или уже использует BDD для обычных форм, а так же экспертов. Думаю тема перспективная.

**Comment by Pr-Mex** [comment]
@snov1kov 
прокомментируешь?

**Comment by maxstarkov** [comment]
Использовал аналогичный подход для xUnit в обычных формах. Правда добавлял реквизиты формы в которые программно при тестах устанавливал значения.
Реквизиты были такими:

`IT_ЮнитТест` (тип булево) - устанавливал в значение Истина, когда выполнялись тесты. Делал это для того, чтобы можно было, например, отказаться от модального окна ввода числа (ага, использовалось `ВвестиЧисло()`) и программно установить значение.
`IT_ЮнитТестПараметры` - инициализировал структурой в которой мог хранить произвольные значения при выполнении тестирования. Например, значение для эмуляции ввода в `ВвестиЧисло()`.

В модуле формы размещал экспортный метод `IT_ЮнитТест(ИмяМетодаДляВыполнения, СтруктураПараметров)`. Вызовом этого метода управлял поведением формы.

В итоге, получались такие тесты:

`ФормаОбработкиРегистратура = Обработки.АРМ_Регистратура_V1.ПолучитьФорму("Форма");
	
	// Проверка наличия реквизита формы с именем IT_ЮнитТест (проверка через заполненность).
	ЕстьРеквизитIT_ЮнитТест = ПроверитьСуществованиеРеквизитаФормы(ФормаОбработкиРегистратура, "IT_ЮнитТест");
	ЮТест.ПроверитьИстину(ЕстьРеквизитIT_ЮнитТест , "Для формы обработки Регистратура не найден реквизит IT_ЮнитТест.");
	
	// Проверка наличия реквизита формы с именем IT_ЮнитТестПараметры (проверка через заполненность).
	ЕстьРеквизитIT_ЮнитТестПараметры = ПроверитьСуществованиеРеквизитаФормы(ФормаОбработкиРегистратура, "IT_ЮнитТестПараметры");
	ЮТест.ПроверитьИстину(ЕстьРеквизитIT_ЮнитТестПараметры, "Для формы обработки Регистратура не найден реквизит IT_ЮнитТестПараметры.");
	
	// Установка параметра формы для определения выполнения процедур тестирования.
	ФормаОбработкиРегистратура.IT_ЮнитТест = Истина;
	
	// Инициализация параметра формы для определения условий выполнения процедур тестирования.
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры = Новый Структура;
	
	// Тест выполняется на текущую дату.
	ФормаОбработкиРегистратура.ЭлементыФормы.НаДату.Значение = ТекущаяДата();
	
	// Получение информации о расписании специалистов.
	СтруктураПараметров = Новый Структура;
	СтруктураПараметров.Вставить("пНаДату", ФормаОбработкиРегистратура.ЭлементыФормы.НаДату.Значение);
	ФормаОбработкиРегистратура.IT_ЮнитТест("ОбновитьТаблицу", СтруктураПараметров);
	
	// Проверка наличия данных о расписании специалистов в обработке.
	КоличествоСтраниц = ФормаОбработкиРегистратура.ЭлементыФормы.Панель1.Страницы.Количество();
	КоличествоСтрок = ФормаОбработкиРегистратура.ТЗ.Количество();
	
	ЮТест.ПроверитьБольше(КоличествоСтраниц, 0, "Нет страниц в панели формы обработки Регистратура.");
	ЮТест.ПроверитьБольше(КоличествоСтрок, 0, "Нет строк для отображения данных в форме Регистратура.");
	
	// Инициализация координат для получения поля сетки расписания специалистов.
	НомерСтрокиСеткиРасписания = 10; // Число представляет номер 15 минутного интервала в сетке расписания.
	НомерКолонкиСеткиРасписания = 3; // Первые две колонки служебные, нужно указывать число больше 1 (нумерация с нуля).
	
	// Получение координат для пустой ячейки сетки расписания.
	ПолучитьКоординатыПустойЯчейкиТаблицыСеткиРасписания(ФормаОбработкиРегистратура, НомерСтрокиСеткиРасписания, НомерКолонкиСеткиРасписания);
	
	// Получение поля сетки расписания по координатам.
	УстановитьТекущиеДанныеТабличногоПоля(ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1, ФормаОбработкиРегистратура.ТЗ[НомерСтрокиСеткиРасписания], ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.Колонки[НомерКолонкиСеткиРасписания]);
	
	// Проверка создания брони на выбранную координату сетки (создание документа Бронь).
	СтруктураПараметров.Очистить();
	СтруктураПараметров.Вставить("Кнопка", ФормаОбработкиРегистратура.ЭлементыФормы.КоманднаяПанель1.Кнопки.Бронь);
	ФормаОбработкиРегистратура.IT_ЮнитТест("КоманднаяПанель1Бронь", СтруктураПараметров);
	
	// Получение поля сетки расписания по координатам.
	УстановитьТекущиеДанныеТабличногоПоля(ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1, ФормаОбработкиРегистратура.ТЗ[НомерСтрокиСеткиРасписания], ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.Колонки[НомерКолонкиСеткиРасписания]);
	
	// Проверка отмены брони на выбранную координату сетки (создание документа отмена Брони).
	СтруктураПараметров.Очистить();
	СтруктураПараметров.Вставить("Кнопка", ФормаОбработкиРегистратура.ЭлементыФормы.КоманднаяПанель1.Кнопки.СнятьБронь);
	ФормаОбработкиРегистратура.IT_ЮнитТест("КоманднаяПанель1СнятьБронь", СтруктураПараметров);
	
	// Получение поля сетки расписания по координатам.
	УстановитьТекущиеДанныеТабличногоПоля(ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1, ФормаОбработкиРегистратура.ТЗ[НомерСтрокиСеткиРасписания], ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.Колонки[НомерКолонкиСеткиРасписания]);
	
	// Установка параметра формы для определения условий выполнения процедур тестирования.
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры.Очистить();
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры.Вставить("ВидПриемаДляТестирования", Новый Структура("Значение", Справочники.ВидыПриемов.ПервичныйПрием));
	
	// Проверка ввода записи на прием.
	СтруктураПараметров.Очистить();
	СтруктураПараметров.Вставить("Элемент", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1);
	СтруктураПараметров.Вставить("ВыбраннаяСтрока", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.ТекущаяСтрока);
	СтруктураПараметров.Вставить("Колонка", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.ТекущаяКолонка);
	СтруктураПараметров.Вставить("СтандартнаяОбработка", Истина);
	ФормаОбработкиРегистратура.IT_ЮнитТест("ТабличноеПолеВыбор", СтруктураПараметров);
	
	// Эмуляция паузы.
	Пауза(5);
	
	// Получение поля сетки расписания по координатам.
	УстановитьТекущиеДанныеТабличногоПоля(ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1, ФормаОбработкиРегистратура.ТЗ[НомерСтрокиСеткиРасписания], ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.Колонки[НомерКолонкиСеткиРасписания]);
	
	// Проверка установки отметки посещения для записи на прием.
	СтруктураПараметров.Очистить();
	СтруктураПараметров.Вставить("Кнопка", ФормаОбработкиРегистратура.ЭлементыФормы.КоманднаяПанель1.Кнопки.Отметка);
	ФормаОбработкиРегистратура.IT_ЮнитТест("КоманднаяПанель1Отметка", СтруктураПараметров);
	
	// Эмуляция паузы.
	Пауза(5);
	
	// Установка параметра формы для определения условий выполнения процедур тестирования.
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры.Очистить();
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры.Вставить("ДействиеЗаписьНаПрием", Новый Структура("Значение", "Просмотр"));
	
	// Получение поля сетки расписания по координатам.
	УстановитьТекущиеДанныеТабличногоПоля(ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1, ФормаОбработкиРегистратура.ТЗ[НомерСтрокиСеткиРасписания], ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.Колонки[НомерКолонкиСеткиРасписания]);
	
	// Проверка просмотра записи на прием.
	СтруктураПараметров.Очистить();
	СтруктураПараметров.Вставить("Элемент", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1);
	СтруктураПараметров.Вставить("ВыбраннаяСтрока", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.ТекущаяСтрока);
	СтруктураПараметров.Вставить("Колонка", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.ТекущаяКолонка);
	СтруктураПараметров.Вставить("СтандартнаяОбработка", Истина);
	ФормаОбработкиРегистратура.IT_ЮнитТест("ТабличноеПолеВыбор", СтруктураПараметров);
	
	// Эмуляция паузы.
	Пауза(5);
	
	// Установка параметра формы для определения условий выполнения процедур тестирования.
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры.Очистить();
	ФормаОбработкиРегистратура.IT_ЮнитТестПараметры.Вставить("ДействиеЗаписьНаПрием", Новый Структура("Значение", "Отменить запись"));
	
	// Получение поля сетки расписания по координатам.
	УстановитьТекущиеДанныеТабличногоПоля(ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1, ФормаОбработкиРегистратура.ТЗ[НомерСтрокиСеткиРасписания], ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.Колонки[НомерКолонкиСеткиРасписания]);
	
	// Проверка ввода отмены записи на прием.
	СтруктураПараметров.Очистить();
	СтруктураПараметров.Вставить("Элемент", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1);
	СтруктураПараметров.Вставить("ВыбраннаяСтрока", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.ТекущаяСтрока);
	СтруктураПараметров.Вставить("Колонка", ФормаОбработкиРегистратура.ЭлементыФормы.ТабличноеПоле1.ТекущаяКолонка);
	СтруктураПараметров.Вставить("СтандартнаяОбработка", Истина);
	ФормаОбработкиРегистратура.IT_ЮнитТест("ТабличноеПолеВыбор", СтруктураПараметров);
	
	// Открытие формы обработки.
	ФормаОбработкиРегистратура.Открыть();`

**Comment by snov1kov** [comment]
В принципе идея нравится, надо только доп проверку, чтобы злоумышленники произвольный код не смогли выполнять на продуктивных базах через "Выполнить"

**Comment by Pr-Mex** [comment]
Закрываю. Если вопрос всё ещё не решен - пишите в эту тему.
