### ISSUE TITLE
Сделать чтобы видеоинструкция формировалась на языке фичи

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#435]
Сейчас часть слов, например "Сценарий", будет формироваться на русском. Это происходит в тех моментах, где идёт видеобрейк.
Надо сделать чтобы видеобрейки соответствовали языку фичи.

Также надо сделать, чтобы финальный скрин заполнялся либо на русском для русских фич, либо на английском для всех остальных.

**Comment by 1C-Romania** [comment]
готов назначить вознаграждение в размере $50 - куда занести?

**Comment by allustin** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=39173249)](https://www.bountysource.com/issues/39173249-?utm_source=39173249&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Pr-Mex** [comment]
Решено.
