### ISSUE TITLE
Надо сделать, чтобы на финальном скрине видеоинструкии отображалась версия инструкции.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#436]
Сейчас нельзя задать версию инструкции.
Предлагаю для этого использовать тэг @Version
Пример:

```Gherkin
@Version 1.00

Функциональность: Что-то надо сделать
...

```

Так соблюдается синтаксис Gherkin и можно указывать произвольные версии.

**Comment by allustin** [comment]
@Pr-Mex ты имеешь ввиду - версию движка ? А не параметр ли это JSON при запуске ?

**Comment by allustin** [comment]
@Pr-Mex - это же `git tag -v`

то есть версия инструкциии - это тупо тэг в git и вообще версия проекта. Не надо в feature это добавлять

**Comment by Pr-Mex** [comment]
@allustin 
я именно про версию конкретной инструкции

@theshadowco, поправь меня если я не правильно понял проблему

А проблема такая:
У нас сотни метаданных, процессов и т.д.
И у нас сотни инструкций.
И когда нам обращается пользователь и говорит, что "вот, я делаю всё по вашей видеоинструкции, но кнопки такой на форме нет". 
И нам как-то надо понять - а какую версию инструкции он сейчас смотрит.

И вот для этого предлагается в само видео встроить версию данной инструкции, т.е. данной фичи.

**Comment by nixel2007** [comment]
Версия инструкции - sha коммита (первые 7-8 символов, которые гит считает обычно уникальными)

**Comment by Pr-Mex** [comment]
@nixel2007 
да, думал об этом

Тут есть пара минусов:
1. Не особо читаемая версия.
2. Фича может и не лежать в гите и любой другой VCS. И из неё тоже можно сделать инструкцию.

**Comment by allustin** [comment]
блин - ну есть же параметр tag в любой CVS.

Не надо это в фичи - фичи это код, это как версию в коде менять постоянно.

обычно делают так https://git-scm.com/book/en/v2/Git-Basics-Tagging, то же саоме для Perforce, SVN, hg и т.д.

**Comment by allustin** [comment]
@Pr-Mex 

не особо читаемая версия - это проблема тэгирования, обычно делают 

для стабильной ветки, для последней разработческой tag+sha+datetime

P.S. Не надо ее пихать в инструкцию, очень прошу - фигня получится

**Comment by theshadowco** [comment]
@Pr-Mex
Спасибо, что не забыл.

Предложения по именованию:
 - Для релиза: при сборке релиза, определять изменившиеся фичи и для них формировать новый набор видео, ну а версия видео - ИмяФичи (или сценарий)  + релиз + DateTime. 
- Для локальной версии (без scm): просто создем видео с версией ИмяФичи (или сценарий) + DateTime.

**Comment by Pr-Mex** [comment]
@theshadowco 
то что ты описываешь - должны делать скрипты на CI.
Их надо написать.

**Comment by theshadowco** [comment]
Да, именно так.

**Comment by Pr-Mex** [comment]
Тогда закрываю.
Итого - версию надо делать скриптами.

**Comment by theshadowco** [comment]
Да, так вернее

17 нояб. 2016 г. 23:21 пользователь "Pautov Leonid" <
notifications@github.com> написал:
