### ISSUE TITLE
ТаблицаСписок.ПерейтиКСтроке(ОписаниеСтроки, Вычислить("НаправлениеПереходаКСтроке.Вниз")); всегда возвращает Истина

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#443]
```Gherkin
Контекст:
  Дано: 1.052
  И 8.3.9.1850
  и 1С: Управление Торговлей ред. 10.3
```

ТаблицаСписок.ПерейтиКСтроке(ОписаниеСтроки, Вычислить("НаправлениеПереходаКСтроке.Вниз"));

всегда возвращает Истина, даже если переход к строке не произошел.
У кого-нибудь есть такое поведение?

**Comment by Pr-Mex** [comment]
У меня на CI на 8.3.9 как раз одна фича падает при переходе строки вниз. Пока не разобрался что к чему.

**Comment by Pr-Mex** [comment]
@viskvortsov 
можете проверить на 8.3.8?

**Comment by viskvortsov** [comment]
Вот и у меня странности.
Пока дошел до следующего:
Когда было вот так:
```
И     		В форме "Волшебный_look (Looks (Ваш KPI)) *" в таблице "Состав" я перехожу к строке:
| 'Номенклатура' 	| 'Основной' 	|'Дополнительный'	|
| 'Блузка' 		| Да                  |Нет				|
```
тогда падало.
Потом сделал так:
```
И     		В форме "Волшебный_look (Looks (Ваш KPI)) *" в таблице "Состав" я перехожу к строке:
| 'Номенклатура' 	| 
| 'Блузка' 		|
```
и стало наоборот всегда выполняться

**Comment by viskvortsov** [comment]
@Pr-Mex сейчас попробую

**Comment by viskvortsov** [comment]
@Pr-Mex на 8.3.8 поведение верное.

**Comment by Pr-Mex** [comment]
@viskvortsov 
Похоже на баг платформы.
Можете его оформить и отправить на v8@1c.ru?

**Comment by viskvortsov** [comment]
Хорошо, сделаю

**Comment by Pr-Mex** [comment]
Я посмотрел. Они сломали переход, когда в ТЧ есть реквизит типа Булево.

**Comment by Pr-Mex** [comment]
Написал в 1С.
Пока ответ такой:
>Здравствуйте!
>Ваше обращение зарегистрировано под номером SW1097927 / 1.
>Пожалуйста, в тексте следующих обращений на эту же тему ссылайтесь на этот номер.
>Ваше сообщение зарегистрировано для расследования 10171059

**Comment by Pr-Mex** [comment]
Суппорт ответил, что в 1С:Предприятие 8.3 (8.3.9.2005) и выше  ошибки нет. В общем, исправлено в будущих версиях платформы. 
Сейчас уже доступен 8.3.9.2016
https://releases.1c.ru/version_files?nick=Platform83&ver=8.3.9.2016
