### ISSUE TITLE
Не находит кнопку вопроса в шаге

### ISSUE THREAD

**Issue by ruimage** [silverbulleters/vanessa-behavior#457]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Работающий шаг "Я нажимаю на кнопку" в программно созданном вопросе
   Как разработчик
   Я хочу что бы при воспроизведении шагов на тестовом клиенте VB находила кнопки вопроса

Контекст: 
  Дано: VB коммит 2470a597786ab697535027128ca9b15a3ae145e5
  И 8.3.8.1675


Сценарий: VB обрабатывает шаг "я нажимаю на кнопку" для кнопки вопроса 
  Допустим: Описан шаг 'Когда открылось окно "Изделия на ТО"	Тогда я нажимаю на кнопку "Отправлено"'
  Когда: Вызывается обработка вызова "e:\localgit\vanessa\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf"
  Тогда: Выводится сообщение об ошибке "Кнопка с заголовком <Доступно> не найдена!"

```
![default](https://cloud.githubusercontent.com/assets/15168946/20617627/885eb7f2-b2fb-11e6-8a8e-f0734f550c91.png)

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
@ruimage 
Привет!
А можешь показать что в этот момент происходит на TestClient?

**Comment by ruimage** [comment]
См. прилагаемый скриншот.
По сути остается окно вопроса и.... все падает.
На название кнопки не обращай внимания, это я откатился на старый сценарий и старую версия ванессы. 
![2](https://cloud.githubusercontent.com/assets/15168946/20619008/1b762938-b303-11e6-8a80-03065e0989a0.png)

**Comment by Pr-Mex** [comment]
А можешь проверить - в режиме Taxi, тоже ошибка возникнет?

**Comment by ruimage** [comment]
Такси тоже падает с ошибкой

**Comment by Pr-Mex** [comment]
Решено в 1.056. Проверьте.

**Comment by ruimage** [comment]
Все работает. ОК.
