### ISSUE TITLE
Заменить слово "Затем" в feature файлах на ключевое слово

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#459]
Ключевые слова определены в [gherkin-languages.json](https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json) и слова "Затем" в этом файле сейчас нет. Прошу заменить "Затем" на ключевое слово из файла, т.к. из-за этого не работает [gherkin-autocomplete](https://github.com/silverbulleters/gherkin-autocomplete).

**Comment by Pr-Mex** [comment]
@alehinsasha 
ты про какие фичи говоришь? про фичи VB?

**Comment by nixel2007** [comment]
угу. https://github.com/silverbulleters/vanessa-behavior/search?l=Cucumber&q=%D0%97%D0%B0%D1%82%D0%B5%D0%BC&utf8=%E2%9C%93

**Comment by nixel2007** [comment]
И из парсера тоже убрать заодно. А то мы конфликтуем с официальным геркиным

**Comment by Pr-Mex** [comment]
В парсере VB нет слова "Затем".
Просто VB по-другому смотрит на фичи с тегом @tree.

Для совместимости - заменю на что-то другое.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by artbear** [comment]
Проблема возникла вновь :(
