### ISSUE TITLE
Снипеты с одинаковыми именами

### ISSUE THREAD

**Issue by Tushkan** [silverbulleters/vanessa-behavior#468]
Снипет "явыполняюшагспараметром" встречается 2 раз!
\vanessa-behavior\features\Core\FeatureReader\step_definitions\ПроверкаПередачиПараметров.epf
\vanessa-behavior\features\Support\Templates\step_definitions\ФичаДляПроверкиОтчетаjUnit.epf

**Comment by Pr-Mex** [comment]
Привет!
Да, вчера случайно задублировал.
Исправлю.
