### ISSUE TITLE
Выполнение команд системы в Unicode

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-behavior#479]
На текущий момент есть проблемы с выполнением команд системы, если команда содержит не ASCII символы.
Имеется:
windows 7
кодовая страница по умолчанию в шелле CP866.

При прогоне тестов VB (tools\2 CheckBehavior.cmd) падает на открытии текстовых файлов, которые должны получаться в результате перенаправления вывода команд системы.
Это происходит в Функция ПолучитьМассивЗанятыхПортов() управляемой формы,
в Функция ПреобразоватьПутьСТочкамиКНормальномуПути() обычной формы,
в Функция ПреобразоватьПутьСТочкамиКНормальномуПути() управляемой формы вспомогательной обработки "tools\epf\init.epf"

Т.е. bat или cmd выполняется системой в данном случае с кодировкой CP866, но текст bat/cmd не в CP866. В результате перекодировки текста перенаправление не срабатывает.

Нужно добиться гарантированного выполнения команды, если ее текст содержит Unicode (не только кириллицу, но и другие языки).

**Comment by 1cgh** [comment]
@Pr-Mex не закрывай пока, я все использования старой функции на новую заменю, сделаю еще pr.

**Comment by Pr-Mex** [comment]
@1cgh 
ОК.
