### ISSUE TITLE
VB не видит изменения в табдоке

### ISSUE THREAD

**Issue by git22ura** [silverbulleters/vanessa-behavior#485]
[Video_2016-12-28_105344.zip](https://github.com/silverbulleters/vanessa-behavior/files/675221/Video_2016-12-28_105344.zip)

Если получать состояние формы "начисто" - все отлично. Если запомнить состояние формы и далее что-то на табдоке изменить, то при клике на "Получить изменения формы" изменений в табдоке не будет.
Иллюстрация в видео

**Comment by Pr-Mex** [comment]
@git22ura 
Понятно.
Видимо табличные документы не сравниваются.
Спасибо за информацию!

**Comment by Pr-Mex** [comment]
@git22ura 
А можешь проверить на текущей версии VB эту проблему?
https://github.com/silverbulleters/vanessa-behavior/issues/395

**Comment by git22ura** [comment]
@Pr-Mex 
закрыл ее

**Comment by crabzzy** [comment]
Леонид, Юрий, добрый день,
у меня в версии 1.074 Behaviour та же беда.

Отдебажил - нужно в модуле УправляемаяФорма строка 9593 
исправить

`ИначеЕсли Ключ = "ТабДок" Тогда
				
				Если Было <> Неопределено Тогда //!!Исправлено с = Неопределено на неравенство
					СтрТабДок = ПолучитьСтрокуТабличныйДокументФормаTestClient(ЭлемСтало[Ключ]);`

**Comment by Pr-Mex** [comment]
Исправления оказались неверными.
При новом варианте кода попадало несколько сценариев
http://ci.silverbulleters.org/job/Vanessa-Behavior-Develop/656/allure/#/behaviors

**Comment by Pr-Mex** [comment]
Теперь должно работать всегда.
