### ISSUE TITLE
Если Ванесса - фича плейер, то ей не хватает кнопки паузы

### ISSUE THREAD

**Issue by snov1kov** [silverbulleters/vanessa-behavior#486]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Кнопка паузы
   Как Разработчик
   Я хочу Поставить проигрывание сценариев на паузу

Контекст:
  Дано: VB 1-0-71
  И 8-3-9-xxx
  и УТ11

Сценарий: Преостановка проигрывания фич
  Допустим: Я открыл Ванессу и запустил проверку сценария
  Когда: Нажал на кнопку Пауза
  Тогда: Шаги перестали воспроизводится

```

> Прикладывайте файлы скриншотов

**Comment by Pr-Mex** [comment]
Принято.

**Comment by Pr-Mex** [comment]
Сделано.
Также  сделаны доработки позволяющие упростить отладку шагов.
Они доступны в контекстном меню.

**Comment by Pr-Mex** [comment]
@snov1kov 
Получилось проверить?

**Comment by snov1kov** [comment]
В обычной форме не паузы
![image](https://cloud.githubusercontent.com/assets/19814854/21836385/e7369c8c-d7d5-11e6-9270-7831e4dd3990.png)
в УФ работает не так, как ожидал, после нажатия STOP происходит полная остановка, после чего выполнить сценарии запускает выполнение шагов с начала, а не с шага, на котором нажимали "паузу"

**Comment by snov1kov** [comment]
@Pr-Mex посмотри, плиз, мой коммент выше...

**Comment by Pr-Mex** [comment]
>в УФ работает не так, как ожидал, после нажатия STOP происходит полная остановка, после чего >выполнить сценарии запускает выполнение шагов с начала, а не с шага, на котором нажимали >"паузу"

Там есть опция продолжить с данного шага.

**Comment by Pr-Mex** [comment]
![image](https://cloud.githubusercontent.com/assets/8627416/21843245/540b64a8-d7fb-11e6-9f4a-3fe4ae83526e.png)
