### ISSUE TITLE
Автоматический запуск выполнения сценариев с сохраненными ранее настройками

### ISSUE THREAD

**Issue by PiskunovSS** [silverbulleters/vanessa-behavior#490]
Функционал: автоматический запуск выполнения сценариев с сохраненными ранее настройками
   Как разработчик
   Я хочу запускать выполнения сценариев при указании параметра StartFeaturePlayer без использования файла с настройками
   Чтобы использовать автозапуск фич при отладке из конфигуратора

Контекст:
  Когда я в запускаю 1С Предприятие
  И в Предприятии я открываю обработку "vanessa-behavior.epf"
  И я загружаю одну фичу
  И я сохраняю текущие настройки
  И Я закрываю Vanessa Behavior
  И я закрываю предприятие
Сценарий: Автоматический запуск выполнения сценариев с настройками сохраненными ранее настройками
   Допустим В параметрах запуска ИБ я указываю строку "ENTERPRISE  /FD:\DB\VB" /TESTMANAGER  /EXECUTE D:\repo\vanessa-behavior\vanessa-behavior.epf  /CStartFeaturePlayer"
  Когда я запускаю предприятие
  Тогда при запуске открывается окно VB
  и загружаются последние ранее сохраненные настройки VB в этой базе
  и происходит выполнение сценариев

ИЛИ

Функционал: сохранение текущих настроек в файл FSON
   Как разработчик
   Я хочу сохранять настройки сделанные интерактивно в файл JSON
   Чтобы не писать этот файл вручную

Сценарий: 
  Когда я запускаю 1С Предприятие
  И в Предприятии я открываю обработку "vanessa-behavior.epf"
  Тогда открылось окно "ver 1.074: Vanessa Behavior"
  И я загружаю одну фичу
  И изменяю какие-либо настройки
  И я сохраняю текущие настройки в файл "D:\repo\vanessa-behavior\tools\JSON\VBParams838UF.json"
  И файл "D:\repo\vanessa-behavior\tools\JSON\VBParams838UF.json" можно использовать в параметрах запуска Vanessa Behavior

**Comment by PiskunovSS** [comment]
Задача стоит реализовать удобный и быстрый запуск отладки при помощи VB. Для удобства сделал обработку (готов поделиться), которую прописываю в автозапуск в параметрах ИБ. Из конфигуратора настроен запуск клиента тестирования, поэтому при нажатии F5 клиент тестирования сразу подключается к отладчику. В клиенте тестирования сразу запускается внешняя обработка, которая запускает менеджер тестирования и в нем Ванессу. Соответственно при запуске Ванессы загружаются сохраненные ранее настройки с нужной фичей для отладки разрабатываемого функционала. Остается только нажать кнопку Выполнить сценарии. Нашел параметры в Ванессе "StartFeaturePlayer;VBParams". Хотел сделать, чтобы сразу после запуска Ванессы автоматом запускался сценарий, но StartFeaturePlayer без указания пути к настройкам в параметре VBParams не работает.

**Comment by PiskunovSS** [comment]
Хотел использовать Ванессу для отладки во время разработки. Т.е. вносим изменения в конфигуратор, жмем F5, отлаживаем вообще без каких либо действий в Предприятии, опять изменяем, F5, отлаживаем. Поэтому вообще не хотелось бы создавать файлы настроек. Сделал фичу, открыл ее в ванессе руками, установил нужные настройки, ванесса их запомнила и при следующем запуске чтобы использовались эти настройки. Но при этом тест запускал автоматически с помощью StartFeaturePlayer. Ну или кнопку надо сделать "Сохранить текущие настройки в JSON"

**Comment by Pr-Mex** [comment]
Предлагаю сделать проще. В VB есть вот такая настройка:
![image](https://cloud.githubusercontent.com/assets/8627416/21953597/ee82f250-da4c-11e6-8ca0-6bea31b3998e.png)

Надо добавить ещё один вариант: **Загрузить и выполнить**

**Comment by PiskunovSS** [comment]
Не видел этой настройки. Отличный вариант. Могу сам сделать. Как раз попробую pull request. На эту доработку нужен тест?

**Comment by Pr-Mex** [comment]
@PiskunovSS 
Ок. Жду PR.
На эту опцию тест делать не обязательно.

**Comment by PiskunovSS** [comment]
Сделал PR.

**Comment by Pr-Mex** [comment]
@PiskunovSS 
Ты писал, что готов поделиться обработкой.
Её можно положить в **vanessa-behavior\lib\VanessaLoader** и рядом положить README.md c описанием использования.

**Comment by PiskunovSS** [comment]
Да, поделюсь обязательно. Поправлю немного и описание сделаю только.

**Comment by Pr-Mex** [comment]
Решено.
