### ISSUE TITLE
Не удается получить изменения формы, если была незаполненная ТЧ

### ISSUE THREAD

**Issue by KrapivinAndrey** [silverbulleters/vanessa-behavior#497]
Поправить строку 9645.
Условие должно быть 
Если ЭлемБыло[Ключ] = Неопределено Тогда

**Comment by Pr-Mex** [comment]
Согласен.

**Comment by Pr-Mex** [comment]
@KrapivinAndrey 
Я внёс указанные изменения.
Можно проверять.
Спасибо!

**Comment by KrapivinAndrey** [comment]
Все работает

**Comment by slaxxals** [comment]
@KrapivinAndrey @Pr-Mex 

Не согласен, что все работает :)
Коммит 3846993d

В моем случае исправленный код 
`Если ЭлемБыло[Ключ] = Неопределено Тогда` 
не работает. При подключении тест-клиента и получении изменения формы Gherkin ошибка 

{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(9662)}: Получение элемента по индексу для значения не определено
				Если ЭлемБыло[Ключ] = Неопределено Тогда

Вернул предыдущий код локально:
`Если Было = Неопределено Тогда`
работает нормально.

Структура Было в моем случае при первом запуске принимает значение Неопределено. А переменная ЭлемБыло инициализируется только при условии 'Если Было <> Неопределено Тогда' в начале 'Функция ВывестиИзмененияФормыGherkin(Было,Стало)'

**Comment by KrapivinAndrey** [comment]
@slaxxals  Работаю с фичей из воздуха на последнем обновлении и в режиме получить изменения формы и в режиме получить состояние формы - ошибок не было.

**Comment by slaxxals** [comment]
@KrapivinAndrey а если после первого запуска тест клиента получить изменения на форме? Форма состоит из двух дин. списков.

**Comment by crabzzy** [comment]
@slaxxals 
Алексей, и у меня неотработало в "кнопконажималке":
заменил на

```
Если ЭлемБыло = Неопределено
     И ЭлемБыло[Ключ] = Неопределено Тогда
```

**Comment by Pr-Mex** [comment]
Я в следующем патче залью изменения.

**Comment by Pr-Mex** [comment]
Обновил. Сейчас должно работать.
