### ISSUE TITLE
Пересоздание EPF-обработки

### ISSUE THREAD

**Issue by crabzzy** [silverbulleters/vanessa-behavior#501]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Пересоздание EPF-обработки
   Как Бехавиорист
   Я хочу Чтобы работала кнопка "Создать и обновить шаблоны обработок" закладки "Генератор EPF"  

Контекст:
  Дано: Vanessa-Behaviour 1.079
  И 1С:Предприятие 8.3 (8.3.8.1933)
  И Управляемые формы не таксишные
  И НЕ ЕстьПоддержкаАсинхронныхВызовов

Сценарий: Работоспособность кнопки "Создать и обновить шаблоны обработок" закладки "Генератор EPF" при уже созданном EPF-файле для не такси управляемых форм (работало в 1.000 версии).
  Допустим: Допустим уже была создана EPF в step_definitions по Feature-файлу
  Когда: Я нажимаю "Создать и обновить шаблоны обработок" закладки "Генератор EPF"  
  Тогда: Появляются ошибки в строках 6557 и 6623 модуля УправляемаяФорма:
            Строка 6557: Тут необходимо каталог und предварительно создавать, т.к. ошибка:
           {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(6557)}: Ошибка при вызове конструктора (ЗаписьТекста)
ЗТ = Новый ЗаписьТекста(СтруктураОписанияEpf.ВременноеИмяМодуля,"UTF-8",,Ложь);
по причине:
Каталог не обнаружен 'C:\Users\Александр\AppData\Local\Temp\Src\v8_83Af\und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0ЗагрузкаНастроек.bsl'
           Строка 6623: вызывается исключение из программного кода, т.к. файл не существует
&НаКлиенте
Процедура УдалитьИзФайлаМодуляФормыУФТестМодуляФормы(ИмяФайлаФормаУФ)
	Файл = Новый Файл(ИмяФайлаФормаУФ);
	
	Если Не ФайлСуществуетКомандаСистемы(ИмяФайлаФормаУФ) Тогда
		ВызватьИсключение "УдалитьИзФайлаМодуляФормыУФТестМодуляФормы. Файл " + ИмяФайлаФормаУФ + " не найден!";
	КонецЕсли;
...

**Comment by crabzzy** [comment]
Леонид, коллеги, добрый день, у меня при пересоздании EPF-ки делается в каталоги Бехавиора bsl-ка. Может не стоит её прямо там размещать? А то коммиты предлагает SourceTree делать (можно конечно в gitigonre сложить подпапку).

...\vanessa-behavior\lib\TemplateEpfUF\und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0_ЗагрузкаНастроек.bsl

Хорошего дня!

**Comment by Pr-Mex** [comment]
Скорее всего у тебя не работают команды cmd, где используются русские символы.
Попробуй создать и пересоздать epf по фиче, где в пути и в имени файла не содержится кириллица.

**Comment by Pr-Mex** [comment]
Также можешь включить вывод отладочных сообщений и там будет видно, какие именно команды не срабатывают.

**Comment by crabzzy** [comment]
@Pr-Mex Леонид, добрый день,

русские имена в пути заменил на английские, не помогло, ошибка:

{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(6557)}: Ошибка при вызове конструктора (ЗаписьТекста)
	ЗТ = Новый ЗаписьТекста(СтруктураОписанияEpf.ВременноеИмяМодуля,"UTF-8",,Ложь); 
по причине:
Каталог не обнаружен 'C:\Users\Александр\AppData\Local\Temp\Src\v8_CB06_7\und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0_CheckImageMagick.bsl'

Отладочные сообщения:

26.01.2017 11:44:22 Запускаю генерацию epf.
26.01.2017 11:44:22 Ищу снипеты в каталоге e:\BDD\features\Drafts\
26.01.2017 11:44:22 Ищу снипеты в каталоге E:\Silverbulleters\vanessa-behavior\features\Libraries
26.01.2017 11:44:22 Работаю по фиче: e:\BDD\features\Drafts\CheckImageMagick.feature
26.01.2017 11:44:22 ОтносительныйКаталогФичи=e:\BDD\features\Drafts\
26.01.2017 11:44:22 Делаю распаковку e:\BDD\features\Drafts\step_definitions\CheckImageMagick.epf
26.01.2017 11:44:22 Строка распаковки: oscript E:\Silverbulleters\vanessa-behavior\vendor/precommit1c/v8files-extractor.os  --decompile "C:\Users\Александр\AppData\Local\Temp\v8_CB06_7.epf" "C:\Users\Александр\AppData\Local\Temp\Src"

**Comment by Pr-Mex** [comment]
@crabzzy 
Не все символы латинские в пути
![image](https://cloud.githubusercontent.com/assets/8627416/22328482/7fa902e0-e3cd-11e6-8365-ac8bc0777911.png)

**Comment by crabzzy** [comment]
@Pr-Mex Леонид, не знаю в этом ли дело,
я думаю не в этом.

Я не знаю как поменять путь к профилю пользователя:-( чтобы проверить
И не знаю как поменять чтобы 1С временные папки в другом месте создавало(

Как бы продвинуться в этом?

**Comment by Ndochp** [comment]
Самое простое - создать нового вин-пользователя. Ну или реестр покопать. Опять же, из под соседнего пользователя кажется.
http://www.admin01.ru/faq/103.html вот статейка 
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\ правильный юзер \ 
ключ ProfileImagePath

**Comment by Pr-Mex** [comment]
@crabzzy 
Просто перенаправь  переменную окружения Temp в каталог с латинскими символами.
![image](https://cloud.githubusercontent.com/assets/8627416/22521156/145adfcc-e8c8-11e6-89bc-7eaf94e1a54f.png)

**Comment by crabzzy** [comment]
@Pr-Mex попробую, Спасибо!

**Comment by SkyPunster** [comment]
Аналогичная проблема. 

1. Если жать кнопку без признака "Генерировать управляемую форму" тогда в сообщениях возникает такое:
`06.02.2017 16:18:00 Ошибка создания временного файла в подкаталоге C:\Users\D_Nemeshov\AppData\Local\Temp\v8_9A9A_8e.tmp!!!`

2. Если установить признак "Генерировать управляемую форму" тогда вылетает исключение 
```
{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(6883)}: Ошибка при вызове конструктора (ЗаписьТекста)
	ЗТ = Новый ЗаписьТекста(СтруктураОписанияEpf.ВременноеИмяМодуля,"UTF-8",,Ложь); 
по причине:
Каталог не обнаружен 'C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_9A9A_9b\und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0_СозданиеСчетовИТСДистрибуции.bsl' 
```
Создание обработок отрабатывает только если каталог step_definitions пуст и признак "генерировать управляемую форму" активирован.

Кирилицы в пути к темпу нет. Платформа 8.3.9.2033 управляемые формы (такси).

**Comment by Pr-Mex** [comment]
@SkyPunster 
Дело в том, что кириллица может быть в любой части пути.
В твоём случае - это имя файла.
![image](https://cloud.githubusercontent.com/assets/8627416/22659831/42d8aa5a-ecb0-11e6-8c23-961a2635640f.png)

Вот здесь, например, собраны рекомендации по настройке ОС, чтобы начали работать команды с русскими символами:
http://www.cyberforum.ru/windows7/thread83559.html

**Comment by SkyPunster** [comment]
Выполнил рекомендации, которые Вы предоставили. Дополнительно переименовал feature-файлы на английском языке. Теперь кириллицы нет вообще. Попробовал на другом компе даже, где соблюдены те же условия. Проблема по-прежнему присутствует. Кстати, и до изменений командная строка (если руками бить команды) адекватно отрабатывала пути, содержащие кириллицу.

**Comment by Pr-Mex** [comment]
@SkyPunster 
@crabzzy 
попробуйте вот что:
Надо вот этот файл
**C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os**
заменить файл на вот этот
https://yadi.sk/d/-IZjlJ403DPmHd
И попробовать ещё раз пересоздать epf.

**Comment by SkyPunster** [comment]
Попробовал. Теперь при попытке пересоздать вываливается окно CMD
![image](https://cloud.githubusercontent.com/assets/25499069/22724380/ddcd26e0-edef-11e6-82c1-44eed53ee69e.png)
Потом открывается толстый клиент, в котором стреляет защита от опасных действий (фишка 8.3.9.2033). После протыкивания жалоб платформы открывается обработка
![image](https://cloud.githubusercontent.com/assets/25499069/22724415/0ccb909e-edf0-11e6-81b8-ae8387127a14.png)
В логах прекоммита увидел строки:
`ИНФОРМАЦИЯ - Собираю исходники <C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_CE0E_20>
ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 279 / [Failed] Ожидали, что проверяемое значение (Ложь) является ИСТИНОЙ.
Файл переименования C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_CE0E_20\renames.txt должен существовать}`
Далее происходят те же ошибки - если с управляемой формой то модульная, если без нее - в сообщениях ошибка о недоступности каталога в темпе.

**Comment by alehinsasha** [comment]
> Чтобы отключить защиту от опасных действий вставил DisableUnsafeActionProtection=.*; в конфиги, не помогло.

должно было помочь, перезагрузи ПК и проверь, результат скриншотами сюда.

**Comment by alehinsasha** [comment]
только вывод отладочного лога в vanessa-behavior включи, то же сюда

**Comment by SkyPunster** [comment]
Перезагрузил комп. Подновил vanessa-behavior (теперь 1.086)
Попробовал снова без генерации управляемой формы.

![image](https://cloud.githubusercontent.com/assets/25499069/22729898/e04249c2-ee0e-11e6-9604-45e096f0e05e.png)

Вот лог сообщений которые выдала vanessa-behavior:
```
08.02.2017 14:48:07 Запускаю генерацию epf.
08.02.2017 14:48:08 Ищу снипеты в каталоге D:\Products\internal automation
08.02.2017 14:48:08 Загрузил снипеты из кеш: D:\Products\internal automation\features\Drafts\step_definitions\TestFeature.epf
08.02.2017 14:48:08 Работаю по фиче: D:\Products\internal automation\features\Drafts\TestFeature.feature
08.02.2017 14:48:08 ОтносительныйКаталогФичи=D:\Products\internal automation\features\Drafts\
08.02.2017 14:48:08 Делаю распаковку D:\Products\internal automation\features\Drafts\step_definitions\TestFeature.epf
08.02.2017 14:48:08 Строка распаковки: oscript D:\vanessa-stack\vanessa-behavior\vendor/precommit1c/v8files-extractor.os  --decompile "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_6.epf" "C:\Users\D_Nemeshov\AppData\Local\Temp\Src"
08.02.2017 14:48:24 Буду записывать C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6\ObjectModule_TestFeature.bsl
08.02.2017 14:48:24 Записал C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6\ObjectModule_TestFeature.bsl
08.02.2017 14:48:24 Переименовал в C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6\ObjectModule.bsl
08.02.2017 14:48:24 Пересоздаю D:\Products\internal automation\features\Drafts\step_definitions\TestFeature.epf
08.02.2017 14:48:24 Создаю из исходников C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6 
 Временный каталог сборки epf C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp
08.02.2017 14:48:24 СтрокаСборкиEpf=oscript -encoding=utf-8 "D:\vanessa-stack\vanessa-behavior\vendor/precommit1c/v8files-extractor.os" --compile "C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6" "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp" > "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_8.txt" 2>&1
08.02.2017 14:48:25 Лог команды сборки EPF:
ИНФОРМАЦИЯ - precommit1c v2.0.4

ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю параметр-флаг --remove-orig-bin-files
ОТЛАДКА - Добавляю позиционный параметр ПутьВходящихДанных
ОТЛАДКА - Добавляю позиционный параметр ВыходнойКаталог
ОТЛАДКА - Добавляю параметр-флаг --recursive
ОТЛАДКА - Разбор команды: --compile
ОТЛАДКА - Попадаю в РазобратьАргументы
ОТЛАДКА - Сбрасываю параметр-флаг: --recursive
ОТЛАДКА - Выбран токен: C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6
ОТЛАДКА - Ищу именованный параметр C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6
ОТЛАДКА - Ищу параметр-флаг C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6
ОТЛАДКА - Установлено значение позиционного параметра <ПутьВходящихДанных = C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6>
ОТЛАДКА - Выбран токен: C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp
ОТЛАДКА - Ищу именованный параметр C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp
ОТЛАДКА - Ищу параметр-флаг C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp
ОТЛАДКА - Установлено значение позиционного параметра <ВыходнойКаталог = C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp>
ОТЛАДКА - Выбран токен: 
ОТЛАДКА - Закончились токены
ОТЛАДКА - Трассировка РезультатРазбора:
ОТЛАДКА -       --recursive:Нет
ОТЛАДКА -       ПутьВходящихДанных:C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6
ОТЛАДКА -       ВыходнойКаталог:C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp
ОТЛАДКА - Трассировка РезультатКоманды.ЗначенияПараметров:
ОТЛАДКА -       --recursive:Нет
ОТЛАДКА -       ПутьВходящихДанных:C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6
ОТЛАДКА -       ВыходнойКаталог:C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp
ИНФОРМАЦИЯ - Собираю исходники <C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6>
ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\asserts\src\bdd-asserts.os / Ошибка в строке: 279 / [Failed] Ожидали, что проверяемое значение (Ложь) является ИСТИНОЙ.
Файл переименования C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_6\renames.txt должен существовать}
08.02.2017 14:48:25 Ошибка создания временного файла в подкаталоге C:\Users\D_Nemeshov\AppData\Local\Temp\v8_C221_7.tmp!!!
08.02.2017 14:48:25 Создание epf по фичам закончено.
```

Так же открылось окно толстого клиента, так же стрельнула защита от опасных действий.
![image](https://cloud.githubusercontent.com/assets/25499069/22729803/7de924b2-ee0e-11e6-99de-73f9a7ed0d8f.png)

Если запускать с генерацией управляемой формы то происходит то же самое, но после того как закрываешь этот открывшийся толстый клиент вылетает модульная:

```
{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(6940)}: Ошибка при вызове конструктора (ЗаписьТекста)
	ЗТ = Новый ЗаписьТекста(СтруктураОписанияEpf.ВременноеИмяМодуля,"UTF-8",,Ложь); 
по причине:
Каталог не обнаружен 'C:\Users\D_Nemeshov\AppData\Local\Temp\Src\v8_C221_e\und\70e297e0-e8a2-43bf-8be1-62e408f610a1.0_TestFeature.bsl'
```

**Comment by alehinsasha** [comment]
> Чтобы отключить защиту от опасных действий вставил DisableUnsafeActionProtection=.*; в конфиги, не помогло.

значит защиту вы не отключили

да, и в УФ нет смысла генерить обработки с обычными формами

**Comment by alehinsasha** [comment]
попробуйте снова отключить защиту, во всех файлах conf.cfg либо удалите все платформы выше 8.3.9.1850 либо этот [форк](https://github.com/alehinsasha/precommit1c) поиспользуйте.

**Comment by Pr-Mex** [comment]
@SkyPunster 
получилось отключить защиту от опасных действий?

**Comment by SkyPunster** [comment]
Отключить не удалось, хотя вбил строчку с отключением вообще во все конфиги, а именно:
1. `"C:\Program Files (x86)\1cv8\conf\conf.cfg"`
2. `"C:\Program Files\1cv8\conf\conf.cfg"`
3. `"C:\Program Files (x86)\1cv8\8.3.9.2033\bin\conf\conf.cfg"`
4. `"C:\Program Files\1cv8\8.3.9.2033\bin\conf\conf.cfg"`
5. `"C:\Users\D_Nemeshov\AppData\Local\1C\1cv8\conf\conf.cfg"`
После этого перегружался. vanessa-behavior я запускаю на базе с платформой 8.3.9.2033.

Удалить 8.3.9.2033 пока что нет возможности. Попробовал использовать предложенный @alehinsasha форк - не помогло. Пока еще исследую. Я так понимаю проблема воспроизводится только у меня?

**Comment by alehinsasha** [comment]
Ты используешь клиент 1С 32 бита или 64?
Попробуй установить релиз 8.3.9.2170.
И на всякий случай покажи свой файл C:\Program Files (x86)\1cv8\conf\conf.cfg

**Comment by SkyPunster** [comment]
![image](https://cloud.githubusercontent.com/assets/25499069/22772782/d9c4779a-eec8-11e6-89cd-bead962de22d.png)
![image](https://cloud.githubusercontent.com/assets/25499069/22772784/dc15af1e-eec8-11e6-9fb3-b07c36d34cde.png)
После установки 8.3.9.2170 перестал открываться толстый клиент при попытке перегенерировать обработки. Ошибки остались те же.

**Comment by alehinsasha** [comment]
Клиент 32 или 64 используешь?
И какой тип клиента запускается, когда открывается окно 1С, в котором не отключается защита?

**Comment by crabzzy** [comment]
@SkyPunster 
Проблема у меня и у коллег моих была, я дальше не исследовал.
У меня проблема осталась, я правда остановился на окружении, у меня всё ещё русские буквы в путях. Дальше я не пробовал. Полагаю будет также всё как у вас.

**Comment by SkyPunster** [comment]
На 8.3.9.2033 пользовал 32 клиент.
Сейчас, на 8.3.9.2170, 64 клиент.
Сейчас защита не стреляет. Когда стреляла открывался толстый клиент.

**Comment by alehinsasha** [comment]
Теперь создание и пересоздание epf работает без ошибок?

**Comment by SkyPunster** [comment]
Нет, ошибки те же, просто перестал открываться толстый клиент с ошибкой защиты от опасных действий. Модульная "Каталог не обнаружен" так и валится.

**Comment by alehinsasha** [comment]
Попробуй посмотреть в отладке что именно не отрабатывает.

**Comment by maxstarkov** [comment]
Столкнулся с аналогичной проблемой при использовании precommit, оказалось, что нужно правильно прописать шаблон строки соединения с ИБ в параметре DisableUnsafeActionProtection.
Нужно просто указать: DisableUnsafeActionProtection=.* (без символа точка с запятой в конце).
Добавил этот параметр в файл: C:\Program Files (x86)\1cv8\conf\conf.cfg.
Все работает отлично на платформе 1С:Предприятие 8.3 (8.3.9.2170).

**Comment by Pr-Mex** [comment]
@maxstarkov 
Спасибо. Я поправил F.A.Q.

**Comment by Pr-Mex** [comment]
@SkyPunster 
Сделай вот что
1. Обнови VB до версии 1.90
2. Включи отладочные сообщения.
![image](https://cloud.githubusercontent.com/assets/8627416/22854193/e4ccf6be-f079-11e6-8032-fe414bec1dd3.png)

3. Сделай пересоздание epf для УФ.
4. Скинь сюда лог сообщений.

**Comment by SkyPunster** [comment]
Привожу лог:
```
13.02.2017 9:24:55 Запускаю генерацию epf.
13.02.2017 9:24:55 Ищу снипеты в каталоге D:\Products\internal automation
13.02.2017 9:24:55 Загрузил снипеты из кеш: D:\Products\internal automation\features\Drafts\step_definitions\TestFeature.epf
13.02.2017 9:24:55 Загрузил снипеты из кеш: D:\Products\internal automation\features\step_definitions\СозданиеДокументовКладовщиком.epf
13.02.2017 9:24:55 Загрузил снипеты из кеш: D:\Products\internal automation\features\step_definitions\СозданиеДокументовМенеджером.epf
13.02.2017 9:24:55 Работаю по фиче: D:\Products\internal automation\features\СозданиеДокументовКладовщиком.feature
13.02.2017 9:24:55 ОтносительныйКаталогФичи=D:\Products\internal automation\features\
13.02.2017 9:24:55 Делаю распаковку D:\Products\internal automation\features\step_definitions\СозданиеДокументовКладовщиком.epf
13.02.2017 9:24:55 Строка распаковки: oscript -encoding=utf-8 D:\vanessa-stack\vanessa-behavior\vendor/precommit1c/v8files-extractor.os  --decompile "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_E9DB_3f.epf" "C:\Users\D_Nemeshov\AppData\Local\Temp\Src" > "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_E9DB_40.txt" 2>&1
13.02.2017 9:24:56 Лог команды распаковки EPF:
13.02.2017 9:24:56 ИНФОРМАЦИЯ - precommit1c v2.0.6

ИНФОРМАЦИЯ - Проверка необходимости выгрузки файла C:\Users\D_Nemeshov\AppData\Local\Temp\v8_E9DB_3f.epf в каталог C:\Users\D_Nemeshov\AppData\Local\Temp\Src, корень C:\Users\D_Nemeshov\AppData\Local\Temp\
ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 535 / Не найден путь к платформе 1С <8.3.8>}
```

И при чем тут 8.3.8, я ведь под 8.3.9.2170 использую... Куда копать?

**Comment by SkyPunster** [comment]
Запустил, получил такой лог:
```
13.02.2017 9:24:55 Запускаю генерацию epf.
13.02.2017 9:24:55 Ищу снипеты в каталоге D:\Products\internal automation
13.02.2017 9:24:55 Загрузил снипеты из кеш: D:\Products\internal automation\features\Drafts\step_definitions\TestFeature.epf
13.02.2017 9:24:55 Загрузил снипеты из кеш: D:\Products\internal automation\features\step_definitions\СозданиеДокументовКладовщиком.epf
13.02.2017 9:24:55 Загрузил снипеты из кеш: D:\Products\internal automation\features\step_definitions\СозданиеДокументовМенеджером.epf
13.02.2017 9:24:55 Работаю по фиче: D:\Products\internal automation\features\СозданиеДокументовКладовщиком.feature
13.02.2017 9:24:55 ОтносительныйКаталогФичи=D:\Products\internal automation\features\
13.02.2017 9:24:55 Делаю распаковку D:\Products\internal automation\features\step_definitions\СозданиеДокументовКладовщиком.epf
13.02.2017 9:24:55 Строка распаковки: oscript -encoding=utf-8 D:\vanessa-stack\vanessa-behavior\vendor/precommit1c/v8files-extractor.os  --decompile "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_E9DB_3f.epf" "C:\Users\D_Nemeshov\AppData\Local\Temp\Src" > "C:\Users\D_Nemeshov\AppData\Local\Temp\v8_E9DB_40.txt" 2>&1
13.02.2017 9:24:56 Лог команды распаковки EPF:
13.02.2017 9:24:56 ИНФОРМАЦИЯ - precommit1c v2.0.6

ИНФОРМАЦИЯ - Проверка необходимости выгрузки файла C:\Users\D_Nemeshov\AppData\Local\Temp\v8_E9DB_3f.epf в каталог C:\Users\D_Nemeshov\AppData\Local\Temp\Src, корень C:\Users\D_Nemeshov\AppData\Local\Temp\
ОШИБКА - {Модуль C:\Program Files (x86)\OneScript\lib\v8runner\src\v8runner.os / Ошибка в строке: 535 / Не найден путь к платформе 1С <8.3.8>}
```
Понял что что-то тут не так, я же на 8.3.9. В файле v8files-extractor.os оказалось прописана маска платформы 8.3.8 (я использовал предложенный выше форк) Подменил на 8.3.9 - заработало всё как надо. Перекачал прекоммит с мастер ветки и всё работает теперь. 
Спасибо вам за оперативную поддержку!

**Comment by crabzzy** [comment]
Леонид, с новым v8runner.os всё заработало на 8.3.8.1933, теперь epf-ки пересоздаются, спасибо!
Автор OneScript Его (v8runner.os) как то можно в дистрибутив OneScript внедрить автору OneScript? (@EvilBeaver ?)

**Comment by Pr-Mex** [comment]
@crabzzy 
Да, я свяжусь с ними.

**Comment by Pr-Mex** [comment]
Задачу закрываю.

**Comment by EvilBeaver** [comment]
Зачем внедрять, когда есть opm update?

**Comment by Pr-Mex** [comment]
@EvilBeaver 
Объясни для непосвященных, плиз.

**Comment by JohnyDeath** [comment]
@Pr-Mex теперь для обновления библиотек достаточно запустить:
```
opm update opm
opm update -all
```
via https://github.com/oscript-library/opm

**Comment by Pr-Mex** [comment]
@JohnyDeath 
Понял, спасибо.
