### ISSUE TITLE
Слишком длинные имена feature файлов

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-behavior#505]
Последовательная работа нескольких клиентов тестирования в одном сценарии.feature

Пожалуйста, не надо быть такими же как и 1С и писать в названии всю повесть, есть проблема с очень длинными путями в наименованиях файлов. 

https://github.com/silverbulleters/vanessa-behavior/blob/develop/features/Libraries/TestClients/%D0%9F%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%20%D0%BD%D0%B5%D1%81%D0%BA%D0%BE%D0%BB%D1%8C%D0%BA%D0%B8%D1%85%20%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%20%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%20%D0%B2%20%D0%BE%D0%B4%D0%BD%D0%BE%D0%BC%20%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B8.feature

**Comment by Pr-Mex** [comment]
@pumbaEO 
у тебя эта фича не работает?

**Comment by pumbaEO** [comment]
с учетом того, что написало "слишком длинное имя файла" и не смогло склонировать, то да фича не работает.

**Comment by nixel2007** [comment]
git config --global core.longpaths true

**Comment by Pr-Mex** [comment]
@pumbaEO 
это решает твою проблему?

**Comment by pumbaEO** [comment]
Ребят, я сейчас беру и конфигуратором разбираю внешние обработки, конфигуратор не понимает данной настройки git config --global core.longpaths true 

Т.е. если попытаться перейти на разработку через исходники, то этот файл будет проблемой, как фича файл, так и внешняя обработка.

**Comment by JohnyDeath** [comment]
Не понял как конфигуратор на это влияет? Он обрезает имена?

**Comment by pumbaEO** [comment]
он не может сохранить веншнюю обработку. по длинному пути.

**Comment by Pr-Mex** [comment]
@pumbaEO 
Попробуй сейчас.

**Comment by Pr-Mex** [comment]
Закрываю. Если вопрос всё ещё не решен - пишите в эту тему.
