### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by mazaharka** [silverbulleters/vanessa-behavior#508]
1) Подскажите пожалуйста можно ли как-то ссылаться на сценарии, написанные в одной feature?
2) Есть ли какой-либо механизм описания отчёта языком gherkin? Или только по механизму "Как придумаешь, так и описывай"?

**Comment by Pr-Mex** [comment]
@mazaharka 
Привет.
Опиши подробнее что ты хочешь сделать/получить.
Если возможно - приведи сценарии.

**Comment by crabzzy** [comment]
@mazaharka 
Отчёты - "кнопконажималкой" - через получение состояния формы, потерял видео, вложу ссылку позже.
Сценарии  в одной фиче - да, можно

```
Сценарий: Два Плюс Два
  Когда Дано Два
  И Прибавляем Два
  Тогда получаем Четыре

Сценарий: Реиспользование сценария
  Когда Два Плюс Два
  Тогда Получаем Четыре
```

**Comment by Pr-Mex** [comment]
@mazaharka 
насчет "ссылаться на сценарии" -  попробуй посмотреть вот это
https://www.youtube.com/watch?v=SbAQKLhJhXI&list=PL2OubLDBf73_7JS2cd4UhkSvSOnAyu9u-

насчет "описания отчёта языком gherkin" - наверно тебе может помочь шаг вида:
И Табличный документ формы с именем "РеквизитТабличныйДокумент" стал равен макету с именем "ИмяМакета"

**Comment by Pr-Mex** [comment]
Закрываю. Если вопрос всё ещё не решен - пишите в эту тему.
