### ISSUE TITLE
Передача тестового параметра содержащего апостроф

### ISSUE THREAD

**Issue by PiskunovSS** [silverbulleters/vanessa-behavior#509]
Функционал: передача тестового параметра содержащего апостроф
   Как разработчик
   Я хочу передавать параметры содержащие апостроф потому что это иногда необходимо

Контекст:
  Дано: 1.083
  И 8.3.9

Сценарий: В текстовое поле я ввожу текст содержащий апостроф
  Допустим: я открываю форму содержащую текстовое поле
  Когда: в поле "Текст1" я ввожу текст "текст содержащий 'апостроф'"
  Тогда: поле "Текст1" содержи значение "текст содержащий 'апостроф'"

**Comment by Pr-Mex** [comment]
Решено.
Теперь надо экранировать апостроф вот так
\'
