### ISSUE TITLE
Предлагаю в .gitignore добавить lib/TemplateEpfUF/*

### ISSUE THREAD

**Issue by crabzzy** [silverbulleters/vanessa-behavior#512]
Добрый день, Леонид, Коллеги!
Предлагаю в .gitignore добавить
lib/TemplateEpfUF/*

В .gitignore сейчас только:
lib/TemplateEpf/*.txt

**Comment by Pr-Mex** [comment]
@crabzzy 
Привет.
А зачем это надо?

**Comment by crabzzy** [comment]
@Pr-Mex 
у меня там лежат файлы при сборке Epf ки генерятся (которая так и не собирается, связано с issue #501)
![templateepfuf](https://cloud.githubusercontent.com/assets/16597488/22542420/bdf4f846-e93c-11e6-8ebd-fe9e17237e15.png)

**Comment by Pr-Mex** [comment]
#501 не работает из-за настройки ОС и переменных окружения.
Сделай чтобы у тебя работали команды с кириллицей и проблема уйдёт.
А этим файлам сделай discard в Source Tree. Или remove.

**Comment by Pr-Mex** [comment]
С #501 разобрались.
Задачу закрываю.
