### ISSUE TITLE
Поправить в библиотеке в РаботаСИнтерфейсом.epf добавление и реализацию шага

### ISSUE THREAD

**Issue by crabzzy** [silverbulleters/vanessa-behavior#515]
1. Поправить в библиотеке в РаботаСИнтерфейсом.epf добавление шагов
ВОткрытойФормеВТЧЯПерехожуНаПервуюСтроку
ВОткрытойФормеВТЧЯПерехожуНаПоследнююСтроку

2. Поправить реализацию шага
ВТЧЯПерехожуНаОднуСтрокуВверх
т.к. сейчас он идёт вниз

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
