### ISSUE TITLE
Не выполняется фича при наличии нескольких таблиц с параметрами

### ISSUE THREAD

**Issue by PashaMak** [silverbulleters/vanessa-behavior#522]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

Функционал: Оптимизация скорости работы обработки распределения
	Как операционист
	Я хочу чтобы обработка распределения по локальным данным выводила корректные данные
	Чтобы убедиться, что локальный расчет не нарушила функцинальность обработки

Контекст:
	Дано Загружены данные окружения из макета "ТестовыйМакетПополнениеСтатусы"
	И Загружены данные окружения из макета "ЛокальныеДанныеПоОстаткам"	
    И Созданы тестовые движения по регистрам	
	И Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: Запуск обработки Расчет параметров распределения с отбором по номенклатуре
	Когда В панели разделов я выбираю "..."
	И     В панели функций я выбираю "----"
	Тогда открылось окно "----"
	И 	  В открытой форме я снимаю флаг с заголовком "---"
	И     Я устанавливаю флаг "---"
	И     я нажимаю кнопку выбора у поля "Дата отчета"
	И     в поле "Дата отчета" я ввожу текст "09.09.2016"
	И     я изменяю флаг "Макс"
	И     в поле "Мах >=" я ввожу текст "1"
	И     я нажимаю кнопку выбора у поля "Склад отправитель"
	Тогда открылось окно "---"
	И     В форме "---" в таблице "Список" я перехожу к строке:
![default](https://cloud.githubusercontent.com/assets/24808007/23196086/0749485a-f8ea-11e6-97e9-1d462b2caff6.png)
![default](https://cloud.githubusercontent.com/assets/24808007/23196085/07445c0a-f8ea-11e6-82d5-9540b9e25d68.png)
![default](https://cloud.githubusercontent.com/assets/24808007/23196095/1054af0c-f8ea-11e6-80da-dd5bbd6828df.png)
![default](https://cloud.githubusercontent.com/assets/24808007/23196106/1dfcf448-f8ea-11e6-9dcc-9d84f2a8d033.png)
![default](https://cloud.githubusercontent.com/assets/24808007/23196107/1e021270-f8ea-11e6-99fc-bde5f76dd456.png)

	| 'Код'       | 'Наименование' |
	| '---' | 'Новосибирск'  |
	И     В форме "---" в ТЧ "Список" я выбираю текущую строку
	Тогда открылось окно "--- *" 
	И     в ТЧ "СкладыПолучатели" я нажимаю на кнопку "Добавить"
	И     в ТЧ "СкладыПолучатели" я нажимаю кнопку выбора у реквизита "Склад получатель"
	Тогда открылось окно "---"
	И     В форме "---" в таблице "Список" я перехожу к строке:
	| 'Склад'              | 'Код'       |
	| '----_Основной' | '---' |
	И     В форме "---" в ТЧ "Список" я выбираю текущую строку
	Тогда открылось окно "--- *"	
	И     в ТЧ "Товары" я нажимаю на кнопку "Добавить"
	И     в ТЧ "Товары" я выбираю значение реквизита "Номенклатура" из формы списка
	Тогда открылось окно "Номенклатура"
	И     В форме "Номенклатура" в таблице "СписокРасширенныйПоискНоменклатура" я перехожу к строке:
	| 'Код'            | 'Наименование'                         |
	| '----' | '--- Фильтр воздушный Bosch' |	
	И     В форме "Номенклатура" в ТЧ "СписокРасширенныйПоискНоменклатура" я выбираю текущую строку
	Тогда открылось окно "--- *"
	И     в ТЧ "Товары" я нажимаю на кнопку "Добавить"
	И     в ТЧ "Товары" я выбираю значение реквизита "Номенклатура" из формы списка
	Тогда открылось окно "Номенклатура"
	И     В форме "Номенклатура" в таблице "СписокРасширенныйПоискНоменклатура" я перехожу к строке:
	| 'Код'            | 'Наименование'                         |
	| 'NSIN----' | '--- Диск тормозной зад Brembo' |	
	И     В форме "Номенклатура" в ТЧ "СписокРасширенныйПоискНоменклатура" я выбираю текущую строку
	Тогда открылось окно "--- *"
	И     в ТЧ "Товары" я нажимаю на кнопку "Добавить"
	И     в ТЧ "Товары" я выбираю значение реквизита "Номенклатура" из формы списка
	Тогда открылось окно "Номенклатура"
	И     В форме "Номенклатура" в таблице "СписокРасширенныйПоискНоменклатура" я перехожу к строке:
	| 'Код'            | 'Наименование'                         |
	| '----' | '--- Лампа H7 12V 55W Bosch' |	
	И     В форме "Номенклатура" в ТЧ "СписокРасширенныйПоискНоменклатура" я выбираю текущую строку
	Тогда открылось окно "--- *"
	И     я нажимаю на кнопку "Рассчитать"
	И     Пауза 5
	Тогда таблица формы с именем "ТабРасчета" стала равной:
		| 'Мин Отпр' | 'Мах Отпр'| 'Мин рыночная цена' | 'Мин получателя' | 'Средняя продажа' | 'Маркетинговая группа' 	| 'Макс получателя'	| 'Объем продаж' | 'Набор аналогов' | 'Макс мес продажа за год' | 'Скоринг'	| 'Сезонность' | 'Кр.заказа' | 'Макс сделка за 180 дней шт' | 'Доля отгрузки' 	| 'Излишки получателя' 	| 'Кол дней наличия за посл 90 дней' 	| 'Статус номенклатуры' | 'Применяемость'                                                                              	| 'Кол дней с первого прихода основной склад за посл 90 дней' | 'Кнал' | 'Склад получателя' | 'Остаток получателя' 	| 'Кол сделок за посл 180 дней' | 'N' | 'Модель сезонности' | 'Рыночная цена' | 'Артикул'    | 'Номенклатура'                         | 'Количество сделок' | 'Потребность полная' 	| 'НСПолучателя'	| 'Код склада получателя' | 'Прибыль' | 'Номенклатурная группа' 		| 'Код набора аналогов' | 'Продано за последние 180 дней шт' | 'Part number'   | 'Коэффициент корректировочный' | 'Кол дней с даты посл прихода на склад пол' | 'Заказано получателем' | 'Бренд'  | 'Остаток отпр' | 'Код ---'        | 'Уже заказано' | 'Коэффициент АBC' 	| 'Кр.хранения' |
		| '' 	 	 | '' 	 	 | ''                  | '4,0'            | ''           	  | 'Головной свет'     	| '6,0'            	| 'X'            | * 				| '4,0'                     | '-2,32'  	| '1,000'      | '1,0'       | '4,0'                        | '1,000'         	| ''                	| ''                               	| 'Новинка'         	| ''                                                                                       	| *                                                           | *      | 'Краснодар'        | ''               		| '1'                           | '1' | 'Основной'          | ''              | '---' | '--- Лампа H7 12V 55W ---' | 'X'                 | '6,0'                   	| '4,0'             	| '---'             | 'X'       | 'Лампа накаливания основного света'    	| ''                    | '4,0'                              | '1 987 301 107' | *                              | '155'                                       | '2,0'                  | 'Bosch'  | '2,0'          | '---' | ''             | ''            		| '2,0'         |
		| '5,0' 	 | '7,0' 	 | ''                  | '10,0'           | '2,250'           | 'Фильтр воздушный'     	| '15,0'           	| 'A'            | * 				| '3,0'                     | '133,60' 	| '1,000'      | '1,0'       | '3,0'                        | '0,438'         	| ''                	| '28'                               	| 'Ассортимент'         | 'Ford'                                                                                       	| *                                                           | *      | 'Краснодар'        | '1,0'               	| '1'                           | '2' | 'Основной'          | ''              | '---' | '--- Фильтр воздушный ---' | 'A'                 | '13,0'                   	| '13,0'             	| '---'             | 'B'       | 'Фильтр воздушный'      		| ''                    | '3,0'                              | '---' | *                              | '28'                                        | ''                     | 'Bosch'  | '4,0'          | '----' | '1,0'          | '0,98'            	| '1,0'         |
		| '4,0' 	 | '4,0' 	 | ''                  | '2,0'            | '1,500'           | 'Диски тормозные'      	| '4,0'            	| 'A'            | * 				| '2,0'                     | '10,70'  	| '1,000'      | '1,0'       | '2,0'                        | ''         	| ''                   	| '8'                                	| ''                    | 'TOYOTA LAND CRUISER 	| *                                                           | *      | 'Краснодар'        | ''               		| '1'                           | '3' | 'Основной'          | ''              | '---'   | '--- Диск тормозной зад ---' | 'A'                 | '2,0'                   	| '2,0'             	| '---'             | 'A'       | 'Диск тормозной'        		| ''                    | '2,0'                              | '---'    | *                              | '8'                                         | ''                     | 'Brembo' | '1,0'          | '---' | '2,0'          | '0,98'            	| '2,0'         |
	И     Я закрываю окно "--- *"
	Тогда открылось окно "1С:Предприятие"
	И     я нажимаю на кнопку "Да"
	И     Я закрываю сеанс TESTCLIENT
	И     я очищаю лишние данные

> Прикладывайте файлы скриншотов

**Comment by alehinsasha** [comment]
Обновитесь на версию 1.097 и проверьте ещё раз.

**Comment by PashaMak** [comment]
Эта ошибка прошла, появилась другая:
![default](https://cloud.githubusercontent.com/assets/24808007/23200391/a515a2c4-f906-11e6-8cc3-ba10fd811d9e.png)

**Comment by PashaMak** [comment]
Все работает. Спасибо.
