### ISSUE TITLE
Вывод корректного пути фичи при замечании по тэгу @tree

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-behavior#524]
```Gherkin
Функционал: Вывод корректного имени фичи при замечании по тэгу @tree
   Как разработчик, использующий VB
   Я хочу, чтобы при выводе замечания по тэгу @tree при наличии пробелов вместо табов выводился корректный путь к фиче

Контекст:
  Дано: 1.097
  И 1С 8.3.8.1784

Сценарий: по тэгу @tree при наличии пробелов вместо табов
  Допустим в числе загружаемых фич имеется фича с тэгом @tree и начальными пробелами вместо табов
  Когда загружается такая фича
  Тогда в окно сообщений в замечании выводится полный путь к фиче
```

Сейчас выводится сообщение вида:
`В фиче <C:\Users\username\AppData\Local\Temp\v8_3373_342.feature> обнаружены строки с пробелами в начале и тэг @Tree. Вместо пробелов в начале строки должны быть символы табуляции.`
Т.е. путь к фиче из темпа, а не реальный полный путь.

**Comment by alehinsasha** [comment]
@1cgh привет, выложи, пожалуйста, feature файлы, на которых воспроизвелась проблема.

**Comment by 1cgh** [comment]
Например, такой:
[524.zip](https://github.com/silverbulleters/vanessa-behavior/files/803398/524.zip)

feature нельзя приложить, зазиповал)

**Comment by 1cgh** [comment]
Исправлено. Спасибо.
