### ISSUE TITLE
Некорректно отрабатывает выполнение сценариев только по одной фиче

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-behavior#525]
Некорректно работает https://github.com/silverbulleters/vanessa-behavior/issues/329 на 1.097:

![2017-02-27 13 02 01](https://cloud.githubusercontent.com/assets/24507052/23357012/125fc96a-fced-11e6-8d9a-a4fff215d65e.png)

**Comment by alehinsasha** [comment]
@1cgh привет, выложи, пожалуйста, feature файлы, на которых воспроизвелась проблема.

**Comment by 1cgh** [comment]
Вот пример:
[Test.zip](https://github.com/silverbulleters/vanessa-behavior/files/803389/Test.zip)

**Comment by 1cgh** [comment]
Ошибка на том же примере, если райтклик сделать на строке дерева с фичей:

> {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(5974)}: Значение не является значением объектного типа (ПолучитьЭлементы)
> 	Для Каждого СтрокаДерева Из Дерево.ПолучитьЭлементы() Цикл

Если на строке сценария или шага, то всё ок.

**Comment by Pr-Mex** [comment]
Исправлено.

**Comment by 1cgh** [comment]
Работает. Спасибо.
