### ISSUE TITLE
Запуск Sikuli-скриптов

### ISSUE THREAD

**Issue by 1cgh** [silverbulleters/vanessa-behavior#526]
```Gherkin
Функционал: Использование Sikuli
   Как разработчик
   Я хочу получить поддержку запуска Sikuli-скриптов из VB под Windows и Linux

Контекст:
  Дано: last version VB
  И полная версия 1С - любая из поддерживаемых
  И любая конфигурация
  И я установил SikuliX по инструкции http://sikulix.com/quickstart/

Сценарий: Запуск sikuli-скриптов
  Когда я прописал путь к runsikulix(.cmd) с помощью path 
  Тогда Sikuli-скрипты выполняются с помощью runsikulix(.cmd) согласно http://sikulix-2014.readthedocs.io/en/latest/faq/010-command-line.html#how-to-run-sikulix-from-command-line
```

Сейчас запуск Sikuli реализован только для винды, к тому же хардкод пути к jar в Функция ПолучитьСтрокуВызоваSikuli()

**Comment by alehinsasha** [comment]
@1cgh На эту тему был pull request https://github.com/silverbulleters/vanessa-behavior/pull/454
Он пересекается с твоей темой?
Ты на какой версии java хочешь запускать Sikuli?

**Comment by 1cgh** [comment]
@alehinsasha не пересекается. там замена одного хардкода другим)
предполагается, что java установлена версии, достаточной для запуска сикули через runsikulix(.cmd)

**Comment by 1cgh** [comment]
@alehinsasha т.е. по сути строка выполнения скрипта будет просто 
runsikulix -r <путь к скрипту>
Путь к runsikulix должен быть задан через path

По поводу Явы:
> To use the SikuliX features you need a valid Java runtime installation (JRE, preferably the Oracle versions) of at least version 6. SikuliX works with version 7 and 8 too and version 2 will need at least Java 7.

http://sikulix-2014.readthedocs.io/en/latest/basicinfo.html#sikulix-system-specifics

**Comment by Pr-Mex** [comment]
@1cgh 
Привет.
Возьмёшься сделать?

**Comment by 1cgh** [comment]
@Pr-Mex  под виндой  что-то чехарда с еррорлевелами. Сейчас всшелл запускает батник, который запускает цмдшку, которая запускает экзешник явы, который выполняет явакод. В доме, который построил Джек. И всшелл.ран возвращает единицу, хотя еррорлевел в батнике при успешном выполнении sikulixrun.cmd равен 0

**Comment by 1cgh** [comment]
@Pr-Mex и еще: как поступим с текущей реализацией? я про то, что если просто заменить, то у тех, у кого сикули были поставлены давно и runsikulix отсутствует, то внезапно перестанет работать то, что работало просто запуском jar

**Comment by 1cgh** [comment]
@Pr-Mex с кодами возврата разобрался. Какое решение по текущей строке вызова будет? Просто там еще в фичах надо править вот типа такого:
https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Libraries/VB/step_definitions/%D0%94%D0%BE%D0%BA-%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%9D%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F%D0%A4%D0%B8%D1%87%D0%B8/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L193

**Comment by Pr-Mex** [comment]
>@Pr-Mex под виндой что-то чехарда с еррорлевелами. 

Не понял что там не так.
Cmd нужен, чтобы не запускать из 1С кириллические символы. На некоторых системах это помогает. Эрорлевел из Sikuli пробрасывается корректно. Попробуй написать Exit(1) в Sikuli/

**Comment by Pr-Mex** [comment]
>@Pr-Mex и еще: как поступим с текущей реализацией? я про то, что если просто заменить, то у тех, у кого сикули были поставлены давно и runsikulix отсутствует, то внезапно перестанет работать то, что >работало просто запуском jar 

Надо заменить так чтобы работало и по старому и по новому. 
Надо добавить новый метод. Старый будет depricated.

**Comment by Pr-Mex** [comment]
>@Pr-Mex с кодами возврата разобрался. Какое решение по текущей строке вызова будет? Просто там еще в фичах надо править вот типа такого:
https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/features/Libraries/VB/step_definitions/%D0%94%D0%BE%D0%BA-%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%9D%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F%D0%A4%D0%B8%D1%87%D0%B8/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0.bsl#L193

Эта фича содержит старый код. Там должно быть
Ванесса.ПолучитьСтрокуВызоваSikuli()
