### ISSUE TITLE
Не верно рассчитывается иерархия при использовании тега tree

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#527]
Для такого фича файла.
"Когда я делаю Шаг 2" попадает внутрь "Когда я делаю Шаг1", а не должен.

# language: ru
@tree

Функционал: Сценарный тест биллинга

Как Разработчик
Я хочу проверить работоспособность биллинга 
Чтобы Михалыч был доволен 

Контекст: 
    Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: сценарий работы в биллинге

    Когда я делаю Шаг1. Создать нового партнера и контрагента для него
            Когда Создать новую пару партнера и контрагента
                Когда Я создаю и запоминаю ПартнераИКонтрагента с случайными реквизитами
            Тогда я проверяю что он создался
                Тогда открылось окно "Партнеры"
                И  в списке есть запомненый Партнер
    Когда я делаю Шаг 2. Первичная поставка
        Когда я создаю новую спецификацию 1. Период действия с 1 января
            Когда я создаю Спецификацию с датой начала периода действия "01.01.2017"
        И Добавить "Поставку" с января по правилу "Постоянная: КЮ за аванс 2 мес.+ 1 мес и КД подарок"
            И     в ТЧ "УсловияСпецификации" я нажимаю на кнопку "Поставка"
            Тогда открылось окно "Поставка новых дистрибутивов (создание)"
            И     я открываю выпадающий список "Прейскурант"

**Comment by Pr-Mex** [comment]
Решено.

**Comment by Agrajaga** [comment]
Теперь содержимое первой области закидывает внутрь области контекста (1). И если шаг верхнего уровня не имеет вложений, то он попадает внутрь предыдущего (2).
![_tree](https://cloud.githubusercontent.com/assets/22379662/23646446/e4c32e30-0321-11e7-874a-0d98562afb28.jpg)
Содержимое фичи:
`@tree

Функционал: Сценарный тест биллинга

Как Разработчик
Я хочу проверить работоспособность биллинга 
Чтобы Михалыч был доволен 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: сценарий работы в биллинге

	Когда я делаю Шаг1. Создать нового партнера и контрагента для него
		Когда Создать новую пару партнера и контрагента
			Когда Я создаю и запоминаю ПартнераИКонтрагента с случайными реквизитами
		Тогда я проверяю что он создался
			Тогда открылось окно "Партнеры"
			И  в списке есть запомненый Партнер
	Тогда Шаг1 - пройден
	Когда я делаю Шаг 2. Первичная поставка
		Когда я создаю новую спецификацию 1. Период действия с 1 января
			Когда я создаю Спецификацию с датой начала периода действия "01.01.2017"
		И Добавить "Поставку" с января по правилу "Постоянная: КЮ за аванс 2 мес.+ 1 мес и КД подарок"
			И     в ТЧ "УсловияСпецификации" я нажимаю на кнопку "Поставка"
			Тогда открылось окно "Поставка новых дистрибутивов (создание)"
			И     я открываю выпадающий список "Прейскурант"
	Когда я делаю Шаг 3
		Когда Создать новую пару партнера и контрагента
			Когда Я создаю и запоминаю ПартнераИКонтрагента с случайными реквизитами
		Тогда я проверяю что он создался
			Тогда открылось окно "Партнеры"
			И  в списке есть запомненый Партнер
	Когда я делаю Шаг 4
	Когда я делаю Шаг 5
		Когда Создать новую пару партнера и контрагента
			Когда Я создаю и запоминаю ПартнераИКонтрагента с случайными реквизитами
		Тогда я проверяю что он создался
			Тогда открылось окно "Партнеры"
			И  в списке есть запомненый Партнер
	Когда я делаю Шаг 6
	Когда я делаю Шаг 7
`

**Comment by Agrajaga** [comment]
А с точки зрения "Геркина" при построении иерархического дерева величина отступа должна влиять на глубину иерархии (т.е. поставили 3 таба - значит уровень строки третий, вне зависимости от предыдущих строк)?

**Comment by Pr-Mex** [comment]
@Agrajaga 
1. С точки зрения классического Gherkin - никакой иерархии шагов нет. Тег @tree поддерживается только Vanessa-Behavior (в рамках расширения языка - Turbo Gherkin). В Vanessa-Behavior уровень определяется тем как идут шаги друг за другом - т.е. три таба не обязательно означают третий уровень.
2. Скинь фичу на обменник, в которой у тебя неверно строится иерархия шагов. У меня не получается воспроизвести твой пример у себя. Всё верно строится.

**Comment by Agrajaga** [comment]
ссылка на фичу https://drive.google.com/open?id=0B8fCN-TCC7vGbWJBOGpBa0U2Vmc

**Comment by Pr-Mex** [comment]
@Agrajaga 
Проверь на новой версии VB.

**Comment by Agrajaga** [comment]
Да, сейчас все корректно. Спасибо

**Comment by Pr-Mex** [comment]
Закрываю.
