### ISSUE TITLE
Проблема с ЗапретитьВыполнениеШагов

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#53]
Если был вызван метод ЗапретитьВыполнениеШагов(), тогда внутри теста можно сделать таймер, но нельзя вызвать исключение для шага, т.к. vb его уже не поймает.

**Comment by Pr-Mex** [comment]
Сделано.
Теперь можно делать так:
Ванесса.ПродолжитьВыполнениеШагов(Истина);
И тогда шаг будет помечен как **Failed**

**Comment by git22ura** [comment]
Вопрос. А как причину падения указать? Хотелось бы вроде:
```
	Если ТекущаяДата()>ДатаЗавершенияОжидания Тогда
		ОтключитьОбработчикОжидания("ОжидаемКогдаТабДокЗаполнится");
		Ванесса.ПродолжитьВыполнениеШагов(Истина,"Не дождались заполнения табличного документа с именем <"+ИмяРеквизита+">");
	КонецЕсли;

```

**Comment by alehinsasha** [comment]
+1
