### ISSUE TITLE
Метод не может быть вызван для данного объекта (Цена)

### ISSUE THREAD

**Issue by SemyonAT** [silverbulleters/vanessa-behavior#541]
```Gherkin
Функционал: Заполнение табличной части документа
   Как Тестер
   Я хочу Чтобы заполнилась цена и количество в табличной части документа в УТ 11 План-продаж

Контекст:
  Дано: 1.102
  И 8.3.9.2170
  и Управление торговлей, редакция 11 (11.3.1.142)

Сценарий: Заполнение табличной части
  Допустим: В документе план-продаж заполняю табличную часть 
  Когда: Ввел Номенклатуру и единицу измерения и перехожу к вводу цены
  Тогда: Метод не может быть вызван для данного объекта (Цена)

08.03.2017 0:37:49 {ВнешняяОбработка.РаботаСИнтерфейсом.Форма.Форма.Форма(1772)}: Ошибка при вызове метода контекста (ВвестиТекст): Метод не может быть вызван для данного объекта (Цена): Метод не может быть вызван для данного объекта (Цена); ИмяФайла=C:\Tools\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf, ИмяПроцедуры=ВТЧВПолеЯВвожуТекст, версия VB=ver 1.102, версия платформы=8.3.9.2170, режим совместимости=Версия8_3_8

**Comment by Pr-Mex** [comment]
@SemyonAT 
Тут возможны варианты:
1. Либо был найден не тот элемент формы
2. Либо он не доступен в данный момент
3. Либо он не видимый в данный момент

Посмотрите в отладке - какой элемент формы был найден и что с ним происходит.

**Comment by SemyonAT** [comment]
Спасибо за помощь, проблема была в видимости. Использовал ТекущаяВидимость() и ТекущаяДоступность().
Подскажите а как вы решаете проблему когда колонки генерируются с использованием в имени уникального идентификатора. Пример xml ниже.
<FormField name="ТоварыПоПериодамЦена_d59778a6_28ae_4154_9da4_6ca6c9c35256" title="Цена">
									<activate/>
									<inputText text="1,00"/>
								</FormField>

**Comment by SemyonAT** [comment]
FormField name="ТоварыПоПериодамЦена_d59778a6_28ae_4154_9da4_6ca6c9c35256"

**Comment by alehinsasha** [comment]
При поиске элемента формы можно использовать символ *.
Например: ТоварыПоПериодамЦена*

**Comment by nixel2007** [comment]
Предполагаю, что @alehinsasha где-то потерял экранирование звездночки :) `*`

**Comment by SemyonAT** [comment]
Проблему решил через загрузку xml. Так как полей с одинаковым именем и разными идентификаторами несколько, а точнее за какое количество месяцев заполняется план столько полей с одинаковыми наименованиями и разными идентификаторами поэтому никак не воспользоваться механизмом фичи из воздуха. Спасибо.

**Comment by Pr-Mex** [comment]
@SemyonAT 
Механизм фич из воздуха тут также можно использовать.
Просто ищи элементы не по заголовку а по имени.
```
"И     в поле с именем "Наименование" я ввожу текст "111"
```

**Comment by SemyonAT** [comment]
Проблема что имена с идентификаторами и понять какой отвечает за какой период нельзя (точнее можно если разобрать алгоритм как он их преобразует в периоды, но я же не могу в момент выполнения сценария пере генерировать имена колонок в фиче файле).
Код проверки поведения автоматически генерируется так:
ПолеЦена = ОкноПриложенияПланПродажСозданиеФормаПланПродажСоздание.НайтиОбъект(Тип("ТестируемоеПолеФормы"), "Цена", "ТоварыПоПериодамЦена_dc289482_739a_4d14_b931_8dbf807fd64e");
ПолеЦена = ОкноПриложенияПланПродажСозданиеФормаПланПродажСоздание.НайтиОбъект(Тип("ТестируемоеПолеФормы"), "Цена", "ТоварыПоПериодамЦена_dc289482_739a_4d14_b931_8dbf807fd64e");
	ПолеЦена.ВвестиТекст("1 232,00");

**Comment by Pr-Mex** [comment]
Закрываю.
