### ISSUE TITLE
Фичи из библиотек VB не подгружаются полностью

### ISSUE THREAD

**Issue by git22ura** [silverbulleters/vanessa-behavior#545]
Когда используется несколько версий VB на Jenkins возможны случаи, что не всегда фичи прогружаются. В частности, у меня грузились только 2 из 160. Помогал только сброс кеша.
Решение - не загружать фичи из кеша. 
Как-то так:
```
Если НЕ Объект.ЗапускИзКоманднойСтроки Тогда
	ВосстановитьНастройкиИзХранилищаТаблицаИзвестныхStepDefinition("ТаблицаИзвестныхStepDefinition","ТаблицаИзвестныхStepDefinition");
КонецЕсли;
```

**Comment by Pr-Mex** [comment]
@git22ura  Вставил твой код.
Закрываю.
