### ISSUE TITLE
Исключение шагов для автоинструкций

### ISSUE THREAD

**Issue by SkyPunster** [silverbulleters/vanessa-behavior#548]
```Gherkin
Функционал: Исключение шагов для автоинструкций
   Как разработчик на платформе 1С:Предприятие
   Я хочу иметь инструмент исключения сервисных шагов из генерации автоинструкции

Сценарий: Создание feature-файла при сборе требований
  Допустим: Я собираю требования с заказчика
  И я указал тег @tree в feature-файле
  И я указал тег @AutoIntstructions

  Когда: Я записываю требования заказчика я формирую первый уровень дерева
  Тогда: Эти шаги попадают в автоинструкцию (озвучка, текст, скриншоты)
  
  Когда я уточняю feature-файл для проверки поведения (кнопконажималко+проверка данных)
  Тогда я формирую вложенные шаги (второй уровень дерева)
  И эти шаги не попадают в автоинструкцию, но выполняются.
```

**Comment by Pr-Mex** [comment]
@SkyPunster 
Надо обдумать.
Я бы не стал завязываться на уровни шагов.
Можно, например, указать в служебном теге список групп - которые не должны попадать в инструкцию. 
```
@IgnoreInAutoIntstructions=Группа1;Группа2
```
Тогда каждый сам сможет настроить как ему надо.

**Comment by SkyPunster** [comment]
Дополню: Было бы неплохо исключать не только шаги, но и сценарии. Способ который я описал изначально это только например, в принципе подойдет и конфиг в котором можно было бы указывать как-то что нужно в автоинструкцию пускать, а что нет чтобы можно было управлять этим.

**Comment by 1cto** [comment]
Похожего в #260 хотел. С деревом тоже была такая мысль. А скриншоты как делать? на каждый шаг второго уровня? Только на первом уровне? Можно ребёнка вместе с водой выплеснуть.
Не помню уж кто рекомендовал - делать для инструкций отдельный сценарий и помечать его соотв. тегом @instructions, и в нём только те шаги, которые нужны для инструкции. И для формирования документации делать отдельную сборку с этим тегом. Но это не отменяет того, что технические шаги всё равно попадут в инструкции.
@Pr-Mex поэтому полезность тега tree всё также сомнительна ;-)

**Comment by Pr-Mex** [comment]
Решено. Надо использовать новый синтаксис автоинструкций.

**Comment by nixel2007** [comment]
@Pr-Mex можешь рассказать про этот новый синтаксис?

**Comment by Pr-Mex** [comment]
@nixel2007 
Он описан в справке.
![image](https://user-images.githubusercontent.com/8627416/33796070-53413d3c-dcfe-11e7-8eba-e17e70fdd375.png)

**Comment by Pr-Mex** [comment]
Плюс вот фича с примером использования
https://yadi.sk/d/FWwsraxI3PCsVz

**Comment by Pr-Mex** [comment]
Плюс вот как выглядит результат
https://www.youtube.com/watch?v=_igegXQHz60

**Comment by nixel2007** [comment]
@Pr-Mex а, это видео.

**Comment by Pr-Mex** [comment]
@nixel2007 
Да.
