### ISSUE TITLE
Различные баги при попытке выполнить сценарии для разных каталогов проекта

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#55]
версия 0.810 (develop)
Различные баги при попытке выполнить сценарии для разных каталогов проекта
В итоге двойное впечатление: видно, что работа проделана большая, иконки понравились в дереве сценариев, но результата нету
@Pr-Mex посмотри. можете отпугнуть новых пользователей :(

Проект находится в каталоге T:\Projects\vanessa-behavoir

Например, для T:\Projects\vanessa-behavoir\features\SelfTests
>{Форма.УправляемаяФорма.Форма(1644)}: Не известная ошибка в ПолучитьКонтекстТестаПоАдресСнипета. АдресСнипета=T:\Projects\vanessa-behavoir\features\SelfTests\step_definitions\AdditionTest.epf
		ВызватьИсключение "Не известная ошибка в ПолучитьКонтекстТестаПоАдресСнипета. АдресСнипета="+АдресСнипета;

![image](https://cloud.githubusercontent.com/assets/2920817/9819870/223b8e66-58b9-11e5-98cd-61afd8d2564a.png)

Для других каталогов (каталог tests и др) выдаются другие ошибки :(

@Pr-Mex У тебя CI настроен? все тесты проходят?

**Comment by Pr-Mex** [comment]
Конкретно этот скриншот - это старый файл. Он недолжен работать. Почищу легаси как до компа доберусь. Спасибо что сказал.

**Comment by Pr-Mex** [comment]
У меня тесты проходят из каталога tests

**Comment by Pr-Mex** [comment]
Там выбирай каталог либо для обычных форм, либо для УФ.

**Comment by artbear** [comment]
Я же говорю, что пробовал разные варианты :(
Не сработало выполнение при загрузке из любых каталогов проекта :( это
сильно и поразило, тк пилишь активно

пт, 11 Сен 2015, 19:33, Pr-Mex <notifications@github.com>:

**Comment by Pr-Mex** [comment]
1. Убрал доступность с поля КаталогИнструментов.
2. Прогнал все тесты - всё работает.

Чтобы прогнать тесты надо:
Если ты открыл vanessa-behavior.epf в режиме УФ то надо загрузить фичи из каталога tests\ManagedApplicationTests
Иначе из каталога tests\OrdinaryApplicationTests

**Comment by artbear** [comment]
Да, после твоих исправлений в выходные сценарии из
tests\ManagedApplicationTests
заработали. Это хорошо.
Но еще остаются вопросы по прохождению других тестов, они-то не проходят.
Еще вопрос - зачем нужны остальные фичи и сценарии для них, если они не
работоспособны?

сб, 12 сент. 2015 г. в 20:47, Pr-Mex <notifications@github.com>:

**Comment by Pr-Mex** [comment]
Давай конкретики.
Какие конкретно ошибки остались.

**Comment by artbear** [comment]
Еще не проверял.
Поясни по назначению различных каталогов, в которых есть файлы фич и
реализованные сценарии.
Вот часть из них падала, я не про бух-фичу :)

пн, 14 сент. 2015 г. в 10:40, Pr-Mex <notifications@github.com>:

**Comment by Pr-Mex** [comment]
Надо просто нажимать на кнопку "загрузить фичи" и Выполнять сценарии. Руками в поля диалога ничего вводить не надо.

**Comment by artbear** [comment]
Вот с чего ты взял, что я что-то руками вносил?
использовал только базовые возможности - загрузить и выполнить, полный
автомат, никаких ручных действий

пн, 14 сент. 2015 г. в 13:54, Pr-Mex <notifications@github.com>:

**Comment by Pr-Mex** [comment]
Тогда жду инфы о том, что сейчас не работает.

**Comment by artbear** [comment]
Что за T:\Projects\vanessa-behavoir\tests\Instructions ? не работают

пн, 14 сент. 2015 г. в 14:03, Pr-Mex <notifications@github.com>:

**Comment by artbear** [comment]
Странный, неработающий сценарий features_examples\SelfTests.
14.09.2015 14:17:22 Пустой адрес снипета у шага: Я передал первый параметр
сложения 2

Может быть, его вообще убрать ? или доработать, чтобы он полноценно работал?

пн, 14 сент. 2015 г. в 14:16, Артур Аюханов <aartbear@gmail.com>:

**Comment by artbear** [comment]
Похоже, что фичи tests\ManagedApplicationTests\ГенерацияEPF
и ПерегенерацияEPF не работают
Загружаю их индивидуально или в составе tests
Везде пишет про пустой адрес снипета

пн, 14 сент. 2015 г. в 14:18, Артур Аюханов <aartbear@gmail.com>:

**Comment by artbear** [comment]
сейчас совершенно непонятно, как завершилось выполнение сценариев :(
прогнал все из папки tests, часть зеленых, а вот ГенерацияEPF
и ПерегенерацияEPF вообще не выполнились, верно?
и значит, не все сценарии прошли.
продукт не сообщает мне об успешности, неуспешности или
пропущенных/нереализованных шагах :( не гуд!

пн, 14 сент. 2015 г. в 14:22, Артур Аюханов <aartbear@gmail.com>:

**Comment by Pr-Mex** [comment]
Ок. Посмотрю.

**Comment by Pr-Mex** [comment]
Не актуально. Закрываю.
