### ISSUE TITLE
Падение TestClient при создании Внутреннего документа в 1С Документооборот

### ISSUE THREAD

**Issue by ZhdanovR** [silverbulleters/vanessa-behavior#568]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: <Создание сценария>
   Как <роль пользователя>
   Я хочу <Запись сценария тестирования>

Контекст:
  Дано: <актуальная из ветки develop>
  И 1С:Предприятие 8.3 (8.3.9.2170) 
  И MS SQL Sever 2014
  И Документооборот 8 КОРП, редакция 2.1 (2.1.10.2)


  Когда: 
Подключается TestClient
И включается запись поведения клиента
и в  TestClient Нажимается кнопка "Создать внутренний документ"

  Тогда: Происходит падение Test Client

**Comment by hawk911** [comment]
По падению платформы -  это вам надо, на техподдержку 1С писать -  v8@1c.ru.

**Comment by ZhdanovR** [comment]
Самое интересное, что  падение возникает только в ДО и при создании внутреннего документа. Все остальные объекты записываются без проблем. Может кто сталкивался? 
Пробовал на файловой и серверной, на чистой системе - результат один

**Comment by hawk911** [comment]
Попробуйте воспроизвести ошибку БЕЗ сторонних механизмов.
99% - это ошибка платформы
т.к. краш приложения - это точно ошибка платформы
1. Напишите кодом подключение TectClient к ДО. Вот здесь описано как это сделать http://xn----1-bedvffifm4g.xn--p1ai/news/%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5-%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B2-1%D1%81-8-3/ 
2. Высылайте пример воспроизведения ошибки на адрес техподдержки 1С.
