### ISSUE TITLE
Не грузится макет с записями регистров сведений, макет выгружен в генераторе данных xUnitFor1C 3.0.0.8 и выше (4.1.0.0 или 4.1.1.0)

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#579]
Не грузится макет с записями регистров сведений, макет выгружен в генераторе данных xUnitFor1C 3.0.0.8 и выше (4.1.0.0 или 4.1.1.0)

Выдается ошибка
```
27.04.2017 17:01:58 Шаг (Допустим Я создаю fixtures по макету "ДопускАккредитуемыхКТестированию") 
не выполнен.

27.04.2017 17:01:58 {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(8249)}: 
Ошибка при вызове конструктора (РегистрСведенийКлючЗаписи.РолиЧленовКомиссии): 
Недопустимое значение параметра (параметр номер '1') 
(Ключ должен содержать 3 значений. Передано 4); 
ИмяФайла=C:\projects\SB\vanessa-behavior\features\Libraries\VB\
step_definitions\СозданиеFixturesПоМакетуОбработкиФичи.epf, 
ИмяПроцедуры=ЯСоздаюFixturesПоМакету, 
версия VB=ver 1.1.011, версия платформы=8.3.10.2168, режим совместимости=НеИспользовать
```

Тестирование загрузки этого же макета в генераторе данных из xUnitFor1C 4.1.0.0 или 4.1.1.0 ошибок не выдает

**Comment by artbear** [comment]
Выгружаю эти же данные в генераторе от xUnitFor1C 3.0.0.8
все равно не работает с этой же ошибкой

```
27.04.2017 17:11:16 Шаг (Допустим Я создаю fixtures по макету "ДопускАккредитуемыхКТестированию") не выполнен.
27.04.2017 17:11:16 {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(8249)}: Ошибка при вызове конструктора (РегистрСведенийКлючЗаписи.РолиЧленовКомиссии): Недопустимое значение параметра (параметр номер '1') (Ключ должен содержать 3 значений. Передано 4); ИмяФайла=C:\projects\SB\vanessa-behavior\features\Libraries\VB\step_definitions\СозданиеFixturesПоМакетуОбработкиФичи.epf, ИмяПроцедуры=ЯСоздаюFixturesПоМакету, версия VB=ver 1.1.011, версия платформы=8.3.10.2168, режим совместимости=НеИспользовать
```

**Comment by artbear** [comment]
В итоге с макетами xUnitFor1C стало невозможно работать в VB :(

**Comment by artbear** [comment]
Не поленился и скачал xUnitFor1C 3.0.0.3, совместимость с которой заявлена в VB.

Такая же проблема :(

Как макетами народ пользуется, непонятно.

**Comment by artbear** [comment]
Решено в #580

**Comment by artbear** [comment]
Оказывается, проблема именно в VB в УФ и работе с регистрами сведений, подчиненными регистраторам.

В управляемой форме есть метод `ПолучитьКлючиЗаписиРСПоНаборуЗаписейРС`
в нем выдается ошибка на строке 		
`КлючЗаписи =  Новый("РегистрСведенийКлючЗаписи." + ИмяРС, ПараметрыКонструктора);`

Метод должен выдать ключи записи для использования на клиенте, но из-за использования конструктора баг.

Кажется, недавно кто-то что-то правил по РС.

**Comment by Tushkan** [comment]
@artbear было предложение в #570

**Comment by naa4sb** [comment]
В xUnit конструктор был поправлен. С учетом #580 всё еще есть проблема?

28 Апр 2017 г. 3:29 PM пользователь "Belyakov Alexandr" <
notifications@github.com> написал:

**Comment by artbear** [comment]
Проблема на стороне VB
в xUnit этого кода нет, или я на него не попадаю.

Я не нашел другого варианта, кроме отключения использования этого метода.
Т.к для регистров сведений, подчиненных регистратору, ошибка :(

**Comment by Pr-Mex** [comment]
@naa4sb 
можешь показать какой код xUnit ты имеешь ввиду?

**Comment by 1cgh** [comment]
Блин. А он не в плагине, а в уф. Тогда код в отмененном пр моем)

**Comment by 1cgh** [comment]
Т.е. в вб его нет сейчас

**Comment by 1cgh** [comment]
@artbear проверь теперь. кстати, почему в вб старая версия плагина сериализатора по сравнению с develop xUnit'а была использована?

**Comment by artbear** [comment]
Откуда инфа, что старая версия?
вроде бы я взял из своего рабочего каталога хЮнит

**Comment by 1cgh** [comment]
@artbear сорян, это я не с той веткой сравниваю опять. сделать PR плагина в xUnit?

**Comment by artbear** [comment]
да, сделай

**Comment by artbear** [comment]
Только не забудь описать свои изменения.
Что-то многовато их, если смотреть через Гитхаб

**Comment by Pr-Mex** [comment]
Решено. Если проблема возникнет вновь - пишите в эту ветку.
