### ISSUE TITLE
Падение шага, в тексте которого есть знак дефиса

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#595]
Есть шаг со знаком дефиса, например, `действие - выполнить`
и есть проблемы 
+ с генерацией кода для него
получается экспортная процедура с одним параметром, что неверно.
+ с выполнением полученного кода
Получается ошибка 
`Выполнить(Команда)	{(1,1)}: Ожидается выражение`
```
04.05.2017 11:23:38 {ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(4280)}: Ошибка компиляции при вычислении выражения или выполнении фрагмента кода: {(1,156)}: Ожидается выражение; ИмяФайла=C:\projects\1.epf, ИмяПроцедуры=ДействиеВыполнить, версия VB=ver 1.1.022, версия платформы=8.3.10.2168, режим совместимости=НеИспользовать
```

В строке модуля УФ 4280 код `Выполнить(Команда)`
 и неверный текст команды в переменной
```
Обработка.ДействиеВыполнить(-)
```
знак дефиса без кавычек !!

**Comment by Pr-Mex** [comment]
@artbear 
Дай пример фичи.
У меня не воспроизводится.

**Comment by Pr-Mex** [comment]
Решено.
