### ISSUE TITLE
Неоднозначное выполнение команды "Выполнить данный сценарий сначала" в зависимости от контекста вызова

### ISSUE THREAD

**Issue by 1cto** [silverbulleters/vanessa-behavior#597]
Имеется такая фича:
```
#language: ru
Функционал: тест воспроизведения неотработки запуска одного сценария

Контекст: пауза 5
		И пауза 4

Структура сценария: Проверка 2
    Дано пауза <Пауза>
    И пауза <Пауза>
    Когда пауза <Пауза>
    Тогда пауза <Пауза>
        И пауза <Пауза>
 
Примеры:
    |Пауза |
    |1 |
    |2 |
    |3 |

Структура сценария: Проверка 3
    Дано пауза <Пауза>
    И пауза <Пауза>
    Когда пауза <Пауза>
    Тогда пауза <Пауза>
        И пауза <Пауза>
 
Примеры:
    |Пауза |
    |1 |
    |2 |
    |3 |

Сценарий: Проверка 4
    Дано пауза 1
    И пауза 1
    Когда пауза 1
    Тогда пауза 1
        И пауза 1
```
Когда в ВБ 1.1.022 мы выбираем вот такой вариант запуска:
![image](https://cloud.githubusercontent.com/assets/15178930/25713206/a01a2258-30fc-11e7-91ec-1c8033e1c4b8.png)
Тогда ВБ сообщает что все сценарии отработаны, но ничего не отрабатывает (хотя ожидалось, что выполнится конкретный пример структуры сценария)

Когда в ВБ 1.1.022 мы выбираем вот такой вариант запуска:
![image](https://cloud.githubusercontent.com/assets/15178930/25713302/eeecb1f2-30fc-11e7-83dc-15a697fd5a59.png)
Тогда ВБ сообщает что все сценарии отработаны, но ничего не отрабатывает (хотя ожидалось, что выполнится вся структуры сценария)

Когда в ВБ 1.1.022 мы выбираем вот такой вариант запуска:
![image](https://cloud.githubusercontent.com/assets/15178930/25713347/152f6eb8-30fd-11e7-9cfd-734e04d44997.png)
Тогда ВБ отрабатывает запуск выбранной строки примеров структуры сценариев, а также последнего сценария (хотя последний сценарий выполниться не должен)

**Comment by Pr-Mex** [comment]
Решено.
