### ISSUE TITLE
Ошибка закрытия test client

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#600]
Если в настройках
  "ЗакрытьTestClientПослеЗапускаСценариев": "Истина"
а открытых testclient-ов нет (или, скорее всего, они в принципе не открывались), то получается  ошибка:
![2017-05-09_12-15-04](https://cloud.githubusercontent.com/assets/12106756/25836462/2df6f7ce-34b1-11e7-8b05-5ba7e57e4fcb.png)

**Comment by Pr-Mex** [comment]
Понял. Проверю у себя.

**Comment by Pr-Mex** [comment]
Решено.
