### ISSUE TITLE
Произошла исключительная ситуация (0x80070002)

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#601]
Во всех местах, где используется 
`wshShell.Run(ИмяВременногоФайла)`
нужна обертка в кавычки на случай, если путь будет с пробелами.
Также нужна обертка для всех путей внутри batников, например:
`ТекстКоманды = "netstat -ano > " + ИмяВременногоФайла;`
Если в ИмяВременногоФайла будет путь с пробелами, то работать ничего не будет

**Comment by Pr-Mex** [comment]
Понял. Проверю у себя.

**Comment by Pr-Mex** [comment]
Решено.
