### ISSUE TITLE
Неверная генерация имени обработки реализации шага, если имя файла фичи не является идентификатором 1С

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#602]
Неверная генерация имени обработки реализации шага, если имя файла фичи не является идентификатором 1С
В этом случае всегда генерится имя "Обработка" вместо уникального имени обработки на базе имени файла фичи

![image](https://cloud.githubusercontent.com/assets/2920817/25989848/561c5e18-3706-11e7-9ec4-a480e8d45812.png)

![image](https://cloud.githubusercontent.com/assets/2920817/25989822/43d6c9be-3706-11e7-9ca0-9918d9421c78.png)

**Comment by artbear** [comment]
Предлагаю в ВБ добавить генерацию уникального имени обработки - например, по имени папки-родителя и имени файла обработки

генерация имени обработки только по имени файла недостаточно.
например, у меня есть однотипные фичи - 01-подготовка, 02-процесс, 03-документ, а вот родители-папки разные - 01-Тестирование, 02-Практика, 03-Собеседование

**Comment by artbear** [comment]
Баг очень сильно мешает при загрузке макетов

**Comment by artbear** [comment]
мне помогает исправление имени внешней обработки на уникальное имя,
перезапуск 1С и повторное выполнение фич через ВБ

**Comment by Pr-Mex** [comment]
Создал задачу по уникальному имени обработки.
https://github.com/silverbulleters/vanessa-behavior/issues/603

**Comment by Pr-Mex** [comment]
> Неверная генерация имени обработки реализации шага, если имя файла фичи не является идентификатором 1С
В этом случае всегда генерится имя "Обработка" вместо уникального имени обработки на базе имени файла фичи

Это исправлено в 1.1.028.

**Comment by Pr-Mex** [comment]
Эту задачу закрываю.
