### ISSUE TITLE
Перестали генерироваться epf

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#604]
Версия: 1.1.025

Перестали генерироваться файлы epf

![1](https://cloud.githubusercontent.com/assets/12106756/26187937/6338d922-3bc6-11e7-9b19-d62829c30669.png)

![2](https://cloud.githubusercontent.com/assets/12106756/26187938/655be8b6-3bc6-11e7-94a2-7c924ee39f3e.png)

![3](https://cloud.githubusercontent.com/assets/12106756/26187941/67cb8c14-3bc6-11e7-8bc5-a6b2f244efea.png)

**Comment by Pr-Mex** [comment]
Согласно справке, теперь для генерации epf на ПК надо установить платформу 8.3.10.
![image](https://cloud.githubusercontent.com/assets/8627416/26273768/19e460a4-3d40-11e7-9d8f-2978557dd53c.png)

Т.е. разрабатывать вы можете на любой версии платформы, хоть на 8.2, но надо *дополнительно* установить 8.3.10

**Comment by Pr-Mex** [comment]
Закрываю.
