### ISSUE TITLE
Ошибки при выполнении шагов

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#607]
У меня возникают какие-то странные ошибки при выполнении сценариев:

```
{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(5361)}: Индекс находится за границами массива
			РезультатПрохожденияШага = РезультатПрохожденияТестовШагов[РезультатПрохожденияТестовШагов.Количество() - 1];
```

Не знаю даже как их классифицировать.
Может подскажите как с ними бороться или что можно привести в пример для воспроизведения.
Снял видео.
Вот ссылка: https://yadi.sk/i/LYaWu56X3JXAR7
Сама ошибка с 3:25

**Comment by Pr-Mex** [comment]
@viskvortsov 
это вроде бы чинили уже.
Попробуйте не версии 1.1.033.

**Comment by Pr-Mex** [comment]
Эта версия стабильна.
http://ci.silverbulleters.org/job/Vanessa-Behavior-Develop/782/allure/

**Comment by viskvortsov** [comment]
Воспроизводится на версии 1.1.033

**Comment by viskvortsov** [comment]
Не знаю как воспроизвести ошибку.
Могу подключить к себе, если это поможет.

**Comment by Pr-Mex** [comment]
Подскажите, если выполнить только один сценарий **Добавление видов компенсации** - ошибка воспроизводится?
![image](https://cloud.githubusercontent.com/assets/8627416/26519967/8726fbda-42d2-11e7-9a32-0d01cfe8b486.png)

**Comment by Pr-Mex** [comment]
Ещё хочется глянуть в epf, в которой реализован шаг **Тогда компенсация записана с наименованием**
![image](https://cloud.githubusercontent.com/assets/8627416/26519980/b9aa787a-42d2-11e7-8f68-ab26bfc339bb.png)

**Comment by Pr-Mex** [comment]
Причём на видео у вас возникла ошибка - **Значение не является значением объектного типа**.
А в issue вы пишите **Индекс находится за границами массива**


![image](https://cloud.githubusercontent.com/assets/8627416/26520198/b00444f0-42d6-11e7-93ae-ecedccf9c9d9.png)

Опишите подробнее что у вас происходит и как часто возникает.
Также проверьте как работает выполнение одного сценария.
![image](https://cloud.githubusercontent.com/assets/8627416/26520210/fe5aaff4-42d6-11e7-8e2a-ed344366a30f.png)

**Comment by viskvortsov** [comment]
> Причём на видео у вас возникла ошибка - Значение не является значением объектного типа.
> А в issue вы пишите Индекс находится за границами массива

Индекс за границами массива там тоже есть. Идет сразу за этой ошибкой.
Полагаю, что они как то взаимосвязаны.

Выполнение сценария по одному похоже работает.
Ошибка эта всегда возникает при прогоне всех сценариев.
На разных машинах воспроизводится.

Добавление видов компенсации - отдельно воспроизводится
Обработка: https://yadi.sk/d/5Myb0gf93JaiDe

**Comment by Pr-Mex** [comment]
@viskvortsov 
Похоже дело в том, что вы не отключаете обработчик ожидания при завершении шага.
И таймер продолжает работать дальше.
![image](https://cloud.githubusercontent.com/assets/8627416/26532228/c0b53da8-4403-11e7-9754-1e49aff0661c.png)

**Comment by Pr-Mex** [comment]
@viskvortsov 
также учтите, что ассерты (ПроверитьИстину) не будут работать, когда вы используете асинхронный шаг.
Они работают только в обычных шагах.

**Comment by Pr-Mex** [comment]
Закрываю. Переоткройте задачу если не удалось решить проблему.
