### ISSUE TITLE
Ошибка при загрузке фич

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#609]
Вот такую ошибку сегодня ловлю в одной из баз:

![2017-05-30_14-02-26](https://cloud.githubusercontent.com/assets/12106756/26571981/66a7a37e-4542-11e7-9f6f-9f5f364e49ad.png)

**Comment by hawk911** [comment]
Добрый день. 
Выложите на обменник feature файл, пожалуйста.

**Comment by viskvortsov** [comment]
Их много.
Попробую найти тот, который сбоит

**Comment by Pr-Mex** [comment]
@viskvortsov 
Как успехи?
Получилось разобраться?

**Comment by Pr-Mex** [comment]
Закрываю.
