### ISSUE TITLE
Ошибка поиска реквизита формы по имени

### ISSUE THREAD

**Issue by asd8703** [silverbulleters/vanessa-behavior#615]
Если на форме находится поле "Поле" и группа "Поле"
Тогда любой шаг в котором используется вызов функции ```ПолеРеквизит = Ванесса.НайтиРеквизитОткрытойФормыПоЗаголовку(ИмяРеквизита,ИскатьПоИмени);``` вызовет ошибку - ```Обнаружено несколько полей с заголовком <Поле>```

Было бы правильно передавать в функцию тип искомого реквизита:

```bsl
&НаКлиенте
Функция НайтиРеквизитОткрытойФормыПоЗаголовку(ИмяРеквизита, ИскатьПоИмени = Ложь, ТипПоля = Неопределено) Экспорт
        Нашли = Ложь;
        МассивФорм = НайтиФормыТекущегоОкнаTestClient();
        Для каждого ТекущаяФорма Из МассивФорм Цикл

Если ИскатьПоИмени Тогда
МассивЭлементов = ТекущаяФорма.НайтиОбъекты(ТипПоля, , ИмяРеквизита);
Иначе
МассивЭлементов = ТекущаяФорма.НайтиОбъекты(ТипПоля, ИмяРеквизита);
КонецЕсли;
```

**Comment by nixel2007** [comment]
Для большинства шагов есть дублирующийся шаг с поиском по имени элемента. Его не хватит в вашем случае?

**Comment by asd8703** [comment]
использовать шаг вида ```И     В открытой форме из выпадающего списка с именем "КонтактнаяИнформацияПоле730ed1f4xb732x4d87xb8a0x792b6dc9a76e1" я выбираю "E-mail отсутствует"``` не очень информативно

**Comment by asd8703** [comment]
ну и соответственно, что если я ищу элемент выпадающего списка, то он точно не может иметь тип "ТестируемаяГруппаФормы"

**Comment by Pr-Mex** [comment]
@asd8703 
В целом согласен.
Сделаешь пулреквест?

**Comment by Pr-Mex** [comment]
Решено. Закрываю.
