### ISSUE TITLE
В табличном документ использовать * в определённых полях

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#621]
Бывают сценарии когда

* я проверяю работу нумератора документа и автоматического назначения даты
* а после этого проверяю движения по регистру

В таком случае

* у меня обязательные результаты в табличном документе это цифры которые легли в регистра, но дата документа движения и его номер меня в секции Тогда не волнуют

В таблице документа есть "библиотечный шаг" который обрабатывает "звёздочку" - то есть любое значение, нужно добавить такое же поведение в табличный документ

**Comment by allustin** [comment]
Вот здесь где-то нужно добавить функциональность

https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/vanessa-behavior/ObjectModule.bsl#L1665

**Comment by allustin** [comment]
заодно отладим новый сервер сборок

**Comment by Pr-Mex** [comment]
Решено. Теперь если в макете эталоне указана * - то в проверяемом макете может быть любое значение.
