### ISSUE TITLE
Шаг Если отображается как группировочный шаг

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#628]
Вопрос:
Почему шаг если может не опознаваться?
Беру шаг из типовой библиотеки - все хорошо.
Пишу свой условный шаг - он отображается в VB как просто группировочный и не выполняется

**Comment by 1cgh** [comment]
Приложите фичу, на которой проявляется проблема

**Comment by viskvortsov** [comment]
[Libraries.zip](https://github.com/silverbulleters/vanessa-behavior/files/1107188/Libraries.zip)

**Comment by 1cgh** [comment]
![2017-06-28 11 01 41](https://user-images.githubusercontent.com/24507052/27626591-4fd3141a-5bf1-11e7-99ab-b8232b414ef6.png)
![2017-06-28 11 02 03](https://user-images.githubusercontent.com/24507052/27626590-4fd11b4c-5bf1-11e7-80ff-cee7536da45e.png)
В VB шаги в дереве построены корректно, полностью в соответствии с содержимым файла.
Что не так?

**Comment by viskvortsov** [comment]
Шаг **Если** не становится условным шагом.
Хотя я ожидаю, что он будет условным и будет выполняться отдельно.
Графически это выглядит как наличие серого круга со стрелкой как для обычных шагов.

**Comment by 1cgh** [comment]
Речь про 'Если это не конфигурация...'?
Следующий шаг задан с дополнительным отступом,  поэтому этот шаг определяется как шаг-группа. Уберите лишний таб у следующего шага

**Comment by viskvortsov** [comment]
Посмотрите Условие.feature в репозитории VB в папке Libraries, чтобы понять о чем я говорю.

**Comment by 1cgh** [comment]
@viskvortsov 
а. насколько я понял, там должен просто параметр передаваться.
типа
	Если "УправлениеТорговлей" тогда

**Comment by 1cgh** [comment]
@Pr-Mex 
а в gherkin добавили if then? или это VB-самодеятельность, как tree?)
просто как на этот шаг в фиче смотрят сторонние инструменты типа пиклза того же

**Comment by Pr-Mex** [comment]
@1cgh 
тег tree необходимость при больших сценариях.
пиклзы смотрят отлично - т.к. это не противоречит ни чему из того что пиклз ждёт увидеть

**Comment by Pr-Mex** [comment]
@viskvortsov 
там ещё один параметр есть в процедуре 
Ванесса.ДобавитьШагВМассивТестов()
надо его указать

**Comment by 1cgh** [comment]
Я не про tree, с ним все ОК. Я про Если

28 Июн 2017 г. 8:58 PM пользователь "Pautov Leonid" <
notifications@github.com> написал:

**Comment by viskvortsov** [comment]
Поставил "Условие"
Не помогает

**Comment by viskvortsov** [comment]
А понял. Нужно было добавить параметр, а не ставить в последний.

**Comment by viskvortsov** [comment]
В принципе вопрос закрыт
