### ISSUE TITLE
Документировать создание скриншотов

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#631]
Можно устанавливать 
+ как `NirCMD`
  + http://www.nirsoft.net/utils/nircmd.zip
![image](https://user-images.githubusercontent.com/2920817/27960898-9c627758-6335-11e7-9ed4-b9c5217de763.png)

+ так и `IrfanView`

+ Важно только устанавливать 32-разрядные версии !!

для `NirCMD` Пример json-файла настройки фиксации скриншотов
```
    "ДелатьСкриншотПриВозникновенииОшибки": true,
    "СниматьСкриншотКаждогоОкна1С": true,
    "КаталогOutputСкриншоты": "$workspaceRoot/build/out/ScreenShots",
    "КомандаСделатьСкриншот": "nircmd savescreenshot "
```
или
для `IrfanView` Пример json-файла настройки фиксации скриншотов
```
    "ДелатьСкриншотПриВозникновенииОшибки": true,
    "СниматьСкриншотКаждогоОкна1С": true,
    "КаталогOutputСкриншоты": "$workspaceRoot/build/out/ScreenShots",
    "КомандаСделатьСкриншот": '"C:\Program Files (x86)\IrfanView\i_view32.exe" /capture=1 /convert='
```

Предлагаю добавить в FAQ

**Comment by Pr-Mex** [comment]
Решено.
