### ISSUE TITLE
Ошибка при открытии VB под веб-клиентом на Ghrome

### ISSUE THREAD

**Issue by vdm5** [silverbulleters/vanessa-behavior#633]
Функционал: Работа с VB в веб-клиенте 1С-приложения
 Как разработчик
 Я хочу запускать VB в веб-клиенте и выполнять "проигрывание" сценариев под веб-клиентом

Контекст:
 Дано: установленная версия VB 1.1.053
 И платформа 1С 8.3.10.2252
 и 1С: Управление холдингом 1.3 (1.3.7.7)

Сценарий: я открываю VB в конфигурации 1С:УХ, запущенной в режиме веб-клиента
 Когда: я открыл VB в конфигурации 1С:УХ, запущенной в режиме веб-клиента
 Тогда: открылось окно с ошибками времени выполнения с содержимым:

{(10701,22)}: Переменная не определена (ТипУзлаXML)
 Если XML.ТипУзла = <<?>>ТипУзлаXML.НачалоЭлемента Тогда
{(11049,22)}: Переменная не определена (ТипУзлаXML)
 Если XML.ТипУзла = <<?>>ТипУзлаXML.Текст Тогда
{(11053,22)}: Переменная не определена (ТипУзлаXML)
 Если XML.ТипУзла = <<?>>ТипУзлаXML.КонецЭлемента Тогда 
{(203,13)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы(Команда);
{(3096,13)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы("sh -c 'env > " + ИмяВременногоФайла + "'");
{(4921,13)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы(Команда);
{(8184,2)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
        <<?>>КомандаСистемы(Стр);
{(8688,4)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы("rm -Rf """ + ИмяФайла + """");
{(8703,4)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы("rm -Rf """ + ИмяФайла + """");
{(8722,4)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы("mv """ + Откуда + """ """ + Куда + """");
{(8902,17)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы(Команда);
{(8922,4)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы("mkdir -p """ + ИмяФайла + """");
{(8949,4)}: Процедура или функция с указанным именем не определена (КомандаСистемы)
 <<?>>КомандаСистемы("sh " + ИмяВременнгоФайла);
{(354,30)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоФайлаКоманды = <<?>>ПолучитьИмяВременногоФайла("bat");
{(3093,23)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоФайла = <<?>>ПолучитьИмяВременногоФайла();
{(4900,19)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ВременныйФайл = <<?>>ПолучитьИмяВременногоФайла("png");
{(6594,23)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ВременныйФайл = <<?>>ПолучитьИмяВременногоФайла("png");
{(8192,17)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8252,26)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ВременныйКаталогБазы = <<?>>ПолучитьИмяВременногоФайла();
{(8254,18)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8255,17)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаOUT = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8272,21)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ПутьКИсходникам = <<?>>ПолучитьИмяВременногоФайла();
{(8276,18)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8277,17)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаOUT = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8433,32)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ВременныйКаталогИсходников = <<?>>ПолучитьИмяВременногоФайла();
{(8510,22)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ВременноеИмяФайла = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8748,18)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8799,18)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8825,18)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(8933,22)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременногоЛог = <<?>>ПолучитьИмяВременногоФайла("log");
{(8939,24)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременнгоФайла = <<?>>ПолучитьИмяВременногоФайла("sh");
{(9019,21)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоEPF = <<?>>ПолучитьИмяВременногоФайла("epf");
{(9039,25)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ВременныйКаталогБазы = <<?>>ПолучитьИмяВременногоФайла();
{(9041,17)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(9042,16)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайлаOUT = <<?>>ПолучитьИмяВременногоФайла("txt");
{(9059,17)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(9060,16)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайлаOUT = <<?>>ПолучитьИмяВременногоФайла("txt");
{(10327,13)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайла = <<?>>ПолучитьИмяВременногоФайла("txt");
{(10672,21)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоXML = <<?>>ПолучитьИмяВременногоФайла("xml");
{(11315,24)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременногоФайла = <<?>>ПолучитьИмяВременногоФайла("txt");
{(11369,23)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоФайла = <<?>>ПолучитьИмяВременногоФайла("txt");
{(11370,21)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоBat = <<?>>ПолучитьИмяВременногоФайла("bat");
{(11407,23)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоФайла = <<?>>ПолучитьИмяВременногоФайла("txt");
{(11410,22)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременногоBat = <<?>>ПолучитьИмяВременногоФайла("bat");
{(11448,22)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременногоBat = <<?>>ПолучитьИмяВременногоФайла("bat");
{(12771,13)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайла = <<?>>ПолучитьИмяВременногоФайла("feature");
{(13092,12)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ЛогФайл = <<?>>ПолучитьИмяВременногоФайла("txt");
{(13251,17)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяФайлаЛога = <<?>>ПолучитьИмяВременногоФайла("txt");
{(14166,22)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременногоBat = <<?>>ПолучитьИмяВременногоФайла("bat");
{(14521,22)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
 ИмяВременногоBAT = <<?>>ПолучитьИмяВременногоФайла("bat");
{(14619,25)}: Процедура или функция с указанным именем не определена (ПолучитьИмяВременногоФайла)
        ИмяВременногоFeature = <<?>>ПолучитьИмяВременногоФайла("feature");
{(13220,55)}: Процедура или функция с указанным именем не определена (XMLСтрока)
        СделатьСообщение("Активирую окно с координатами: " + <<?>>XMLСтрока(ТекКоординаты.x) + ";" + XMLСтрока(ТекКоординаты.y));
{(13220,90)}: Процедура или функция с указанным именем не определена (XMLСтрока)
        СделатьСообщение("Активирую окно с координатами: " + XMLСтрока(ТекКоординаты.x) + ";" + <<?>>XMLСтрока(ТекКоординаты.y));
{(13221,103)}: Процедура или функция с указанным именем не определена (XMLСтрока)
        ВыполнитьSikuliСкрипт(Объект.КаталогИнструментов + "\tools\Sikuli\ClickCoordinates.sikuli --args " + <<?>>XMLСтрока(ТекКоординаты.x) + " " + XMLСтрока(ТекКоординаты.y) , -1, Истина);
{(13221,138)}: Процедура или функция с указанным именем не определена (XMLСтрока)
        ВыполнитьSikuliСкрипт(Объект.КаталогИнструментов + "\tools\Sikuli\ClickCoordinates.sikuli --args " + XMLСтрока(ТекКоординаты.x) + " " + <<?>>XMLСтрока(ТекКоординаты.y) , -1, Истина);
{(15736,64)}: Процедура или функция с указанным именем не определена (XMLСтрока)
 oChildProcess = oService.Get("Win32_Process.Handle=" + <<?>>XMLСтрока(oApp.ProcessID));
{(15738,26)}: Процедура или функция с указанным именем не определена (XMLСтрока)
 PIDЭтогоСеанса = <<?>>XMLСтрока(oChildProcess.ParentProcessID);
{(14514,3)}: Процедура или функция с указанным именем не определена (ЗапуститьСистему)
 <<?>>ЗапуститьСистему(СтрокаЗапуска);
{(14516,21)}: Процедура или функция с указанным именем не определена (КаталогПрограммы)
 СтрокаЗапуска1с = <<?>>КаталогПрограммы() + "1cv8";

**Comment by nixel2007** [comment]
А в веб-клиенте вообще есть поддержка ТестируемогоПриложения?

**Comment by vdm5** [comment]
Да, в веб-клиенте есть поддержка тестируемого приложения, ровно как и менеджера тестирования.
![image](https://user-images.githubusercontent.com/29339414/28071350-56f996c6-6658-11e7-96d2-f77df2679e18.png)

**Comment by Pr-Mex** [comment]
@vdm5 
Web клиент не может быть TestManager, только TestClient.

Если вы хотите проверять работу TestClient в Web, тогда вам надо запустить TestManager в тонком клиенте, а TestClient в Web.

Поэтому нет смысла запускать VB в браузере. 

Предлагаю issue закрыть.

**Comment by vdm5** [comment]
Леонид, благодарю за разъяснение. Предлагаю при открытии формы Ванессы проверять, если она открывается в веб-клиенте, то выводить осмысленное сообщение, что "...нельзя открывать ее в вебе...", а сейчас открытие просто падает с ошибкой, что не совсем правильно)). Кстати, не я один этой "тонкости" не знал....

**Comment by nixel2007** [comment]
> а сейчас открытие просто падает с ошибкой, что не совсем правильно

оно падает на ошибке компиляции модуля. Единственная возможность не падать в таком случае - все процедуры оборачивать в Выполнить/Вычислить, которые... тоже не работают в веб-клиенте :)

Выглядит как необходимое ограничение, которое просто должно быть описано в readme

**Comment by vdm5** [comment]
а если в процедуре ПриСозданииНаСервере обернуть инструкцией препроцессора вызов метода Возврат
#Если ВебКлиент Тогда
      Возврат;
#КонецЕсли
тогда при открытии этой формы в веб-клиенте она сразу же и закроется, не доходя до описанных ошибок.

**Comment by vdm5** [comment]
или делать дальше уже в коде обертку инструкциями препроцессора, и это не кажется сложным. Так или иначе, любая форма должна корректно открываться или корректно НЕ открываться при любом режиме работы 1С:Предприятия -я за этот подход))

**Comment by nixel2007** [comment]
@vdm5 да, инструкции препроцессору я как-то упустил из виду :) 
Не уверен, что хватит оборачивания при создании на сервере - модуль-то компилируется (или падает) целиком. А каждую функцию оборачивать... Трудозатратно, хотя и реализуемо :)

**Comment by vdm5** [comment]
Никита, решайте тогда с Леонидом, по какому пути пойдете))

**Comment by artbear** [comment]
Указание в документации вполне устроит для столь частного случая.
