### ISSUE TITLE
Правильный URL запуска Web клиента

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#636]
https://its.1c.ru/db/v8310doc#bookmark:dev:TI000001065

Итак есть возможность запуска Web клиента тестирования

тогда настройка VB будет выглядеть как

Имя: WebTest
Адрес инфобазы; http://localhost/testbase/
Дополнительные параметры: &N=Тесть&P=123456
Порт: 1538
```

в режиме отладки запускается следующая строка

```
http://localhost/testbase?TESTCLIENT&TESTCLIENTID=WebTest&N=Тесть&P=123456
```

цитата с ИТС

```
Адрес веб-сервера, на котором развернуто тестируемое приложение. Адрес информационной базы знать не обязательно!
Номер TCP-порта, через который веб-сервер будет передавать данные между менеджером и клиентом тестирования.
Идентификатор конкретного экземпляра тестируемого приложения, исполняющегося в веб-клиенте.
```

согласно ИТС можно создать следующий файл (хотя можно и не создавать)

```
<config xmlns="http://v8.1c.ru/v8/testcfg">
    <testports range="1538:1539"/>
</config>
```

предположим я вибираю нестандратный порт 41540, тогда в дополнительные параметры уедут

```
Дополнительные параметры: &N=Тесть&P=123456&TPORT=41540
```

ну и тогда меняю настроечный файл

```
<config xmlns="http://v8.1c.ru/v8/testcfg">
    <testports range="41540:41540"/>
</config>
```

После всех этих манипуляция скотина Web сервер (Apache) отказывается запускаетЬ тест-клиент хоть на стандартном порту 1538, хоть на нестандартном 41540

Особенность проявляется на платформе x64 - 8.3.10.2252,

Нужно добыть точно правильную строку запуска в условиях стандартных и нестандартных портов - сейчас совсем неясно низ из ИТС, ни из VB как оно должно работать

**Comment by allustin** [comment]
```
При тестировании через веб-клиент информационной базы, которая расположена на сервере "1С:Предприятия", необходимо подключаться по адресу и порту менеджера кластера сервера (порт по-умолчанию 1541).
Значение по умолчанию: 1538. 
```
просто молодцы ```необходимо подключаться по адресу и порту менеджера кластера сервера```

**Comment by Pr-Mex** [comment]
На CI работает проверка TestClient в режиме Web в Chrome.
Закрываю.
