### ISSUE TITLE
В процессе проверки вылазят левые окна

### ISSUE THREAD

**Issue by viskvortsov** [silverbulleters/vanessa-behavior#637]
Хотел спросить как боретесь с всплывающими окнами в типовых конфигурациях.
Недавно стала всплывать проверка лицензирования. Не знаю как ее убрать, чтобы не мешала.

**Comment by nixel2007** [comment]
Посмотрите vanessa-runner. Там есть пример закрытия этого окна.

**Comment by Pr-Mex** [comment]
@viskvortsov наверно правильнее всего сразу ввести эти данные.
Если вы используете заранее подготовленный dt с тестовыми данными - тогда лучше сразу указать данные регистрации в нём.
