### ISSUE TITLE
Ошибка при вызове метода контекста (Выбрать)

### ISSUE THREAD

**Issue by Egor1987** [silverbulleters/vanessa-behavior#639]
Ванесса Бихевиор 1.1.036. Накликал такой фиче-файл:

Как <Роль>
Я хочу <описание функционала> 
Чтобы <бизнес-эффект> 

Контекст: 
        Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>

```
Когда В панели разделов я выбираю "Продажи"
И В панели функций я выбираю "Счета-фактуры выданные"
Тогда открылось окно "Счета-фактуры выданные"
И я нажимаю на кнопку "Счет-фактура на суммовую разницу"
Тогда открылось окно "Счет-фактура выданный на суммовую разницу (создание)"
И я открываю выпадающий список "Организация"
И я нажимаю кнопку выбора у поля "Организация"
И из выпадающего списка "Организация" я выбираю "хх"
И я открываю выпадающий список "Контрагент"
И из выпадающего списка "Контрагент" я выбираю "ООО Ромашка"
И я нажимаю кнопку выбора у поля "Документ-основание"
```

В строке "И я нажимаю кнопку выбора у поля "Документ-основание" получаю ошибку: 

Ошибка при вызове метода контекста (Выбрать): Метод не может быть вызван для данного объекта (Документ-основание). ИмяПроцедуры: ЯНажимаюКнопкуВыбораУПоля 
версия платформы 8.3.9.2170.

Как это исправить?

**Comment by Pr-Mex** [comment]
@Egor1987 
Попробуйте на свежей версии VB.

**Comment by Pr-Mex** [comment]
Должно работать на текущей версии как мастер, так и девелоп. Переоткройте ищут если проблема повторится.
