### ISSUE TITLE
Рефакторинг структуры каталогов под bootstrap

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#64]
Для целей внедрения необходимо привести все проекты к единой рекомендованной нами структуры каталогов

https://github.com/silverbulleters/vanessa-bootstrap

**Comment by Pr-Mex** [comment]
@allustin закроешь задачу?

**Comment by allustin** [comment]
В целом я думаю да - правда там еще нужно документацию накопить: но это уже в рамках релизов
