### ISSUE TITLE
Ошибка после отказа в диалоге открытия каталога/фала фич

### ISSUE THREAD

**Issue by JohnyDeath** [silverbulleters/vanessa-behavior#65]
Если нажать на "Загрузить фичи из каталога" или "Загрузить фичу" и далее в открывшемся диалоге ничего не выбрать и закрыть окно (например по "Отмена"), то вываливается ошибка

**Comment by Pr-Mex** [comment]
Есть такое. Починил. Но это полностью проблему не решает, т.к. сейчас нет поддержки асинхронных вызовов. Сейчас надо чтобы было так:
Режим использования синхронных вызовов = Использовать.
