### ISSUE TITLE
ОФ: запуск из командной строки выдает ошибку

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#652]
ОФ: запуск из командной строки выдает ошибку
из ванесса-раннер.

>Указан неверный параметр запуска: `StartFeaturePlayer;VBParams=C:\_SilverBullet\original\UPPOMC\VBParams.json;workspaceRoot=C:\_SilverBullet\original`

Для УФ ошибок при тех же параметрах нет.

**Comment by artbear** [comment]
![image](https://user-images.githubusercontent.com/2920817/28524354-d4dba66c-7088-11e7-9626-562d6e07df69.png)

**Comment by Pr-Mex** [comment]
@artbear 
Попробуйте на актуальной версии: 1.1.063.

**Comment by Pr-Mex** [comment]
@artbear 
Проверь, плиз, на текущей версии.

**Comment by Pr-Mex** [comment]
@artbear
Проверь на 1.1.067.

**Comment by Pr-Mex** [comment]
Закрываю.
