### ISSUE TITLE
Серьезная проблема работы продукта - перестали нажиматься кнопки в вопросах

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#654]
При обновлении с 1.1.054 на любую более позднюю версию начинают падать ранее проходившие фичи.
Падает сразу же первоначальное заполнение тестовых данных.

+ фичи проходят на 1.1.054, аллюр зеленый, ошибок в логе нет
+ больше ничего не меняю в репо и 1С (платформа та же), только обновляюсь на последнюю (64)
+ запускаю фичи, получаю падение тут же!!
+ откатываюсь назад, все опять зеленое

Соответственно, пока версии 1.1.055 и выше юзать нельзя :(

### Сценарий довольно простой
+ БСП-совместимая конфа (например, сама БСП или СППР или УТ или еще что-нибудь)
+ создаем пустую базу, загружаем конфигурацию
+ не создаем никаких пользователей !!
+ открываем Предприятие без пользователя в режиме менеджера тестирования
+ открываем VB
+ стартуем новый тест-клиент (Этот клиент)
+ включаем запись действий
+ далее создаем первого пользователя в режиме Предприятия средствами БСП
+ нажимаем Записать
+ получаем вопрос о необходимости добавления первого пользователя в группу администраторов
+ отменяем вопрос !!
+ переключаем в менеджер тестирования
+ останавливаем запись
+ получаем набор шагов
+ вместо последнего шага используем `И я нажимаю на кнопку "Да"` для создания пользователя
+ записываем набор шагов в фичу 
+ пытаемся выполнить данную фичу для данного тест-клиента
+ получаем баг :( - нажатие на кнопку "Да" не выполняется и окно вопроса остается висеть.

### Вот пример реализации упомянутых выше шагов
```gherkin
@tree
@FirstStart

Функциональность: Администрирование пользователей

Сценарий: Создание в новой инфобазе пользователей и настройка их прав

Впервые запускаю инфобазу и создаю пользователя Администратор

	И я запускаю клиент тестирования с автоопределением пользователя
# шаг выше можно выполнить вручную или через обычный шаг подключения пользователя

	И я создаю пользователя Администратор
```

```bsl
&НаКлиенте
//И я настраиваю пользователя Администратор
//@ЯСоздаюПользователяАдминистратор()
Процедура ЯСоздаюПользователяАдминистратор() Экспорт
	РазрешитьОткрытиеВнешнихОбработок();
	
	Ванесса.Шаг("И В панели разделов я выбираю ""Администрирование""");
	Ванесса.Шаг("И В панели функций я выбираю ""Настройки пользователей и прав""");
	Ванесса.Шаг("И открылось окно ""Настройки пользователей и прав""");
	Ванесса.Шаг("И я нажимаю на кнопку ""Пользователи""");
	Ванесса.Шаг("И открылось окно ""Пользователи""");
	
	Если Не ЕстьПользовательАдминистратор() Тогда
		Ванесса.Шаг("И я нажимаю на кнопку ""Создать""");
		Ванесса.Шаг("И открылось окно ""Пользователь (создание)""");
		Ванесса.Шаг("И в поле ""Полное имя"" я ввожу текст ""Администратор""");
		Ванесса.Шаг("И я нажимаю на кнопку с именем ""ФормаЗаписать""");
		Ванесса.Шаг("И открылось окно ""Запись пользователя информационной базы""");
		Ванесса.Шаг("И я нажимаю на кнопку ""Да"""); // ВОТ ЗДЕСЬ ВСЕ И ОСТАНАВЛИВАЕТСЯ !!
	КонецЕсли;
КонецПроцедуры


&НаКлиенте
Процедура РазрешитьОткрытиеВнешнихОбработок()
	ОкноПредупрежденияБезопасности = КонтекстСохраняемый.ТестовоеПриложение.НайтиОбъект(Тип("ТестируемоеОкноКлиентскогоПриложения"), "Предупреждение безопасности");
	Если ОкноПредупрежденияБезопасности = Неопределено Тогда
		Возврат;
	КонецЕсли;
	
	КнопкаНеЗапрещать = ОкноПредупрежденияБезопасности.НайтиОбъект(Тип("ТестируемаяКнопкаФормы"),, "НеЗапрещать");
	Если КнопкаНеЗапрещать = Неопределено Тогда
		ВызватьИсключение "Найдено окно предупреждения но на нем нет кнопки ""Не запрещать""";
	КонецЕсли;
	
	КнопкаНеЗапрещать.Нажать();
	
КонецПроцедуры


&НаСервереБезКонтекста
Функция ЕстьПользовательАдминистратор()
	Результат = Ложь;
	
	Запрос = Новый Запрос;
	Запрос.Текст = 
	"ВЫБРАТЬ
	|	Пользователи.Ссылка
	|ИЗ
	|	Справочник.Пользователи КАК Пользователи
	|ГДЕ
	|	Пользователи.Наименование = ""Администратор""";
	
	РезультатЗапроса = Запрос.Выполнить();
	Если Не РезультатЗапроса.Пустой() Тогда
		Результат = Истина;
	КонецЕсли;
	
	Возврат Результат;
КонецФункции

```

**Comment by 1cgh** [comment]
Там косяк в открылосьокно. Точнее косяк в платформе, и как следствие в снимаете, код которого косяк платформы сейчас не учитывает

**Comment by artbear** [comment]
А как же правильная работа в 1.1.054 на этой же платформе?
в новых версиях зачем-то убрали полезный обход бага платформы? :(

**Comment by 1cgh** [comment]
https://github.com/silverbulleters/vanessa-behavior/commit/eaa9d9c35af385a2520d91380c22b127193e4f2a#commitcomment-23263870

**Comment by artbear** [comment]
Ага, похоже, тот самый баг.
Код какой-то странноватый в коммите :(
зачем нужно было менять исходный текст этого метода?

**Comment by 1cgh** [comment]
Видимо, хотели добиться более корректной работы шага: окно открылось = есть такое открытое окно + оно является активным
Старый вариант проверял только наличие окна среди открытых.

Сейчас получается, что из-за бага платформы нужно
- либо искать альтернативу ПолучитьАктивноеОкно, корректно работающее в том числе и для служебных окон (вопрос, предупреждение, ...)
- либо для служебных окон вводить отдельный шаг
- либо возвращаться к чуть доработанному старому варианту, когда ищем среди всех открытых и при исключении сообщаем инфу об активном окне

**Comment by Pr-Mex** [comment]
Проблема оказалась с модальными диалогами, у которых нестандартный заголовок окна.
Стандартный - это "1С:Предприятие", а ПоказатьВопрос() позволяет задать любой заголовок.
Раньше обход бага поиска активного окна работал и для них, но потом сломался.
Приношу свои извинения.
Добавил сценарий для проверки работы этой ситуации.
Проверьте работу сценариев на 1.1.065.

**Comment by artbear** [comment]
На 1.1.065 все равно падает

![image](https://user-images.githubusercontent.com/2920817/28625862-2155f738-7226-11e7-889e-3965805c1969.png)

**Comment by artbear** [comment]
В 1.1.065 проблема устранена.
