### ISSUE TITLE
При загрузке VB 1.1.065 в 8.3.10.2466 в режиме совместимости с "Версия 8.3.4" выдается ошибка "Процедура или функция с указанным именем не определена (СтрШаблон)"

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#656]
При загрузке VB 1.1.065 в 8.3.10.2466 в режиме совместимости с "Версия 8.3.4" выдается ошибка `Процедура или функция с указанным именем не определена (СтрШаблон)`
`Процедура или функция с указанным именем не определена (СтрНайти)`

Конфигурация - Документооборот 8 ПРОФ, редакция 1.4 (1.4.2.1)

Ошибка инициализации модуля: 
```
ВнешняяОбработка.ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.Форма.Форма.Форма
по причине:
{ВнешняяОбработка.ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.Форма.Форма.Форма(87,20)}: 
Процедура или функция с указанным именем не определена (СтрШаблон)

СтрокаОшибки = <<?>>СтрШаблон("В таблице <%1> отсутствует колонка <%2>, 
указнная в параметрах.", ИмяТЧ, ЭлементФильтра.Ключ);

{ВнешняяОбработка.ВТаблицеЯПерехожуКСтрокеСодержащейПодстроки.Форма.Форма.Форма(100,9)}: 
Процедура или функция с указанным именем не определена (СтрНайти)

ИЛИ <<?>>СтрНайти(ЗначениеКолонкиTesClient, ЭлементФильтра.Значение) = 0 Тогда
```

Вопрос - разве VB уже не поддерживает старые версии ??

**Comment by artbear** [comment]
`СтрНайти` используется только в указанном файле.

А вот `СтрШаблон` (3 раза) еще есть в файле
`features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсом.epf`

**Comment by Pr-Mex** [comment]
@artbear 
Проверь на 1.1.066.

**Comment by Pr-Mex** [comment]
@artbear
Проверь на 1.1.067.

**Comment by Pr-Mex** [comment]
Закрываю.
