### ISSUE TITLE
Странные путающие и не помогающие сообщения в случае неверно написанных фич

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#659]
При загрузке некоторых фич, чаще в случае загрузки неверно написанных фич,
выдаются странные сообщения.
Сообщения очень странные, путающие и не помогающие, совершенно не информативные.
  + Приведены ниже на скриншотах.

```
Ошибка при построении дерева.
ЗагрузитьФичиПродолжение:{ВнешняяОбработка.FeatureReader.МодульОбъекта(316)}: Ошибка при вызове метода контекста (Получить): Значение индекса выходит за границы диапазона
```

Дополнительно:
+ я включил выдачу отладочных сообщений в логи, а в них только ссылки на подгружаемые каталоги фич, но не на конкретные фичи.
+ так что нельзя узнать, какая же конкретная фича виновна в проблеме загрузки.

+ и такое уже не в первый раз
  + сообщение с "ЗагрузитьФичиПродолжение ..." вижу не в первый раз

Предлагаю добавить показ пути неверной фичи и более информативные сообщения.

Платформа: 1С:Предприятие 8.3 (8.3.9.1818)
Конфигурация: не типовая, на базе БСП
Режим: Серверный (сжатие: усиленное)
Приложение: Тонкий клиент
Локализация: Информационная база: русский (Россия), Сеанс: русский
Вариант интерфейса: Такси

![image](https://user-images.githubusercontent.com/2920817/28863517-f52d23c4-7771-11e7-87aa-e3eb9b8f78c2.png)

![image](https://user-images.githubusercontent.com/2920817/28863534-fcfc661e-7771-11e7-9fb5-23337d2895bf.png)

**Comment by Pr-Mex** [comment]
Добавил вывод имени проблемной фичи, если из-за неё не получилось построить дерево.
@artbear 
Проверь на свежей версии, плиз.

**Comment by Pr-Mex** [comment]
Подробное сообщение добавлено. Переоткройте ищут если проблема повторится.
