### ISSUE TITLE
Неверное ключевое слово "Затем", которого нет в типовом геркине

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#660]
Проблема в файле `features\Libraries\VB\VBManager.feature`
Неверное ключевое слово "Затем", которого нет в типовом геркине

плагин VSC выдает ошибку на этом файле
подсветка также не работает.

Предлагаю исключить это слово, заменив на `Когда` или `Тогда`

```
[Extension Host] error parse file 
c:\projects\SB\vanessa-behavior\features\Libraries\VB\VBManager.feature:
CompositeParserException: 
Parser errors:
(18:2): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, 
#ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, 
got 'Затем я запускаю несколько сеансов раннеров согласно указанных настроек'
(20:2): expected: 
#EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, 
#ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, 
got 'Затем я выполняю каждую фичу из полученного списка'
(27:6): expected: 
#EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, 
#ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, 
got 'Затем  я загрузил в раннер текущий фича файл и запустил на выполнение'
```

Также это слово есть еще в нескольких файлах, поиск VSC показывает это

Пример поиска VSC
![image](https://user-images.githubusercontent.com/2920817/28864252-93e3a784-7774-11e7-9bde-6c19564d88e3.png)

**Comment by artbear** [comment]
Никита подсказал, что есть уже закрытый ишуз https://github.com/silverbulleters/vanessa-behavior/issues/660
в котором написано, что проблема уже исправлена!!

**Comment by Pr-Mex** [comment]
Это слово есть в Gherkin.
В этом можно убедиться вот тут
https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin-languages.json#L2415

Проблема на стороне плагина VSC.

**Comment by artbear** [comment]
Проблема на стороне 2х плагинов.
+ Наш по автоподстановке
+ родной от кукумбера по подсветке геркин-файлов.

Кто по второй части ишуз в репо плагина создаст ?

**Comment by nixel2007** [comment]
> Кто по второй части ишуз в репо плагина создаст ?

ты? :)

**Comment by Pr-Mex** [comment]
В vb ошибки нет. Закрываю.
