### ISSUE TITLE
Ошибка "Метод не может быть вызван для данного объекта (Документ расчетов)"

### ISSUE THREAD

**Issue by Egor1987** [silverbulleters/vanessa-behavior#665]
В 1С 8.3 конфа Бухгалтерия 3.0 (ВБ 1.1.066) накликал такой фиче-файл (создание документа "Авизо по расчетам исходящее" вкладка "Дебиторская задолженность" поле "Документ расчетов"): 

```Gherkin
Как <Роль>
Я хочу <описание функционала> 
Чтобы <бизнес-эффект> 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий


Сценарий: <описание сценария>

	Когда В панели разделов я выбираю "Продажи"
	И     В панели функций я выбираю "Авизо по расчетам исходящие"
	Тогда открылось окно "Авизо по расчетам исходящие"
	И     я нажимаю на кнопку "Создать"
	Тогда открылось окно "Авизо по расчетам исходящее (создание)"
	И     я нажимаю кнопку выбора у поля "Организация"
	И     из выпадающего списка "Организация" я выбираю "х ООО"
	И     из выпадающего списка "Подразделение" я выбираю "Основное подразделение"
	И     я нажимаю кнопку выбора у поля "Получатель"
	И     из выпадающего списка "Получатель" я выбираю 'Московский филиал ООО "х"'
	И     в таблице "СуммыДолгаДебиторская" я нажимаю на кнопку "Добавить"
	И     в таблице "СуммыДолгаДебиторская" из выпадающего списка "Контрагент" я выбираю "ООО Ромашка"
	И     я перехожу к следующему реквизиту
	И     в таблице "СуммыДолгаДебиторская" я активизирую поле "Договор"
	И     в таблице "СуммыДолгаДебиторская" я нажимаю кнопку выбора у реквизита "Договор"
	Тогда открылось окно "Договоры"
	И     в таблице "Список" я перехожу к строке:
	| 'Валюта' | 'Организация' | 'Дата'       | 'Наименование'    | 'Вид договора'                         | 'Номер договора' |
	| 'руб.'   | 'х ООО'     | '29.06.2017' | '9 от 29.06.2017' | 'С комиссионером (агентом) на продажу' | '9'              |
	И     в таблице "Список" я активизирую поле "Наименование"
	И     в таблице "Список" я выбираю текущую строку
	Тогда открылось окно "Авизо по расчетам исходящее (создание) *"
	И     в таблице "СуммыДолгаДебиторская" я активизирую поле "Документ расчетов"
	И     в таблице "СуммыДолгаДебиторская" я нажимаю кнопку выбора у реквизита "Документ расчетов"
```

В последней строке получаю ошибку "Метод не может быть вызван для данного объекта (Документ расчетов)"

> Прикладывайте файлы скриншотов
![image](https://user-images.githubusercontent.com/29567290/29522370-ef20a190-8699-11e7-933a-9b4130f0d98e.png)

Как устранить ошибку?

**Comment by Pr-Mex** [comment]
1. Попробуй обновить vb до текущей версии.
2. Реквизит точно доступен для редактирования в данный момент?

**Comment by Egor1987** [comment]
2. В реквизите в котором происходит ошибка выбирается документ и он доступен

**Comment by Pr-Mex** [comment]
@Egor1987 
Выложи, пожалуйста, в доступ DT на котором можно воспроизвести проблему.

**Comment by Egor1987** [comment]
Что такое DT?

**Comment by nixel2007** [comment]
Файл выгрузки информационной базы

**Comment by Pr-Mex** [comment]
@Egor1987 
Можешь выложить базу, на которой проблема воспроизводится?

**Comment by Egor1987** [comment]
Вот ccылка dt на котором воспроизводится проблема: http://transfiles.ru/aqmgv

**Comment by Pr-Mex** [comment]
@Egor1987 
База есть.
Скажи логины/пароли для доступа в неё.
И, надеюсь, это не твоя "боевая" база? :-)

**Comment by Egor1987** [comment]
Доменная авторизация

**Comment by Egor1987** [comment]
База тестовая

**Comment by Egor1987** [comment]
Напишите свой e-mail, скину на него.

**Comment by Egor1987** [comment]
E-mail нашел, на почту логин-пароль отправил.

**Comment by Pr-Mex** [comment]
@Egor1987 
Я тебе ответил на емейл. Не подходят логины/пароли.

**Comment by Egor1987** [comment]
Ответил на почту.

**Comment by Pr-Mex** [comment]
@Egor1987 
Ответил в почту.

**Comment by Egor1987** [comment]
Ответ на почту не приходил.

**Comment by Pr-Mex** [comment]
@Egor1987 
Не получается запустить базу. У пользователя нет прав.

**Comment by Egor1987** [comment]
Отправил письмо на почту с темой "По Ванессе Бихевиор".

**Comment by Pr-Mex** [comment]
@Egor1987 
Не работает.
![image](https://user-images.githubusercontent.com/8627416/30077104-7947fc2a-9283-11e7-9a78-2eb643f199eb.png)

**Comment by artbear** [comment]
Ребята, вы уже 15 дней пытаете доступ к проблемной базе, а мы все это наблюдаем :(
Может быть, уже какой-новый способ попробуете? :)

**Comment by Egor1987** [comment]
Разобрался, решение: вместо строки
"И     в таблице "СуммыДолгаДебиторская" я нажимаю кнопку выбора у реквизита "Документ расчетов"" нужно написать строку:
"И     в таблице "СуммыДолгаДебиторская" я выбираю текущую строку" 

Тему можно закрывать.
