### ISSUE TITLE
Работа с таблицами. Не работает сравнивалка таблиц в 1.1.074

### ISSUE THREAD

**Issue by git22ura** [silverbulleters/vanessa-behavior#666]
Не работает сравнивалка таблиц в 1.1.074 (c6318b0db3de4ab4c624212c67f9408b8239a5ed ) 

```
Тогда Табличный документ формы с именем "Результат" стал равен макету с именем "Макет"
```
дает ошибку:

```
{ВнешняяОбработка.VanessaBehavior.МодульОбъекта(1755)}: [Failed] Таблицы должны совпадать, а они различны
Различия в таблицах:
Ожидали статус <ТаблицыСовпадают>, а получили <РазноеКоличествоСтрок>


ИмяФайла=C:\TestTools\vanessa-behavior\features\Libraries\UITestRunner\step_definitions\РаботаСИнтерфейсомДополнительный.epf, ИмяПроцедуры=ТабличныйДокументФормыСИменемСталРавенМакетуСИменем, версия VB=ver 1.1.074, версия платформы=8.3.10.2505, режим совместимости=Версия8_3_8
```

Сравниваемые таблицы из макета и из отчета по факту идентичны. Бегло прошелся отладчиком - одна таблица правильная (Таб1), вторая (Таб2) принципиально неправильная. Количество строк, содержимое - другое.

Откатился до коммита aa048e6aae7324e3753f799d9bf408ad9116dac3 - тут работает.

**Comment by Pr-Mex** [comment]
@git22ura  Сравнение макетов активно дорабатывается, чтобы оно одинаково работало в тонком и web клиенте. 
Дай dt и фичу, на которой у тебя воспроизводится проблема.

**Comment by git22ura** [comment]
[ДТ и тесты.zip](https://github.com/silverbulleters/vanessa-behavior/files/1247867/default.zip)
dt и два теста. Длинный падает, короткий проходит. Версия ВБ: c6318b0db3de4ab4c624212c67f9408b8239a5ed , версия платформы: 8.3.10.2168

**Comment by Pr-Mex** [comment]
@git22ura 
Вернул поведение шага к прежнему.
Проверь.

**Comment by git22ura** [comment]
Да, работает
