### ISSUE TITLE
Стопорится выполнение VB при автозапуске и установке автозакрытия тест-клиентов

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#667]
Проблема возникает далеко не в первый раз на разных проектах, подзадолбало.

+ Дано большое количество фич, запускающих и закрывающих тест-клиенты
+ Включена настройка `"ЗакрытьTestClientПослеЗапускаСценариев": true,`
+ После завершения ВБ и получения сообщения "были ошибки" получаем модальное окно
```
{ВнешняяОбработка.РаботаСTestClient.Форма.Форма.Форма(367)}: 
Не нашел профиля TestClient с именем <АбрамовО (МО)> 
хотя он должен быть активным в данный момент.
    ВызватьИсключение "Не нашел профиля TestClient с именем <" + ТекущийПрофильTestClient + 
"> хотя он должен быть активным в данный момент.";
```

Насколько я понимаю, проблема в вызове кода из vanessa-behavior.epf - модуля формы УправляемаяФорма
```bsl
		Если Объект.ЗакрытьTestClientПослеЗапускаСценариев Тогда
			//ЗакрытьTestClientЕслиОнПодключен();
			// закроем все TestClient которые были запущены
			Для каждого СтрокаДанныеКлиентовТестирования Из ДанныеКлиентовТестирования Цикл
				Шаг("И я закрываю TestClient """ + СтрокаДанныеКлиентовТестирования.Имя + """");
			КонецЦикла;			
		КонецЕсли;	 
```
внутри шага `И я закрываю TestClient` выбрасывается исключение, которое никак не ловится, и стопорит автоматическое выполнение :(

**Предлагаю вставить вызов шага в блок Попытка-исключение.**
в случае ловли исключения 
+ писать сообщения в нужные логи
+ менять код возврата
+ другие необходимые действия для ошибок тестирования

**Comment by artbear** [comment]
Проверяли на последней версии ВБ 1.1.075

**Comment by Pr-Mex** [comment]
@artbear Решено в 1.1.076.
Добавил попытку/исключение.
Проверь.

**Comment by Pr-Mex** [comment]
Закрываю. Прошу сообщить если ошибка вновь появится.
