### ISSUE TITLE
Feature files and video-doc IN ITALIAN

### ISSUE THREAD

**Issue by 1Attimo** [silverbulleters/vanessa-behavior#671]
Здравствуйте, 
Почитав [Issue 427](https://github.com/silverbulleters/vanessa-behavior/issues/427)
и пообщавшись с 1C-Romania, захотелось таких же возможностей на итальянском языке. Подскажите куда копать? Файл it.mxl переведен и готов. 
Спасибо

**Comment by Pr-Mex** [comment]
@1Attimo 
Приветствую.
Лучший вариант - это вам сделать пул реквест с этим файлом.
Или можете его прислать мне на pautovlv@gmail.com, я добавлю.

**Comment by 1Attimo** [comment]
@Pr-Mex 
Спасибо Леонид. Послан емайл.

**Comment by 1C-Romania** [comment]
> Файл it.mxl переведен и готов. Спасибо
Супер-новость - спасибо, Ольга!

**Comment by Pr-Mex** [comment]
Закрываю.
