### ISSUE TITLE
Пустой адрес снипета у шага

### ISSUE THREAD

**Issue by Egor1987** [silverbulleters/vanessa-behavior#679]
> Скачал ванессу версии 96. В базе бухгалтерия 3.0 открыл файл vanessa-behavior.epf как внешнюю обработку. Как обычно запустил тест клиент, нажал запись действий юзера, накликал такой feature-файл:  

```Gherkin
Функционал: <описание фичи>

Как <Роль>
Я хочу <описание функционала> 
Чтобы <бизнес-эффект> 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>

	И     В командном интерфейсе я выбираю "Операции" "Журнал операций"
	Тогда открылось окно "Журнал операций"
	И     в таблице "Список" я выбираю текущую строку

```
При выполнении сценарии появляется ошибка:

![image](https://user-images.githubusercontent.com/29567290/33213241-398633da-d140-11e7-8f40-d5dfc0661809.png)

С предыдущей 66 ванессой таже проблема случилась.

Похоже карета превратилась в тыкву :-1: 

Как устранить проблему?

**Comment by Pr-Mex** [comment]
Покажите, какие у вас подключен библиотеки.

**Comment by Egor1987** [comment]
Используемая конфигурация Бухгалтерия предприятия 3.0 Корп (нетиповая).  Какие библиотеки имеются ввиду? Если имеется ввиду библиотека станд. подсистем, то ее не используем.

**Comment by Egor1987** [comment]
![2](https://user-images.githubusercontent.com/29567290/33259238-b58fa006-d375-11e7-9985-7de54f7c27fc.jpg)

**Comment by Egor1987** [comment]
Cпросил про библиотеки у спецов по 1С, они не в курсе что за библиотеки в 1с 8. Может имеется ввиду используемые dll?

**Comment by pumbaEO** [comment]
Если открыть обработку, то справа будет вкладка "Бибилиотеки" - там указываетса путь обычно к библиотекам обычно это ПолныйПутьКВанессе/features/libraries

**Comment by Egor1987** [comment]
Ок, сейчас посмотрю.  
Как сделать пожертвование на развитие проекта через гитхаб? Кнопку "Post a bounty" не нашел

**Comment by Egor1987** [comment]
Да, я сам удалил содержимое папки features, исправил и ВБ заработала. Спасибо

**Comment by Pr-Mex** [comment]
>Как сделать пожертвование на развитие проекта через гитхаб? Кнопку "Post a bounty" не нашел

@allustin
Это только возможно через спонсорство решения задачи?

**Comment by Egor1987** [comment]
Эта задача решена.
