### ISSUE TITLE
Ошибка "Ожидали, что активным окном будет *1 окно*, а нашли другое окно " 

### ISSUE THREAD

**Issue by Egor1987** [silverbulleters/vanessa-behavior#680]
Добрый день, снова непобедимая проблемой с всплывающими окнами.

Обновил ВБ до 96 версии, обновил платформу 1С Бухгалтерия  до версии 8.3.10.2667. 
Накликал простенький скрипт воспроизводящий проблему:

```Gherkin
Функционал: <описание фичи>

Как <Роль>
Я хочу <описание функционала> 
Чтобы <бизнес-эффект> 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий


Сценарий: <описание сценария>

	И     В командном интерфейсе я выбираю "Операции" "Отражение НДС к вычету"
	Тогда открылось окно "Отражение НДС к вычету"
	И     я нажимаю на кнопку "Создать"
	Тогда открылось окно "Отражение НДС к вычету (создание)"
	И     я перехожу к закладке "Товары и услуги"
	И     я перехожу к закладке "Страницы"
	И     в таблице "ТоварыУслуги" я нажимаю на кнопку "Добавить"
	И     в таблице "ТоварыУслуги" я нажимаю кнопку выбора у реквизита "Номенклатура"
	Тогда открылось окно "Выбор типа данных"
	И     я нажимаю на кнопку "ОК"
	Тогда открылось окно "Отражение НДС к вычету (создание) *"
	И     в таблице "ТоварыУслуги" из выпадающего списка "Номенклатура" я выбираю "Номенклатура"
	Тогда открылось окно "Номенклатура"
	И     я перехожу к следующему реквизиту
	И     я нажимаю на кнопку "Выбрать"
	Тогда открылось окно "Отражение НДС к вычету (создание) *"
	И     в таблице "ТоварыУслуги" я нажимаю кнопку выбора у реквизита "Номенклатура"
```

В строке "Тогда открылось окно "Отражение НДС к вычету (создание) *"" 
после строки "И     я нажимаю на кнопку "ОК"" появляется нижеуказанная ошибка:

> Прикладывайте файлы скриншотов
![1](https://user-images.githubusercontent.com/29567290/33553998-6cff7678-d914-11e7-9e78-0fbda6bce073.jpg)

Как решить эту часто встречающуюся ошибку?

**Comment by Pr-Mex** [comment]
@Egor1987 
1. А какое окно реально активно в данный момент?
2. Попробуй на свежей версии VB 1.1.101. Были изменения при поиске активного окна.

**Comment by Egor1987** [comment]
1. ВБ прерывается на этом окне:
![1](https://user-images.githubusercontent.com/29567290/33652528-3ad6dd92-da83-11e7-9b10-b832963097ef.jpg)

**Comment by Egor1987** [comment]
Обошел эту ошибку другими действиями, но эта же ошибка возникает в других документах. Тему можно закрывать
