### ISSUE TITLE
Ошибка "Ожидали, что активным окном будет <Внимание!>, а нашли <Декларация по налогу по имуществу>"

### ISSUE THREAD

**Issue by Egor1987** [silverbulleters/vanessa-behavior#683]
Приветствую. Снова появилась ошибка из заголовка темы "Ожидали, что активным окном будет <Внимание!>, а нашли <Декларация по налогу по имуществу>"

Конфигурация Бухгалтерия 3

```Gherkin
Функционал: <описание фичи>

Как <Роль>
Я хочу <описание функционала> 
Чтобы <бизнес-эффект> 

Контекст: 
	Дано Я запускаю сценарий открытия TestClient или подключаю уже существующий

Сценарий: <описание сценария>
	И     В командном интерфейсе я выбираю "Отчеты" "Регламентированные отчеты"
	Тогда открылось окно "1С-Отчетность"
	И     в таблице "Отчеты" я нажимаю на кнопку "Создать"
	Тогда открылось окно "Виды отчетов"
	И     в таблице "СписокРанееСозданные" я перехожу к строке:
	| 'Наименование'                      |
	| 'Декларация по налогу на имущество' |
	И     я нажимаю на кнопку "Выбрать"
	Тогда открылось окно "Декларация по налогу на имущество"
	И     я нажимаю кнопку выбора у поля "Организация"
	И     из выпадающего списка с именем "Организация" я выбираю '*'
	И     я нажимаю на кнопку "Создать"
	Тогда открылось окно "Внимание!"
```

> 
![1](https://user-images.githubusercontent.com/29567290/34103536-749d21e4-e406-11e7-823b-750f52e8bfae.png)

Что с этим делать? (это массовая ошибка)

**Comment by nixel2007** [comment]
Какая версия платформы?

**Comment by Egor1987** [comment]
8.3.11.2867
Конфигурация Бух. предприятия 3.0.44.202

**Comment by Pr-Mex** [comment]
@Egor1987 
1. Попробуй на VB из ветки Develop.
2. Дай скриншот окна.

**Comment by Egor1987** [comment]
1.  Из ветки develop и обновляю Vanessa

**Comment by Egor1987** [comment]
2  Какого окна?

**Comment by Pr-Mex** [comment]
1. Версия в Develop выше, чем показанная на скриншоте - 1.1.096
2. Скриншот всего окна сеанса 1С в момент возникновения ошибки.

**Comment by Egor1987** [comment]
1. У меня уже целый "зоопарк" этих Ванесс. Что толку через день ее обновлять если ошибка все равно не устранена.
2. Зачем вам скриншот всего окна? Скрин ошибки привел

**Comment by Pr-Mex** [comment]
@Egor1987 
1. Попробуй проверить воспроизведение ошибки на версии 1.1.104. Проблема может быть уже решена.
2. Скриншот нужен, чтобы лучше понять какие окна находятся на экране.
3. Приведи, пожалуйста, полный текст ошибки, который отдаёт VB.

**Comment by Egor1987** [comment]
После обновления проблема исчезла
Спасибо!
