### ISSUE TITLE
При выполнении фич падают последние версии ВБ (1.1.114)

### ISSUE THREAD

**Issue by artbear** [silverbulleters/vanessa-behavior#687]
https://gitter.im/silverbulleters/vanessa-behavior?at=5a73385aac509d207da6ff85

упала свежайшая версия VB 1.1.114 - я только что склонировал из develop
при загрузке фичи все путем.
а вот при выполнении беда :(
```
{ВнешняяОбработка.VanessaBehavior.Форма.УправляемаяФорма.Форма(10600)}: 
Получение элемента по индексу для значения не определено
	ОбработкаТеста = ТаблицаКонтекстовОбработок[ИД].Обработка;
```

Виноваты последние коммиты

![image](https://user-images.githubusercontent.com/2920817/35689647-0f8a71e2-0785-11e8-97be-568eb4132986.png)

**Comment by Pr-Mex** [comment]
@artbear 
Проверил. У меня не воспроизводится.
Приложи, пожалуйста, фичу и библиотеки, которые у тебя подключены.
Если секретные - кидай в личку.

**Comment by artbear** [comment]
Отправил файлы в личку

**Comment by Pr-Mex** [comment]
Ответил в личке. Воспроизвести не получается.
Предлагаю вечером собраться по RDP и посмотреть что там происходит.

**Comment by Pr-Mex** [comment]
@artbear 
получилось решить проблему?
