### ISSUE TITLE
Ошибка в определении видимости по имени реквизита

### ISSUE THREAD

**Issue by xnd1124** [silverbulleters/vanessa-behavior#694]
Шаги ЯВижуЭлементСИменем и ЯВижуЭлементСИменемНаФорме на самом деле всегда ищут по заголовку из-за опечатки в форме РаботаСИнтерфейсом
![image](https://user-images.githubusercontent.com/6578710/37540223-da55568a-295e-11e8-95fb-4d292854698f.png)

**Comment by Pr-Mex** [comment]
Да.
Спасибо!
Исправлю.

**Comment by Pr-Mex** [comment]
Исправлено.
