### ISSUE TITLE
{ВнешняяОбработка.FeatureReader.МодульОбъекта(1229)}: Поле объекта не обнаружено (ЭтоLinux)

### ISSUE THREAD

**Issue by Geraz** [silverbulleters/vanessa-behavior#695]
При загрузки фичи возникает ошибка в обычном приложении.
Прошу добавить одну строчку исправляющую эту ошибку. В [СтруктураПараметров](https://github.com/silverbulleters/vanessa-behavior/blob/develop/src/vanessa-behavior/Form/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0/module.bsl#L2836) добавить 

```bsl
СтруктураПараметров.Вставить("ЭтоLinux",ЭтоLinux);
```

**Comment by kuzyara** [comment]
Пулреквеста не будет?

**Comment by Pr-Mex** [comment]
Уже исправлено.
