### ISSUE TITLE
Ошибка генерации allure отчетов, с помощью allure-cli

### ISSUE THREAD

**Issue by pumbaEO** [silverbulleters/vanessa-behavior#70]
При попытки сгенерировать отчет по xml файлам, allure вываливается с ошибкой:
```
allure.bat generate d:\work\test\
Exception in thread "main" ru.yandex.qatools.allure.data.ReportGenerationException: Could not find any allure results
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:58)
        at ru.yandex.qatools.allure.data.AllureReportGenerator.generate(AllureReportGenerator.java:53)
        at ru.yandex.qatools.allure.AllureMain.main(AllureMain.java:48)
ERROR: Command aborted due to exception org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1).
```
эксперементально выяснил, что необходимо добавить в файл стандартный заголовок
```
<?xml version="1.0" encoding="UTF-8"?>
```
и для тэгов использовать ns 
```
<ns:test-suite-result xmlns:ns="urn:model.allure.qatools.yandex.ru" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

</ns:test-suite-result>
```
все остальное без изменений.

**Comment by Pr-Mex** [comment]
Решено.

**Comment by krohotin** [comment]
allure cli    - 2.4-SNAPSHOT
allure bundle - 1.5.0-RC1
Ошибка воспроизводится. Проверял структуру полученного xml через xsd-схему, взятую с https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd - все корректно

**Comment by Pr-Mex** [comment]
Давай xml, который даёт ошибку.

**Comment by Pr-Mex** [comment]
И какая версия ванессы используется?

**Comment by krohotin** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1448519133193" stop="1448519261575">
  <name>py_testTest</name>
  <labels/>
  <test-cases>
    <test-case start="1448519133193" status="passed" stop="1448519142327">
      <name>test_1</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="a07c4afe-22fa-46da-af69-02e46d606f7d-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519142334" status="passed" stop="1448519148286">
      <name>test_2</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="e7c99743-1aed-4e1e-b9ff-fed83cd512b4-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519148287" status="passed" stop="1448519175271">
      <name>test_3</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="49eae58d-11d8-4e9c-b942-5ba6256657a9-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519175271" status="passed" stop="1448519175594">
      <name>test_3_5</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="c9b29e88-fb45-4018-ac46-a1a5669f5e59-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519175594" status="passed" stop="1448519213032">
      <name>test_4</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="4dc05e57-af55-42c5-9b8e-7856845d6fbe-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519213033" status="passed" stop="1448519224938">
      <name>test_5</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="22bb99f3-8ef4-455c-87dc-e41425e8e7ff-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519224939" status="passed" stop="1448519261558">
      <name>test_6</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="9a1765bf-50a8-443c-8e93-38582f96ce6b-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
    <test-case start="1448519261559" status="passed" stop="1448519261574">
      <name>test_close</name>
      <steps/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="5036-MainThread"/>
        <label name="host" value="Andrey-PC"/>
      </labels>
      <attachments>
        <attachment source="d10fb1bf-16fb-4cff-8349-3db83bc45f43-attachment.txt" title="Captured stdout call" type="text/plain"/>
      </attachments>
    </test-case>
  </test-cases>
</ns0:test-suite>

**Comment by krohotin** [comment]
[acc85d9d-448a-4a59-80cf-84187ab288ac-testsuite .txt](https://github.com/silverbulleters/vanessa-behavior/files/44754/acc85d9d-448a-4a59-80cf-84187ab288ac-testsuite.txt)

**Comment by Pr-Mex** [comment]
А каким софтом был получен данный xml?
Он явно не из Vanessa-Behavior.
