### ISSUE TITLE
Для фича файлов нужна система тегов.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#72]
На данный момент уже очевидно, что фича файлы нужно помечать внутренними тегами. Спецификация Gherkin 2.0 их поддерживает.

Например, не все фичи надо запускать на CI сервере, т.к. у них служебные цели. Например вот эти:
https://github.com/silverbulleters/vanessa-behavior/tree/develop/features/Support/Templates

Было бы удобно пометить их тегом:
@IgnoreOnCI

Или нужен тег, определяющий, нужно ли по фиче генерировать автодокументацию.

Предлагаю обсудить.

**Comment by Pr-Mex** [comment]
Сделано.
Создал два списка, один для исключения фич по тегам, другой для отбора фич по тегам.

**Comment by pumbaEO** [comment]
Хм, пропустил. Почему бы в параметрах запуска не указать список тегов для
запуска или игнорирования?
Еще вопрос мы при запуске тегов исходим из запрета или разрешения, т.е.
если ничего не указано, то все запускаем, если что-то указано то запускаем
только это?

2015-10-01 13:25 GMT+03:00 Pr-Mex <notifications@github.com>:

> Closed #72 <https://github.com/silverbulleters/vanessa-behavior/issues/72>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverbulleters/vanessa-behavior/issues/72#event-424075187>
> .
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by Pr-Mex** [comment]
В параметрах запуска указать теги можно.

Если ничего не указано - то всё загружается.
Можно игнорировать фичи, содержащие нужный теги.
Можно загружать только те фичи, которые содержат нужные теги.
