### ISSUE TITLE
Нет возможности разрабатывать в режиме отказа от асинхронности

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#78]
Когда я создаю конфигурацию с последним режимом перехода на асинхронность
Тогда я получаю ошибку при старте обработки

Ошибка воспроизводится плавающе, в тот момент, когда обработка запускается в первый раз и дерево фич пустое

```
{Форма.УправляемаяФорма.Форма(97)}: Ошибка при вызове метода контекста (Выбрать)
	Если ДиалогОткрытияФайла.Выбрать() Тогда
по причине:
Использование синхронных методов на клиенте запрещено!
```

**Comment by Pr-Mex** [comment]
Не удалось воспроизвести проблему у себя.
Нужно больше информации.

**Comment by allustin** [comment]
@Pr-Mex - сценарий воспроизведения простой

* первый clone в режиме bootstrap
* создаем чистую базу
* открываем обработку bahavior приехавшую через git pull
* пытаемся загрузить каталог Feature из bootstrap

важное замечание - нужна именно новая обработка, в которой еще не успело сработать сохранение настроек

Пока так смог воспроизвести

**Comment by Pr-Mex** [comment]
Попробуй на текущей версии, 0.811.

**Comment by Pr-Mex** [comment]
CI настроен, все сценарии работают в режиме отказа от синхронных вызовов.
Закрываю.
