### ISSUE TITLE
Добавить настройку для работы с тегами.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#80]
Надо добавить два списка.
Один список - теги, которые говорят, что фичу надо проигнорировать.
Второй список - теги, которые говорят, что только фичи с этими тегами надо загружать.
В случае конфликта (два противоположных тега встретились одновременно), фича будет загружена.

**Comment by Pr-Mex** [comment]
Сделано.

**Comment by allustin** [comment]
Зафиксирую - определили тут, что во время коммуникации с заказчиком нужно "драфтовать" требования.

Так что тэг *draft* оказался востребованным

**Comment by Pr-Mex** [comment]
Ок. Хочу отметить, что теги в фичи можно вставлять любые. Их смысл остаётся на усмотрение тех, кто владеет системой.
