### ISSUE TITLE
Плагин Allure report для Jenkins не меняет статус билда

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#82]
При формировании отчета Allure, если есть сценарии со статусом failed, то в отчете это отображается корректно, но статус билда не меняется, и нет настройки, чтобы он изменился.

Нужно менять статус билда каким-то другим образом, учитывая, что 1С не умеет выдавать что-то подобное exit (1).

**Comment by pumbaEO** [comment]
пусть 1с пишет в лог выполнения 1 и тогда, читаем файл лога выполнения и
делаем exit(ПеременнаяЛога)

1 октября 2015 г., 10:21 пользователь Pr-Mex <notifications@github.com>
написал:

> При формировании отчета Allure, если есть сценарии со статусом failed, то
> в отчете это отображается корректно, но статус билда не меняется, и нет
> настройки, чтобы он изменился.
>
> Нужно менять статус билда каким-то другим образом, учитывая, что 1С не
> умеет выдавать что-то подобное exit (1).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/silverbulleters/vanessa-behavior/issues/82>.
>



-- 
З повагою Сосна Євген,
mailto:shenja@sosna.zp.ua
skype:shenjasosna
+380933897103

**Comment by allustin** [comment]
Создал задачу в Allure плагине - а пока придется выкрутиться через костыль с единичкой

**Comment by Pr-Mex** [comment]
Сделано.
