### ISSUE TITLE
Как определяются сниппеты шагов

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-behavior#84]
Если в фиче встречается строка
**Тогда В созданном документе реквизит "ОбращениеКлиент" заполняется значением 5**
тогда по ней будет сгенерирован сниппет:
**ВСозданномДокументеРеквизитЗаполняетсяЗначением(Парам01Строка,Парам02Число)**

что при повторном использовании кода не получится использовать этот сниппет с иным типами параметров (например: **Тогда В созданном документе реквизит "ОбращениеКлиент" заполняется значением "КакаяТоСтрока"**)

**Comment by pumbaEO** [comment]
я добавил в  vbFeatureReader.epf заполнение имени процедуры которая будет заполненна, имхо более правильно все же все называть парам01, парам02

**Comment by Pr-Mex** [comment]
Сделано. Ограничение по типу убрано.
