### ISSUE TITLE
Заменить feature файл на главной странице

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#90]
Сейчас там фича, работающая только вместе с Cucumber.

**Comment by Pr-Mex** [comment]
@allustin Нужен совет, ибо визитная карточка.

**Comment by allustin** [comment]
Взялся - сделаю в субботу.

**Comment by allustin** [comment]
Добил текущую версию.
Остальное по итогам использования - возможно стоит часть документации перенести в WiKI
