### ISSUE TITLE
Переход на xUnitFor1C v4 в качестве запускалки тестов BDD

### ISSUE THREAD

**Issue by wizi4d** [silverbulleters/vanessa-behavior#91]
Предлагаю в качестве запускалки тестов использовать xUnitFor1C v4. API библиотеки к этому полностью готов.
Со своей стороны могу предложить помощь в переходе. Готовый раннер, bdd утверждения, построители отчетов о тестировании и прочие готовые утилиты = profit.

Для работе на основе раннера v4 нужно реализовать [интерфейс плагина-загрузчика](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop_v4_reborn/src/PluginsTemplates/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%B0).
В качестве примера доступны загрузчики:

1. [Загрузчик тестовых файлов типового формата](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop_v4_reborn/src/Plugins/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%A4%D0%B0%D0%B9%D0%BB%D0%B0)
1. [Загрузчик из каталога файловой системы](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop_v4_reborn/src/Plugins/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%9A%D0%B0%D1%82%D0%B0%D0%BB%D0%BE%D0%B3%D0%B0) - базируется на загрузчике фалов (п.1).
1. [Загрузчик тестов из метаданных конфигурации](https://github.com/xDrivenDevelopment/xUnitFor1C/tree/develop_v4_reborn/src/Plugins/%D0%97%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D1%87%D0%B8%D0%BA%D0%98%D0%B7%D0%9F%D0%BE%D0%B4%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8)

**Comment by EvilBeaver** [comment]
+1

**Comment by allustin** [comment]
Пока не будем такого делать.

Подобная попытка уже привела к архитектурным и методологическим противоречиям.

В августе еще было можно, сейчас уже мы ушли в методологических подходах в другую сторону.

**Comment by wizi4d** [comment]
Голосом я предлагал еще в начале лета вести совместную разработку, поэтому про точку невозврата в августе для меня звучит несколько странно.

И можно подробней про архитектурные и методологические проблемы?

И еще мне не совсем понятно, как различие в методологических подходах может мешать использованию инструментария. Звучит как "я не использую пылесос из методологических соображений".

**Comment by wizi4d** [comment]
@allustin не могу достучаться до тебя в hangouts. Хотел бы обсудить некоторые моменты лично.

**Comment by allustin** [comment]
Часть методологии мы сгруппировали тут https://github.com/silverbulleters/vanessa-bootstrap

Например мы отказываемся от понятия "тест", заменяя его на другие понятия, естественно с определенными целями.

hangouts был заблокирован 2 месяца назад как отвлекающий инструмент. Разблокировал до утра . Пиши.

**Comment by allustin** [comment]
Еще раз зафиксирую - мы считаем на данном этапе что unit тесты в 1С избыточны, и BDD полностью их заменять. Так как важно поведение системы в целом.

В 1С мире нет юнитов - есть поведение объектов. все объекты очень сильно связаны и нужно смотреть в комплексе на поведение системы.

из xUnit нам необходим пока только блок ассертов, да и то мы планируем от него отказаться.

Unit тесты - для большинства команд разработки 1С вызывают большие затраты на внедрение. Что не позволительно для 1С мира - где бюджеты команд "короткие"

Поэтому - внедряться в xUnit мы не будем. В том числе и по соображениям лицензионной чистоты.

У нас используется BSD лицензия, которая в некоторых моментах может конфликтовать с лицензией xUnit
