### ISSUE TITLE
не генерируется шаблоны обработок в режиме ненавистной асинхронности

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior#92]
![image](https://cloud.githubusercontent.com/assets/55323/10380484/b251cb46-6e1c-11e5-9f0d-7af657d9528b.png)

Сценарий воспроизведения

* последняя версия develop
* для простоты открываем фичи bootstrap
* нажимаем генерировать шаблоны обработок

**Comment by Pr-Mex** [comment]
Сделано.
