### ISSUE TITLE
Сделать стандартную библиотеку для работы с интерфейсом 1С 8.3 УФ.

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-behavior#99]

**Comment by artbear** [comment]
Отличнейшая идея. Молодцы

**Comment by artbear** [comment]
ИМХО это киллер-фича

**Comment by artbear** [comment]
Только ИМХО для создания/генерации фичи другой проект предназначен, нет?
https://github.com/silverbulleters/vanessa-bdd-editor

**Comment by Pr-Mex** [comment]
Основа сделана.
Для доработок библиотеки создавайте новые задачи.
Закрываю.
